### DISCUSSION TITLE
ACK + minikube + localstack?

### DISCUSSION THREAD

**Discussion by gfaraj** [aws-controllers-k8s/community#2236] [Q&A]
Has anyone gotten ACK to work with minikube and localstack? Is there any reason why this would not work? I'm looking to start using ACK but want to have a good way to test my app locally using localstack.

**Comment by gfaraj** [comment]
I was able to get this working for SQS by manually editing the resources created by the ack-sqs-controller-sqs-chart helm chart. It would be great if these could be exposed as configuration values on the charts. 

I had to modify the args like this:

```
        - args:
          - --aws-region
          - $(AWS_REGION)
          - --aws-endpoint-url
          - $(AWS_ENDPOINT_URL)
          - --log-level
          - $(ACK_LOG_LEVEL)
          - --resource-tags
          - $(ACK_RESOURCE_TAGS)
          - --watch-namespace
          - $(ACK_WATCH_NAMESPACE)
          - --deletion-policy
          - $(DELETION_POLICY)
          - --reconcile-default-resync-seconds
          - $(RECONCILE_DEFAULT_RESYNC_SECONDS)
          - --reconcile-default-max-concurrent-syncs
          - $(RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS)
          - --feature-gates
          - $(FEATURE_GATES)
  +       - --aws-identity-endpoint-url
  +       - $(AWS_ENDPOINT_URL)
  +       - --allow-unsafe-aws-endpoint-urls
  +       - "true"
```


and update the environment variables like this:

```
          env:
          - name: ACK_SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_ENDPOINT_URL
            value: http://host.minikube.internal:4566
          - name: ACK_WATCH_NAMESPACE
          - name: DELETION_POLICY
            value: delete
          - name: LEADER_ELECTION_NAMESPACE
          - name: ACK_LOG_LEVEL
            value: info
          - name: ACK_RESOURCE_TAGS
            value: services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%,services.k8s.aws/namespace=%K8S_NAMESPACE%
          - name: RECONCILE_DEFAULT_RESYNC_SECONDS
            value: "36000"
          - name: RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS
            value: "1"
          - name: FEATURE_GATES
            value: ReadOnlyResources=false,ResourceAdoption=false,ServiceLevelCARM=false,TeamLevelCARM=false
  +       - name: AWS_ACCESS_KEY_ID
  +         value: "MyAccessKey"
  +       - name: AWS_SECRET_ACCESS_KEY
  +         value: "MySecretKey"
  +       - name: AWS_IGNORE_CONFIGURED_ENDPOINT_URLS
  +         value: "true"
```

Crossplane supports this via their ProviderConfig CRD, like this:

```
  spec:
    s3_use_path_style: true
    skip_metadata_api_check: true
    skip_requesting_account_id: true
    skip_credentials_validation: true
    endpoint:
      url:
        type: "Static"
        static: "http://host.minikube.internal:4566/"
      services: [iam, s3, sqs, sts]
      hostnameImmutable: true
      source: "Custom"
    credentials:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: aws-secret
        key: my-aws-secret
```
