### ISSUE TITLE
Operation Renames Config does not consume `output_fields` override

### ISSUE THREAD

**Issue by brycahta** [aws-controllers-k8s/community#1023]
**Describe the bug**
* The `output_fields` of an operation rename override does **not** work because it never gets consumed/used anywhere in [code](https://github.com/search?q=org%3Aaws-controllers-k8s+output_fields&type=code)

**Steps to reproduce**
* Add the following block to ec2-controller _generator.yaml_:

```
resources:
  SecurityGroup:
    renames:
      operations:
        CreateSecurityGroup:
          input_fields:
            GroupName: SecurityGroupName
          output_fields:
            GroupId: SecurityGroupId
```

**Expected outcome**
* I expect both fields to be renamed; however, upon inspecting the resource **only** the `input_fields` override takes effect:

```
CRD: &{sdkAPI:0xc000ddb9e0 cfg:0xc0005f0b40 Names:{ModelOriginal: Original:SecurityGroup Camel:SecurityGroup
 CamelLower:securityGroup Lower:securitygroup Snake:security_group} Kind:SecurityGroup Plural:SecurityGroups Ops:
{Create:0xc001594a80 ReadOne:<nil> ReadMany:0xc0015c1c00 Update:<nil> Delete:0xc0015a4e00 GetAttributes:<nil> 
SetAttributes:<nil>} additionalPrinterColumns:[] SpecFields:map[Description:0xc0017c5b00 
SecurityGroupName:0xc0017c5bc0 --> YES!

TagSpecifications:0xc0017c5ec0 VpcId:0xc0017c5c80] 
StatusFields:map[GroupId:0xc0018e8000 Tags:0xc0018e8240] Fields:map[Description:0xc0017c5b00 
GroupID:0xc0018e8000 --> NO!!

SecurityGroupName:0xc0017c5bc0 TagSpecifications:0xc0017c5ec0 
TagSpecifications..ResourceType:0xc001d503c0 TagSpecifications..Tags:0xc001d50600 
TagSpecifications..Tags..Key:0xc001d506c0 TagSpecifications..Tags..Value:0xc001d50780 Tags:0xc0018e8240 
Tags..Key:0xc001d50900 Tags..Value:0xc001d50840 VPCID:0xc0017c5c80] TypeImports:map[] ShortNames:[]}

```

**Environment**

* Kubernetes version 1.20
* Using EKS (yes/no), if so version?  No
* AWS service targeted (S3, RDS, etc.) EC2
