### ISSUE TITLE
GlobalCluster (with sourceDBClusterIdentifier specification) is not created properly if created at same time as DBCluster

### ISSUE THREAD

**Issue by rbranche** [aws-controllers-k8s/community#1027]
**Describe the bug**
`GlobalCluster` (with`sourceDBClusterIdentifier` specification) is not created properly if created at same time as `DBCluster`.

**Steps to reproduce**
1. Create combined yaml file with `GlobalCluster` and `DBCluster`

`cluster.yaml`
```
---
apiVersion: v1
kind: Secret
metadata:
  name: branche-test-rds-master-password
data:
  password: "ZGVhZGJlYWZkZWFkYmVhZmRlYWRiZWFm"

---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: GlobalCluster
metadata:
  name: branche-test
spec:
  globalClusterIdentifier: branche-test-preview-na1
  sourceDBClusterIdentifier: arn:aws:rds:us-east-1:<account>:cluster:us-east-1-branche-test

---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: branche-test
spec:
  engine: aurora-mysql
  databaseName: database_name
  dbClusterIdentifier: us-east-1-branche-test
  masterUsername: root
  masterUserPassword:
    namespace: preview
    name: branche-test-rds-master-password
    key: password
```

2. Apply changes to k8s
```
kubectl apply -f cluster.yaml
```

**Expected outcome**
`GlobalCluster` is created properly.

**Actual outcome**
`GlobalCluster` fails to create because the `DBCluster` takes a while to create in AWS and `DBClusterNotFoundFault` is a terminal condition.

---

We just need to remove `DBClusterNotFoundFault` as a terminal condition, just like how `DBInstance` works.

**Environment**

* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes
* AWS service targeted (S3, RDS, etc.) RDS
