### ISSUE TITLE
Table not found when creating GlobalTable resource

### ISSUE THREAD

**Issue by acunabit** [aws-controllers-k8s/community#1034]
**Describe the bug**

I am trying to create a global table and I am getting the following error:

```
ack-dynamodb-controller-5c4f76b845-xpdlk controller 2021-10-18T04:34:25.065Z	
ERROR	controller-runtime.controller	Reconciler error	{"controller": "globaltable", "request": "kube-system/ack", "error": "TableNotFoundException: Table not found: Table: 'acktable' not found in region: 'us-east-1'."}
```

Does the DynamoDb controller uses  DynamoDB Global Tables V2 (version 2019.11.21) or  DynamoDB Global Tables V1 (version 2017.11.29)?

If it's using V1, could you confirm if I need to create the table in both regions before creating the global table resource? Is V2 going to be supported in the near future?  Thank you very much.

**Steps to reproduce**

1. Create the resources 
```
cat  <<EOF | kubectl apply -f -
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: GlobalTable
metadata:
  namespace: kube-system
  name: ack
  labels:
    table: acktable
    version: v1.0.0
    helm.sh/chart: dynamodb-v1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dynamodb
    app.kubernetes.io/instance: ack
spec:
  globalTableName: acktable
  replicationGroup:
    - regionName: ap-southeast-2
    - regionName: us-east-1
---
# Source: dynamodb/templates/table.yaml
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  namespace: kube-system
  name: ack
  labels:
    table: acktable
    version: v1.0.0
    helm.sh/chart: dynamodb-v1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dynamodb
    app.kubernetes.io/instance: ack
spec:
  tableName: acktable
  billingMode: PAY_PER_REQUEST
  attributeDefinitions:
    - attributeName: ForumName
      attributeType: S
    - attributeName: Subject2
      attributeType: S
  keySchema:
    - attributeName: ForumName
      keyType: HASH
    - attributeName: Subject2
      keyType: RANGE
  streamSpecification:
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
EOF
```

**Expected outcome**
DynamoDb table created in both regions.

**Environment**

* Kubernetes version
1.19
* Using EKS (yes/no), if so version? 
yes : eks.6
* AWS service targeted (S3, RDS, etc.)
DynamoDB
