### ISSUE TITLE
DynamoDB controller cannot update any Table information if provisionedThroughput contains the original values

### ISSUE THREAD

**Issue by rbranche** [aws-controllers-k8s/community#1067]
**Describe the bug**
DynamoDB controller cannot update any Table information if `provisionedThroughput` contains the original values

**Steps to reproduce**
1. Create Table object
```
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: mytable
spec:
  tableName: mytable
  attributeDefinitions:
    - attributeName: field
      attributeType: S
  keySchema:
    - attributeName: field
      keyType: HASH
  provisionedThroughput:
    readCapacityUnits: 25
    writeCapacityUnits: 25
```
2. Try to add new Global Secondary Indexes to Table object
```
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: mytable
spec:
  tableName: mytable
  attributeDefinitions:
    - attributeName: field
      attributeType: S
  globalSecondaryIndexes:
    - indexName: field-index
      keySchema:
        - attributeName: field
          keyType: HASH
      projection:
        projectionType: KEYS_ONLY
      provisionedThroughput:
        readCapacityUnits: 25
        writeCapacityUnits: 25
  keySchema:
    - attributeName: field
      keyType: HASH
  provisionedThroughput:
    readCapacityUnits: 25
    writeCapacityUnits: 25
```
3. Controller fails to update Table with new GSI because `spec.provisionedThroughput` values didn't change

```
│     Message:            ValidationException: The provisioned throughput for the table will not change. The requested value equals the current value. Current ReadCapacityUnits provisioned for the tab │
│ le: 25. Requested ReadCapacityUnits: 25. Current WriteCapacityUnits provisioned for the table: 25. Requested WriteCapacityUnits: 25. Refer to the Amazon DynamoDB Developer Guide for current limits a │
│ nd how to request higher limits.                                                                                                                                                                       │
│                         status code: 400, request id: EFUN8JOS0NKP1NCISHIMPGHR07VV4KQNSO5AEMVJF66Q9ASUAAJG
```

**Expected outcome**
GSI for Table is created properly

**Environment**

* Kubernetes version: 1.21
* Using EKS (yes/no), if so version?  2
* AWS service targeted (S3, RDS, etc.) DynamoDB
