### ISSUE TITLE
SetResource does not handle String Pointers properly in `GenerateCrawler`

### ISSUE THREAD

**Issue by AaronME** [aws-controllers-k8s/community#1078]
**Describe the bug**
https://github.com/aws-controllers-k8s/code-generator/pull/232 introduced the ability to support different goTypes for input/output shapes with the same name. This code is not working for all fields on all resources.

The Crawler Resource on the Glue API exposes a field "Schedule."

In CreateCrawlerInput, "Schedule" is a [string](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#CreateCrawlerInput).
In GetCrawlerOutput's Crawler, "Schedule" is a type [Schedule](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#Schedule).

When running this through the latest code-generator, we get the following on the `GenerateCrawler` method:
```go
	if resp.Crawler.Schedule != nil {
		var f13 string
		cr.Spec.ForProvider.Schedule = f13
	} else {
		cr.Spec.ForProvider.Schedule = nil
	}
```

Because `Schedule` is a `*string` and not a `string`, this code does not compile.

**Steps to reproduce**
See generated code in https://github.com/crossplane/provider-aws/blob/2212c0919ed36e8d10f7829ef939d69322766b7e/pkg/controller/glue/crawler/zz_conversions.go#L92

**Expected outcome**
I would expect the generator to initialize this value as `nil` for a pointer:

```go
	if resp.Crawler.Schedule != nil {
		cr.Spec.ForProvider.Schedule = resp.Crawler.Schedule
	} else {
		cr.Spec.ForProvider.Schedule = nil
	}
```

**Environment**

* Kubernetes version N/A
* Using EKS (yes/no), if so version?  N/A
* AWS service targeted (S3, RDS, etc.) glue

**Comment by vijtrip2** [comment]
Hi @AaronME , thanks for pointing this out.

This issue of different go types for same named field was recently fixed. Please take a look at this [fix](https://github.com/aws-controllers-k8s/code-generator/commit/30510fcc39c8de2c65ad65c385c52c8153924e8d)

You'll need to update generator.yaml to provide code-generator the instructions on how to handle this field. See the above mentioned fix's commit message for reference.

**Comment by AaronME** [comment]
@vijtrip2 Thank you for the fast reply.

I had already tried running generation with the following:
```yaml
resources:
  Crawler:
    fields:
      Schedule:
        set:
          - on: Create
            from: ScheduleExpression
          - on: Update
            from: ScheduleExpression
          - on: ReadOne
            from: ScheduleExpression
          - on: ReadMany
            from: ScheduleExpression
```

This did not change any generated code.

I have two theories about this:

1. This is a known issue with [nested fields](https://github.com/aws-controllers-k8s/community/issues/1065), since the Schedule field needs to be set from Schedule.ScheduleExpression. 
2. https://github.com/aws-controllers-k8s/code-generator/pull/232 does not affect setResourceReadMany (which is where [GenerateCrawler](https://github.com/crossplane/provider-aws/blob/2212c0919ed36e8d10f7829ef939d69322766b7e/pkg/controller/glue/crawler/zz_conversions.go#L40) is being generated).
