### ISSUE TITLE
DBParameterGroup doesn't have the requested parameter value

### ISSUE THREAD

**Issue by jamesseo-alation** [aws-controllers-k8s/community#1086]
**What is the URL of the document?**

**Which section(s) is the issue in?**

**What needs fixing?**

**Additional context**
I am currently trying to create the below DBParameterGroup. It can create james-rds-parametergroup-test, but when I check rds.logical_replication in AWS console, it doesn't have 1, but 0 (default value). Could you share exact example to create the parameter group w/ custom parameters?
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBParameterGroup
metadata:
  name: james-rds-parametergroup-test
spec:
  name: james-rds-parametergroup-test
  description: Test parameter group for ACK
  family: postgres13
  parameters:
    - parameterName: rds.logical_replication
      parameterValue: "1"
```
