### ISSUE TITLE
crossplane: Kinesis Stream Status Struct is empty

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#1113]
**Describe the bug**

Kinesis Stream Status struct is empty - think because CreateStreamOutput is empty:
https://github.com/crossplane/provider-aws/pull/857

check:
https://github.com/crossplane/provider-aws/pull/857/files#diff-7b8e02c9bf79e827467652ee7f8c5a713396532f93d57ecd83162129248c447bR47

think `StreamDescription` needs to be part of  Status struct:

https://github.com/crossplane/provider-aws/pull/857/files#diff-3a3ab58f037334b3784e5b2e237f6db4551dcbf3fbc4dfe2617ad4982da6c3b8R120-R140

check in aws cli:
```
aws kinesis describe-stream --stream-name kinesis-stream --region us-east-1
{
    "StreamDescription": {
        "Shards": [
            {
                "ShardId": "shardId-000000000000",
                "HashKeyRange": {
                    "StartingHashKey": "0",
                    "EndingHashKey": "85070591730234615865843651857942052863"
                },
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49625430044987770121081518938564482091269801865790881794"
                }
            },
            {
                "ShardId": "shardId-000000000001",
                "HashKeyRange": {
                    "StartingHashKey": "85070591730234615865843651857942052864",
                    "EndingHashKey": "170141183460469231731687303715884105727"
                },
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49625430045010070866280049561706017809542450227296862226"
                }
            },
            {
                "ShardId": "shardId-000000000002",
                "HashKeyRange": {
                    "StartingHashKey": "170141183460469231731687303715884105728",
                    "EndingHashKey": "255211775190703847597530955573826158591"
                },
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49625430045032371611478580184847553527815098588802842658"
                }
            },
            {
                "ShardId": "shardId-000000000003",
                "HashKeyRange": {
                    "StartingHashKey": "255211775190703847597530955573826158592",
                    "EndingHashKey": "340282366920938463463374607431768211455"
                },
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49625430045054672356677110807989089246087746950308823090"
                }
            }
        ],
        "StreamARN": "arn:aws:kinesis:us-east-1:255932642927:stream/kinesis-stream",
        "StreamName": "kinesis-stream",
        "StreamStatus": "ACTIVE",
        "RetentionPeriodHours": 48,
        "EnhancedMonitoring": [
            {
                "ShardLevelMetrics": [
                    "IncomingBytes",
                    "OutgoingBytes"
                ]
            }
        ],
        "EncryptionType": "KMS",
        "KeyId": "arn:aws:kms:us-east-1:255932642927:key/c3b672bd-5f9a-4b31-87e6-ffcabfd27b53",
        "StreamCreationTimestamp": "2022-01-02T12:52:38+01:00"
    }
}
```

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by RedbackThomson** [comment]
Yes, [`CreateStreamOutput`](https://docs.aws.amazon.com/sdk-for-go/api/service/kinesis/#CreateStreamOutput) does not export any fields. I wouldn't say this is a bug in the code-generator, as we would expect it to not associate any status fields in this scenario. You would have to unpack each of the fields from the describe call into status fields in the generator, kind of like we do for the [SageMaker generator](https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/generator.yaml#L80-L87).

**Comment by haarchri** [comment]
Thanks for comment

Something like this ?

 
 ​  ```
  ​fields​: 
 ​      ​EndpointStatus​: 
 ​        ​is_read_only​: ​true 
 ​        ​print​: 
 ​          ​name​: ​STATUS 
 ​        ​from​: 
 ​          ​operation​: ​DescribeEndpoint 
 ​          ​path​: ​EndpointStatus
```

**Comment by RedbackThomson** [comment]
More specifically, as an example for a Kinesis stream:
```
  ​fields​: 
​      StreamStatus: 
​        ​is_read_only​: ​true 
​        ​from​: 
​          ​operation​: DescribeStream 
​          ​path​: StreamDescription.StreamStatus
```

**Comment by haarchri** [comment]
Okay i need to check if crossplane pipeline can handle this

**Comment by haarchri** [comment]
thanks it is working with:

```
resources:
  Stream:
    fields: 
      StreamStatus: 
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.StreamStatus
      StreamARN:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.StreamARN
      Shards:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.Shards
      RetentionPeriodHours:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.RetentionPeriodHours
      KeyId:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.KeyId
      HasMoreShards:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.HasMoreShards
      EnhancedMonitoring:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.EnhancedMonitoring
      EncryptionType:
        is_read_only: true 
        from: 
          operation: DescribeStream 
          path: StreamDescription.EncryptionType
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
```

and reflects in:

```
type StreamObservation struct {
	// The server-side encryption type used on the stream. This parameter can be
	// one of the following values:
	//
	//    * NONE: Do not encrypt the records in the stream.
	//
	//    * KMS: Use server-side encryption on the records in the stream using a
	//    customer-managed AWS KMS key.
	EncryptionType *string `json:"encryptionType,omitempty"`
	// Represents the current enhanced monitoring settings of the stream.
	EnhancedMonitoring []*EnhancedMetrics `json:"enhancedMonitoring,omitempty"`
	// If set to true, more shards in the stream are available to describe.
	HasMoreShards *bool `json:"hasMoreShards,omitempty"`
	// The GUID for the customer-managed AWS KMS key to use for encryption. This
	// value can be a globally unique identifier, a fully specified ARN to either
	// an alias or a key, or an alias name prefixed by "alias/".You can also use
	// a master key owned by Kinesis Data Streams by specifying the alias aws/kinesis.
	//
	//    * Key ARN example: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
	//
	//    * Alias ARN example: arn:aws:kms:us-east-1:123456789012:alias/MyAliasName
	//
	//    * Globally unique key ID example: 12345678-1234-1234-1234-123456789012
	//
	//    * Alias name example: alias/MyAliasName
	//
	//    * Master key owned by Kinesis Data Streams: alias/aws/kinesis
	KeyID *string `json:"keyID,omitempty"`
	// The current retention period, in hours. Minimum value of 24. Maximum value
	// of 168.
	RetentionPeriodHours *int64 `json:"retentionPeriodHours,omitempty"`
	// The shards that comprise the stream.
	Shards []*Shard `json:"shards,omitempty"`
	// The Amazon Resource Name (ARN) for the stream being described.
	StreamARN *string `json:"streamARN,omitempty"`
	// The current status of the stream being described. The stream status is one
	// of the following states:
	//
	//    * CREATING - The stream is being created. Kinesis Data Streams immediately
	//    returns and sets StreamStatus to CREATING.
	//
	//    * DELETING - The stream is being deleted. The specified stream is in the
	//    DELETING state until Kinesis Data Streams completes the deletion.
	//
	//    * ACTIVE - The stream exists and is ready for read and write operations
	//    or deletion. You should perform read and write operations only on an ACTIVE
	//    stream.
	//
	//    * UPDATING - Shards in the stream are being merged or split. Read and
	//    write operations continue to work while the stream is in the UPDATING
	//    state.
	StreamStatus *string `json:"streamStatus,omitempty"`
}
```
