### ISSUE TITLE
When lambda type `docker image` causes `code sign` error when registering manifest.

### ISSUE THREAD

**Issue by miseyu** [aws-controllers-k8s/community#1117]
**Describe the bug**
When lambda Type `docker image` causes `code sign` error when registering manifest.

```
ERROR   controller-runtime.controller   Reconciler error        {"controller": "function", "request": "***", "error": "InvalidParameterValueException: Code signing is not supported for functions created with container images.\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"a4e16c66-459f-493c-8736-0a139d1fbaad\"\n  },\n  Message_: \"Code signing is not supported for functions created with container images.\",\n  Type: \"User\"\n}"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
^CGot error: signal: interrupt
```

**Steps to reproduce**
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: ***
  annotations:
    services.k8s.aws/region: us-west-2
spec:
  name: ***
  packageType: Image
  code:
    imageURI: ***
  environment:
    variables:
      ***: ***
  role: ***
  timeout: 60
  description:  ***
  vpcConfig:
    securityGroupIDs:
      -  ***
    subnetIDs:
      -  ***
      -  ***
      -  ***
```

**Expected outcome**

**Environment**
us-west-2

* Kubernetes version 1.21
* Using EKS (yes/no), if so version?  yes eks.4
* AWS service targeted (S3, RDS, etc.) lambda
