### ISSUE TITLE
Hexchars in endpoint names for `rds` blocks use in GitOps workflow

### ISSUE THREAD

**Issue by doctorpangloss** [aws-controllers-k8s/community#1132]
**Describe the bug**
When creating a `DBCluster` instance, endpoints appear in status of the form:

```
CLUSTERNAME.cluster-HEXCHARS.REGION.rds.amazonaws.com
```

`hexchars` are the name given by AWS employees by this deterministic but not-known-ahead-of-time string appearning in the endpoint. See https://stackoverflow.com/a/35000722/1757994

Because hexchars are not known at the time the cluster is created, although it is constant, end users of any AWS RDS operation cannot create a manifest of any form that does not involve

 - polling for the value of these hexchars
 - some other dependency step

**Steps to reproduce**

Create a `DBCluster` resource. Observe the endpoints cannot be calculated from any input value on it.

**Expected outcome**
You should be able to declare something of the form

```
kind: DBCluster
spec:
  wellKnownClusterEndpoint: my-db-cluster
...
---
kind: Deployment
spec:
  containers:
   env:
    PGHOST:  my-db-cluster
```
**Environment**
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? : Yes, 1.21
* AWS service targeted (S3, RDS, etc.): RDS
