### ISSUE TITLE
[rds] RDS DBInstance created successfully but ack-rds-controller shows errors.

### ISSUE THREAD

**Issue by aws-patrickc** [aws-controllers-k8s/community#1147]
**Describe the bug**
RDS DBInstance created successfully, however the *ack-rds-controller* logs shows the error **InvalidVPCNetworkStateFault: The specified DB instance is already in the target DB subnet group.

Using CloudTrail I could see that the **ModifyDBInstance** API call shows the *dBSubnetGroupName* getting passed a parameter. This shouldn't occur as the same parameter was passed on **CreateDBInstance** API call.

**Steps to reproduce**
Apply the following manifest:
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: test-dbsubnetgroup
spec:
  description: Create DB SubnetGroup for Test VPC
  name: test-dbsubnetgroup
  subnetIDs:
    - subnet-aaaaaaaaaaaaaaaaa
    - subnet-bbbbbbbbbbbbbbbbb 
  tags:
    - key: VPCID
      value: vpc-xxxxxxxxxxxxxxxx
    - key: Region
      value: us-east-1
    - key: Environment
      value: SandBox
    - key: Name
      value: test-dbsubnetgroup
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSecurityGroup
metadata:
  name: test-mysql-db-sg
spec:
  description: Security Group For MySQL Database
  name: test-mysql-db-sg
  tags:
    - key: VPCID
      value: vpc-xxxxxxxxxxxxxxxx
    - key: Region
      value: us-east-1
    - key: Environment
      value: SandBox
    - key: Name
      value: test-mysql-db-sg
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysqldbcreds
data:
  password: YWxhdGlvbjEyMw==
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: test-mysql-db
spec:
  allocatedStorage: 50
  dbInstanceClass: db.t2.small
  dbInstanceIdentifier: test-mysql-db
  dbSubnetGroupName: test-dbsubnetgroup
  engine: mariadb
  engineVersion: "10.5.13"
  masterUserPassword:
    key: password
    name: mysqldbcreds
    namespace: default
  masterUsername: admin
  multiAZ: false
  publiclyAccessible: false
  storageEncrypted: true
  storageType: gp2
  tags:
    - key: VPCID
      value: vpc-xxxxxxxxxxxxxxxx
    - key: Region
      value: us-east-1
    - key: Environment
      value: SandBox
    - key: Name
      value: test-mysql-db
  vpcSecurityGroupIDs:
    - sg-xxxxxxxxxxxxxxxx

```

Monitor the ack-rds-controller logs for the error, using:

`
kubectl logs ack-rds-controller-rds-chart-xxxx-xxxxx  -n ack-system -f
`

RDS instance will be created successfully, look out for error like below:

```
1.6432833992493517e+09	ERROR	controller.dbinstance	Reconciler error	{"reconciler group": "rds.services.k8s.aws", "reconciler kind": "DBInstance", "name": "test-mysql-db", "namespace": "default", "error": "InvalidVPCNetworkStateFault: The specified DB instance is already in the target DB subnet group.\n\tstatus code: 400, request id: xxx-xxxx-xxxx-xxx"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

**Expected outcome**
Expecting RDS DBInstance to be created successfully without any errors

**Environment**

* Kubernetes version: 1.21
* Using EKS (yes/no), if so version?  Version 1.21, platform: eks.3
* AWS service targeted (S3, RDS, etc.): RDS
