### ISSUE TITLE
RDS: can't change tags after database creation

### ISSUE THREAD

**Issue by ddmedvedev** [aws-controllers-k8s/community#1155]
**Describe the bug**
Can't change tags after database creation.

**Steps to reproduce**
1. Run `kubectl logs your_pod_rds_chart_name -f`
2. Create somewhere file `db.yaml` with such contents
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysqldbcreds
data:
  password: some_password
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: rds-ack-db-test
  namespace: your_namespace
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: rds-ack-db-test
  engine: mysql
  engineVersion: 8.0.23
  masterUsername: admin
  masterUserPassword:
    key: password
    name: mysqldbcreds
  multiAZ: false
  port: 3306
  publiclyAccessible: false
  storageType: gp2
  tags:
    - key: Name
      value: rds-ack-db-test
    - key: CreatedBy
      value: RDS ACK
```

3. Run `kubectl apply -f db.yaml`
4. Verify that database have been created and there are some output from rds-chart pod.
5. Change tags or remove them
6. Run `kubectl apply -f db.yaml`
7. Verify that nothing changed and there is no new output from rds-chart pod.

**Expected outcome**
Tags have been modified and there is some new output from rds-chart pod.

**Environment**

* Kubernetes version 1.21
* Using EKS (yes/no), if so version? eks.4
* AWS service targeted (S3, RDS, etc.) RDS
