### ISSUE TITLE
RDS: dbSubnetGroupName not working

### ISSUE THREAD

**Issue by ddmedvedev** [aws-controllers-k8s/community#1157]
**Describe the bug**
After setting value for `dbSubnetGroupName` controller constantly shows `InvalidVPCNetworkStateFault` error and can't modify db instance.

**Steps to reproduce**
1. Create VPC, some subnets and DB subnet group
2. Run `kubectl logs your_pod_rds_chart_name -f`
3. Create somewhere file `db.yaml` with such contents
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysqldbcreds
data:
  password: some_password
---

apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: rds-ack-db-test
  namespace: some_namespace
spec:
  allocatedStorage: 20
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 7
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: rds-ack-db-test
  dbName: testdatabase
  dbSubnetGroupName: sng-d-rds-app
  engine: mysql
  engineVersion: 8.0.11
  masterUsername: admin
  masterUserPassword:
    key: password
    name: mysqldbcreds
#    namespace: default
  multiAZ: false
  port: 3306
  preferredBackupWindow: 05:30-06:30
  publiclyAccessible: false
  storageType: gp2
  tags:
    - key: Name
      value: rds-ack-db-test
    - key: CreatedBy
      value: RDS ACK
    - key: JiraID
      value: PLAT-13
```

4. Run `kubectl apply -f db.yaml`
5. Verify that database have been created in your specific DB subnet group and in custom VPC
6. Look at output from rds-chart pod, there will be repeatable error 
```
1.643808567784069e+09	ERROR	controller.dbinstance	Reconciler error	{"reconciler group": "rds.services.k8s.aws", "reconciler kind": "DBInstance", "name": "rds-ack-db-test", "namespace": "some_namespace", "error": "InvalidVPCNetworkStateFault: The specified DB instance is already in the target DB subnet group.\n\tstatus code: 400, request id: cebe1ec6-8026-4f8d-b8fc-efe7e37b90ec"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```
7. Change something, for example `preferredBackupWindow`
8. Run `kubectl apply -f db.yaml`
9. Look at output from rds-chart pod. Verify that despite `desired resource state has changed` message, nothing will actually change because of repeatable `InvalidVPCNetworkStateFault` error. Repeat steps 7-8 to make sure the db instance is out of control.

Conclusion:
There is no correct way to put database in non-default VPC.

**Expected outcome**
No errors when `dbSubnetGroupName` set, database in correct db subnet group and still under control.

**Environment**

* Kubernetes version 1.21
* Using EKS (yes/no), if so version? eks.4
* AWS service targeted (S3, RDS, etc.) RDS
