### ISSUE TITLE
Add a feature like writing a secret with the RDS connection string details.

### ISSUE THREAD

**Issue by PrasadTelasula** [aws-controllers-k8s/community#1162]
In crossplane we have a great feature to create the secret after RDS Instance created with all the required parameter os a connection string.

```yaml
writeConnectionSecretToRef:
      name: sample-db-con-string
      namespace: default
```
