### ISSUE TITLE
Add yaml anchors as default in the manifest schema like crossplane

### ISSUE THREAD

**Issue by PrasadTelasula** [aws-controllers-k8s/community#1163]
Requesting a feature request to include yaml anchors by default to call the resources using refs like in crossplane.

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: seu-cop-octopus3-pgsql-sg
spec:
  forProvider:
    region: eu-west-1
    vpcId: vpc-xcxcxcxcxcxc
    groupName: abcdefgh
    description: "RDS communication to Application Pods"
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: seu-cop-octopus3-pgsql
spec:
  forProvider:
    allocatedStorage: 25
    vpcSecurityGroupIDRefs:
      - name:  abcdefgh
```
