### ISSUE TITLE
EKS Controller - Cluster Creation InvalidParameterException

### ISSUE THREAD

**Issue by mcbarzi** [aws-controllers-k8s/community#1175]
**Describe the bug**
When creating a cluster resource, I'm getting eventhough keyARN is provided in the spec file
`InvalidParameterException: KeyArn is required `

**Steps to reproduce**

1. Installed eks-contoller v.0.0.6
2. Created the ff cluster ack resource
```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: sandbox
  namespace: sandbox
spec:
  encryptionConfig:
    - provider: 
       keyARN: "arn:aws:kms:{omitted}"
    - resources: 
      - "secrets"     
  kubernetesNetworkConfig: 
    serviceIPv4CIDR: "{omitted}"
  logging: 
    clusterLogging:
    - enabled: true
      types:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
  name: sandbox-
  resourcesVPCConfig: 
    endpointPrivateAccess: true
    endpointPublicAccess: false
    publicAccessCIDRs: []
    securityGroupIDs:
    - {omitted}
    subnetIDs:
    - subnet-{omitted}
  roleARN: {omitted}
  tags: {
    "Name": "sandbox"
  }
  version: "1.20"
```
**Expected outcome**
A concise description of what you expected to happen.
Expected EKS cluster will be created but got the ff error:

```yaml
Status:
  Ack Resource Metadata:
    Owner Account ID:  {omitted}
  Conditions:
    Message:  InvalidParameterException: KeyArn is required
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "{omitted}"
  },
  Message_: "KeyArn is required"
}
    Status:                True
    Type:                  ACK.Terminal
    Last Transition Time:  2022-02-11T02:50:43Z
    Status:                True
    Type:                  ACK.ResourceSynced
Events:                    <none>
```
**Environment** 
sandbox

* Kubernetes version
* 1.20
* Using EKS (yes/no), if so version?  EKS 
* AWS service targeted (S3, RDS, etc.) EKS
