### ISSUE TITLE
Resource references don't support nested field paths

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1212]
**Describe the bug**
When trying to add a reference on a nested field path, the code generator simply ignores the field.

**Steps to reproduce**
From the EKS controller:
```yaml
  Cluster:
    fields:
      ResourcesVpcConfig.SecurityGroupIds:
        references:
          service_name: ec2
          resource: SecurityGroup
          path: Status.ID
```

**Expected outcome**
The `ResourceVpcConfig` type should now contain a `SecurityGroupsRef` field with a slice of `SecurityGroup` references, as it would if it were a root spec field.
