### ISSUE TITLE
Resource references don't support ARNs

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1213]
**Describe the bug**
ACK stores ARNs in the `Status.ACKResourceMetadata.ARN` field. `ARN` is an `AWSResourceName` type, which is an alias of `string`, but Go code does not implicitly cast between these types:
```go
ko.Spec.RoleARN = obj.Status.ACKResourceMetadata.ARN
```

This leads to a compilation error:
```
cannot use obj.Status.ACKResourceMetadata.ARN (variable of type *"github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1".AWSResourceName) as *string value in assignment
```

**Steps to reproduce**
From the EKS controller:
```yaml
  Cluster:
    fields:
      RoleArn:
        references:
          service_name: iam
          resource: Role
          path: Status.ACKResourceMetadata.ARN
```

**Expected outcome**
The code-generator should cast the value appropriately. `Status.ACKResourceMetadata.ARN` is a `*AWSResourceName`, so the appropriate code would be:
```go
podExecutionRoleARN = string(*obj.Status.ACKResourceMetadata.ARN)
ko.Spec.PodExecutionRoleARN = &podExecutionRoleARN
```
