### ISSUE TITLE
Resource references check for nil in an unsafe way

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1214]
**Describe the bug**
`references.go` contains a nil check to ensure a property exists on the referenced object before it is injected into the field. This looks like the following:
```go
if obj.Status.SubnetID == nil {
	return ackerr.ResourceReferenceMissingTargetFieldFor(
		"Subnet",
		namespace, *arr.Name,
		"Status.SubnetID")
}
```

While this works for parent-level fields on `Spec` and `Status`, it incorrectly checks for nil on nested fields. For instance:
```go
if obj.Status.ACKResourceMetadata.ARN == nil {
	return ackerr.ResourceReferenceMissingTargetFieldFor(
		"Role",
		namespace, *arr.Name,
		"Status.ACKResourceMetadata.ARN")
}
```

This code may panic if `ACKResourceMetadata` is a `nil` struct. The behaviour is the same for any other nested field on `Spec` or `Status`.

**Steps to reproduce**
In the EKS controller:
```yaml
  Cluster:
    fields:
      RoleArn:
        references:
          service_name: iam
          resource: Role
          path: Status.ACKResourceMetadata.ARN
```

**Expected outcome**
The nil checking code should include an additional check for all nested paths that parent the final field.
```go
if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
	return ackerr.ResourceReferenceMissingTargetFieldFor(
		"Role",
		namespace, *arr.Name,
		"Status.ACKResourceMetadata.ARN")
}
```
