### ISSUE TITLE
Support association of `RouteTable` to `Subnet` in ec2-controller

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1219]
**Is your feature request related to a problem?**
The EC2 controller currently supports creating a `Subnet` and a `RouteTable` resource, but does not support a way to associate the two. Since a `SubnetRouteTableAssociation` does not have a unique identifier, it does not warrant its own resource. It would be more appropriate to place a list of associated `RouteTable` as a field in the spec of `Subnet`.

**Describe the solution you'd like**
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  name: subnet-1
spec:
  routeTableIDs:
  - rt-12345
  - rt-67890
```

with a corresponding resource reference:
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  name: subnet-2
spec:
  routeTableRefs:
  - from:
      name: my-route-table-1
  - from:
      name: my-route-table-2
```
