### ISSUE TITLE
All newly release controllers fail to start on OpenShift

### ISSUE THREAD

**Issue by acornett21** [aws-controllers-k8s/community#1238]
**Describe the bug**
All new controllers with runtime of `v0.18.0` fail to start. This appears to be caused by a change in the `deployment.yaml.tpl` in the code generator, in this [PR](https://github.com/aws-controllers-k8s/code-generator/commit/0b5dc38297ec74d54da4dd326a3988dc3de68b78)

**Steps to reproduce**
1. Install any operator that was released as part of `v0.18.0` runtime in an OpenShift cluster
2. See that the controller manager pod will `CrashLoopBackOff`

**Logs**
Controller pod logs
```
oc logs ack-rds-controller-d959dc69-6phtd
1.6481558349385543e+09	ERROR	setup	Unable to create controller manager	{"aws.service": "rds", "error": "unable to start service controller as AWS region is missing. Please pass --aws-region flag or set AWS_REGION environment variable"}
main.main
	/github.com/aws-controllers-k8s/rds-controller/cmd/controller/main.go:67
runtime.main
	/opt/bitnami/go/src/runtime/proc.go:255
```

Config map configuration
```
 oc get configmap ack-user-config -oyaml
apiVersion: v1
data:
  ACK_ENABLE_DEVELOPMENT_LOGGING: "true"
  ACK_LOG_LEVEL: debug
  ACK_RESOURCE_TAGS: hellofromocp
  ACK_WATCH_NAMESPACE: ""
  AWS_REGION: us-west-2
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-12T19:22:11Z"
  name: ack-user-config
  namespace: ack-system
  resourceVersion: "3819318"
  uid: befa04f3-fc0c-4f96-bd70-a1872059a708
  ```
  
  Snippet from the deployment
  ```
   spec:
      containers:
      - args:
        - --aws-region
        - $(AWS_REGION)
        - --aws-endpoint-url
        - $(AWS_ENDPOINT_URL)
        - --enable-development-logging
        - $(ACK_ENABLE_DEVELOPMENT_LOGGING)
        - --log-level
        - $(ACK_LOG_LEVEL)
        - --resource-tags
        - $(ACK_RESOURCE_TAGS)
        - --watch-namespace
        - $(ACK_WATCH_NAMESPACE)
        command:
        - ./bin/controller
        env:
        - name: ACK_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AWS_REGION
        - name: AWS_ENDPOINT_URL
        - name: ACK_WATCH_NAMESPACE
        - name: ACK_ENABLE_DEVELOPMENT_LOGGING
          value: "false"
        - name: ACK_LOG_LEVEL
          value: info
        - name: ACK_RESOURCE_TAGS
          value: services.k8s.aws/managed=true,services.k8s.aws/created=%UTCNOW%,services.k8s.aws/namespace=%KUBERNETES_NAMESPACE%
        - name: OPERATOR_CONDITION_NAME
          value: ack-rds-controller.v0.0.20
        envFrom:
        - configMapRef:
            name: ack-user-config
            optional: false
        - secretRef:
            name: ack-user-secrets
            optional: false
```

**Observations**
This means that `env` is taking precedence over `envFrom`. This also means that `kustomize` is _not_ propagating the default values that are in the `tpl` file properly (or possibly operator-sdk). We would need to look at the `tmp` directories in real time to see which is dropping the default `""` empty values. 

**Expected outcome**
I would expect that the controller manager pod would be able to start.

**Environment**
Production

* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? no, OpenShift
* AWS service targeted (S3, RDS, etc.) - All
