### ISSUE TITLE
ReplicationGroup adoption bug

### ISSUE THREAD

**Issue by oleg-yudovich** [aws-controllers-k8s/community#1250]
**Describe the bug**
When trying to adapt the existing replication group by applying:

```YAML
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  namespace: ***
  name: ***
spec:
  aws:
    nameOrID: ***
  kubernetes:
    group: elasticache.services.k8s.aws
    kind: ReplicationGroup
    metadata:
      name: ***

```
`ack-elasticache-controller` reconcile is failing:

"INFO	adoption.adopted-reconciler	starting adoption reconciliation	{"target_group": "elasticache.services.k8s.aws", "target_kind": "ReplicationGroup", "namespace": "***", "name": "***", "generation": 1} 1.6491549222661903e+09	ERROR	controller.adoptedresource	Reconciler error	{"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "name": "***", "namespace": "***", "error": "ReplicationGroup.elasticache.services.k8s.aws \"***\" is invalid: spec.replicationGroupDescription: Required value"}"

P.S.
I can see exactly the same error when applying replication group YAML without a description.

**Expected outcome**
`ack-elasticache-controller` should handle the adoption of the existing replication group correctly

**Environment**

* Kubernetes version
* Using EKS: no
* AWS service targeted: Elasticache
* Chart version: v0.0.9
