### ISSUE TITLE
AdoptedResource for DBParameterGroup Failing

### ISSUE THREAD

**Issue by urton** [aws-controllers-k8s/community#1264]
**Describe the bug**
Trying to adopt an existing RDS parameter group via AdoptedResource results in a reconciler error specifying a key that is not supported in the AdoptedResource CR.

**Steps to reproduce**
Apply the yaml below
```
---
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: my-pg-group
  namespace: my-namespace
spec:
  aws:
    arn: arn:aws:rds:_region_:_accountid_:pg:my-pg-group
    nameOrID: my-pg-group
  kubernetes:
    group: rds.services.k8s.aws
    kind: DBParameterGroup
```
Error
```
1.6503848514709425e+09	ERROR	controller.adoptedresource	Reconciler error	{"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "name": "my-pg-group", "namespace": "my-namespace", "error": "DBParameterGroup.rds.services.k8s.aws \"my-pg-group\" is invalid: spec.family: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

I tried adding spec.family in the yaml above but received the same error.

**Expected outcome**
The AdoptedResource should create a DBParamterGroup CR.

**Environment**
DEV

* Kubernetes version v1.22.5
* Using EKS (yes/no), if so version?  No, OpenShift 4.9.26
* AWS service targeted (S3, RDS, etc.) RDS
