### ISSUE TITLE
Add Additional Print Columns to DB Instance and DB Cluster CRDs

### ISSUE THREAD

**Issue by urton** [aws-controllers-k8s/community#1271]
@jaypipes here's what I've got so far working locally with the DBInstance CRD:
```
$ oc -n my-namespace get dbinstance
NAME             READY   STATUS      ENGINE      ENGINE-VER                           CLASS
my-db-instance   True    available   oracle-ee   19.0.0.0.ru-2022-01.rur-2022-01.r1   db.t3.medium
```
Here's the yaml insert for the v1alpha1 spec.version:
```
    additionalPrinterColumns:
    - description: The state of the custom resource
      name: READY
      #priority: 0
      jsonPath: .status.conditions[?(@.type=="ACK.ResourceSynced")].status
      type: string
    - description: The AWS status of the custom resource
      jsonPath: .status.dbInstanceStatus
      name: STATUS
      #priority: 0
      type: string
    - description: The AWS engine of the custom resource
      jsonPath: .spec.engine
      name: ENGINE
      #priority: 0
      type: string
    - description: The AWS engine version of the custom resource
      jsonPath: .spec.engineVersion
      name: ENGINE-VER
      #priority: 0
      type: string
    - description: The AWS instance class of the custom resource
      jsonPath: .spec.dbInstanceClass
      name: CLASS
      #priority: 0
      type: string
```
I'll need to get the ack generator working so I can test the syntax for the fields block and then I will pull. This look OK to you?
