### ISSUE TITLE
Support for ImportApi operation of APIGatewayV2

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#128]
**Is your feature request related to a problem?**
ImportApi is one of most used apigatewayv2 operation and it's support is currently missing because the name does not start with "create"

**Describe the solution you'd like**
- Support of ImportAPI in CRD generation and controller.
- Support of ReImport(Update) in CRD generation and Controller

**Comment by vijtrip2** [comment]
I have tried to implement this using following generator-config for apigatewayv2 

```
operations:
  ImportApi:
    resource_name: ImportedApi*
    operation_type: Create
  ReimportApi:
    resource_name: ImportedApi*
    operation_type: Update
```
* -> "ImportedApi" is not yet decided as final name of this resource.
But there is a weirdness with APIGatewayV2 operations.

ImportedApi* and Api share the ReadOne and Delete operation while Create and Update operations are not shared. IOW, GetApi and DeleteApi operation apply to both Api and ImportedApi resource.

@jaypipes I need your guidance on how to share an operation for two CRDs.
I have been thinking of introducing another abstraction in the generatorConfig for this case but I will wait for your expert opinion : )
