### ISSUE TITLE
Ability to specify additional printer columns in `ack-generate` config file

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1281]
**Is your feature request related to a problem?**
Currently, `ack-generate` can produce go code with kubebuilder markers allowing CRDs to have additional print columns. However, CRDs can only have one print column per field. Ideally, we would like to have an option to specify extra print columns with something similar to:

```yaml
    additionalPrinterColumns:
    - name: SYNCED
      jsonPath: .status.conditions[?(@.type=="ACK.ResourceSynced")].status
```

**Describe the solution you'd like**
Ability to have multiple print columns per field.
