### ISSUE TITLE
Provide example for AdoptedResource

### ISSUE THREAD

**Issue by jkatz** [aws-controllers-k8s/community#1303]
**What is the URL of the document?**

**Which section(s) is the issue in?**

Likely "Tutorials"

**What needs fixing?**

There is no example for how to use [`AdoptedResource`](https://aws-controllers-k8s.github.io/community/reference/common/v1alpha1/adoptedresource/) in the documentation, which may be affecting its adoption.

**Additional context**

Provide some examples with how it works with one or more services.

**Comment by jeesmon** [comment]
Design proposal has some good examples at https://github.com/aws-controllers-k8s/community/blob/main/docs/design/proposals/adoption/resource-adoption.md

But not sure if it matches with implementation. Adding it in the official documentation will definitely help the adopters.

**Comment by RedbackThomson** [comment]
@jeesmon I have more examples, if anyone needs them. Thankfully the implementation does actually match the proposal, except that the `apiVersion` of the resource is not service specific - that is, the `apiVersion` is `services.k8s.aws/v1alpha1`

Here's one example with an S3 bucket
```yaml
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-boring-bucket
spec:  
  aws:
    nameOrID: boring-old-normal-bucket
  kubernetes:
    group: s3.services.k8s.aws
    kind: Bucket
    metadata:
      name: my-adopted-bucket
```
