### ISSUE TITLE
EKS ACK - PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by amosaini** [aws-controllers-k8s/community#1320]
**Describe the bug**
The EKS ACK pods fails after deploying a nodegroup.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/95207359/172532242-ad3276f4-a405-4c9c-9a32-7acd9d496b6c.png">

**Steps to reproduce**
1. Install v0.1.1 of eks ack.
2. created iam Role using following iam policy.
```
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "eks:*",
                "iam:GetRole",
                "iam:PassRole",
                "iam:ListAttachedRolePolicies",
                "ec2:DescribeSubnets"
            ],
            "Resource": "*"
        }
    ]
}
```
4. Created Nodegroup using folowing.
```
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: xxxx
spec:
  amiType: "AL2_x86_64"
  capacityType: "ON_DEMAND"
  clusterName: "xxxxxxx"
  diskSize: 100
  instanceTypes:
  - "m5.4xlarge"
  - "m5n.4xlarge"
  - "m5d.4xlarge"
  - "m5dn.4xlarge"
  - "m5a.4xlarge"
  - "m4.4xlarge"
  labels: {node : "vcpu", type : "ON_DEMAND", project : "xxxx"}
  name: "sbx-cd-msr-nodegroup"
  nodeRole: "arn:aws:iam::xxxxxxx:role/xxxxx-role"
  scalingConfig: 
    desiredSize: 1
    maxSize: 6
    minSize: 1
  subnets:
  - "subnet-xxxxx"
  - "subnet-xxxxx"
  tags: { environment: sbx, project_name: xxxx }
  taints:
  - effect: "NO_SCHEDULE"
    key: "project"
    value: "xxxxx"
 ```
**Expected outcome**
The Pods should not have gone into failed state.

**Environment**

* Kubernetes version v0.21
* Using EKS (yes/no), if so version? yes v0.1.1
* AWS service targeted (S3, RDS, etc.) EKS
