### ISSUE TITLE
Updates to DBSubnetGroup resources don't take effect

### ISSUE THREAD

**Issue by teddyking** [aws-controllers-k8s/community#1324]
**Describe the bug**

Hi there, I've noticed a potential issue regarding updates to `.spec` and re-reconciliation of resources.
Specifically, I noticed this when trying to update the `.spec.subnetIDs` field for a `DBSunetResource`. 

**Steps to reproduce**

1. Use `kubectl` to create a `DBSubnetGroup`, for example:

```shell
cat <<EOF | kubectl apply -f-
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: sg-1
  namespace: ack-system
spec:
  name: sg-1
  description: sg-1 description
  subnetIDs:
  - subnet-foo
  - subnet-bar
EOF
```

2. Use `kubectl` to update the `DBSubnetGroup`, for example:

```shell
cat <<EOF | kubectl apply -f-
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: sg-1
  namespace: ack-system
spec:
  name: sg-1
  description: sg-1 description
  subnetIDs:
  - subnet-baz # updated
  - subnet-qux # updated
EOF
```

3. Expect the change to be reflected in `.status` of the resource, as well as in the AWS API/console.

```shell
kubectl get dbsubnetgroup -n ack-system sg-1 -o yaml

# output trimmed for brevity
spec:
  subnetIDs:
  - subnet-baz # updated as expected
  - subnet-qux # updated as expected
...
status:
  subnets:
  - subnetIdentifier: subnet-foo # expected subnet-baz
  - subnetIdentifier: subnet-bar # expected subnet-qux

# also check the resources in the AWS web console and see that they have not been updated there either
```

**Expected outcome**

I would expect that if I update a field in the `.spec` of a resource and then apply the updated resource, that the change would take effect and subsequently be reflected in `.status` as well as within the AWS API/console. However, I am not seeing this behaviour.

**Environment**

* Kubernetes version: v1.21.12
* Using EKS (yes/no), if so version?  Yes, v1.21.12
* AWS service targeted (S3, RDS, etc.) RDS
* RDS ACK controller version: v0.0.24

**Comment by brucegucode** [comment]
I tried with local setup and seems it's working as expected.  
@teddyking  If you describe that DBSubnetGroup object in k8s, does it have some message/exception of sync status? 

Previously I have 
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: "brucegu-test-subnet-1"
spec:
  name: "brucegu-test-subnet-1"
  description: "created by ack"
  subnetIDs:
  - subnet-3f23d662 (old subnet id )
  - subnet-c8c1ace3 (old subnet id )
 ```

describe call has 
```
  Conditions:
    Last Transition Time:  2022-06-14T17:31:41Z
    Message:               Resource synced successfully
    Reason:
    Status:                True
    Type:                  ACK.ResourceSynced
  Subnet Group Status:     Complete
  Subnets:
    Subnet Availability Zone:
      Name:             us-west-2c
    Subnet Identifier:  subnet-3f23d662 (old subnet id )
    Subnet Outpost:
    Subnet Status:  Active
    Subnet Availability Zone:
      Name:             us-west-2d
    Subnet Identifier:  subnet-c8c1ace3 (old subnet id )
    Subnet Outpost:
    Subnet Status:  Active

```

then i updated subnet id in this CRD
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: "brucegu-test-subnet-1"
spec:
  name: "brucegu-test-subnet-1"
  description: "created by ack"
  subnetIDs:
  - subnet-30756f49 (new subnet id )
  - subnet-a0b4b0eb (new subnet id )
```

after applying, the describe is returning:

```
  Conditions:
    Last Transition Time:  2022-06-14T17:34:57Z
    Message:               Resource synced successfully
    Reason:
    Status:                True
    Type:                  ACK.ResourceSynced
  Subnet Group Status:     Complete
  Subnets:
    Subnet Availability Zone:
      Name:             us-west-2a
    Subnet Identifier:  subnet-30756f49 (new subnet id )
    Subnet Outpost:
    Subnet Status:  Active
    Subnet Availability Zone:
      Name:             us-west-2b
    Subnet Identifier:  subnet-a0b4b0eb (new subnet id )
    Subnet Outpost:
    Subnet Status:  Active
```
