### ISSUE TITLE
serverlessV2ScalingConfiguration state not changing  

### ISSUE THREAD

**Issue by cdaveaws** [aws-controllers-k8s/community#1373]
**Describe the bug**
any changes to serverlessV2ScalingConfiguration is not applied to the cluster.

**Steps to reproduce**

```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster

metadata:
  name: tfc-db
  namespace: mydb

spec:
  backupRetentionPeriod: 1
  serverlessV2ScalingConfiguration:
    maxCapacity: 16
    minCapacity: 4
  dbClusterIdentifier: tfc-db
  dbSubnetGroupName: mydbsubetgroupack
  engine: aurora-postgresql
  engineVersion: "14.3"
  masterUsername: adminer
  masterUserPassword:
    namespace: mydb
    name: postgres-creds
    key: password
  vpcSecurityGroupIDs:
     - {ADD-SecuritygroupID}
```
 
**Expected outcome**
After changing max/min capacity for serverlessV2ScalingConfiguration, it is not reflected on the cluster on a console.

```
kubectl get  dbcluster -n "${APP_NAMESPACE}"  -o=jsonpath='{..spec.serverlessV2ScalingConfiguration}'
{"maxCapacity":8,"minCapacity":2}
```

logs:

**Environment**
```
aws eks   describe-cluster --name eksworkshop-eksctl --query 'cluster.version'
"1.19"
```
* Kubernetes version:
* Using EKS (yes/no), yes: 
* AWS service targeted : RDS
