### ISSUE TITLE
FieldExport does not export field in configmap 

### ISSUE THREAD

**Issue by x4d3** [aws-controllers-k8s/community#1375]
**Describe the bug**
Following [this tutorial](https://aws-controllers-k8s.github.io/community/docs/tutorials/rds-example/) we are trying to export the endpoint of a RDS database to a configmap in order to provide it to our pods as an env variable.

However the configmap does not contain the value after applying the configuration.

**Steps to reproduce**

- Apply this configuration
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: account-applications-api-db
  namespace: account-applications-api
spec:
  allocatedStorage: 20
  backupRetentionPeriod: 14
  dbInstanceClass: db.t3.medium
  dbInstanceIdentifier: account-applications-api
  dbName: account_applications_api
  dbSubnetGroupName: account-applications-api-db-subnets
  deletionProtection: true
  engine: postgres
  engineVersion: "13"
  masterUsername: account_applications_api
  # TODO: preferredBackupWindow?
  #       preferredMaintenanceWindow?
  masterUserPassword:
    name: db-secrets
    key: password
    namespace: account-applications-api
  multiAZ: true
  publiclyAccessible: false
  storageEncrypted: true
  vpcSecurityGroupIDs:
    - sg-0ccf9607832ded7fe
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-database-cm
  namespace: account-applications-api
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: export-database-url
  namespace: account-applications-api
spec:
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: account-applications-api-db
  to:
    kind: configmap
    name: postgres-database-cm
    namespace: account-applications-api
```
and Run
```
kubectl describe configmap/postgres-database-cm -n account-applications-api
```

worth noting that 
```
kubectl describe fieldexport/export-database-url -n account-applications-api
```
does not return any status nor events.

**Expected outcome**
It should display data with the `export-database-url` field.

**Environment**

* Kubernetes version
1.22
* Using EKS (yes/no), if so version? 
yes, eks.2
* AWS service targeted (S3, RDS, etc.)
RDS
