### ISSUE TITLE
Allow configuration of `SetManyOutputNotFoundErrReturn` per Operation

### ISSUE THREAD

**Issue by EdgeJ** [aws-controllers-k8s/community#1380]
**Is your feature request related to a problem?**
Now that the `setResourceReadMany` function has been set to pull double duty when passed a `Create` operation with a list element as the output (in https://github.com/aws-controllers-k8s/code-generator/pull/337) there can arise problems from the return value within the loop. Create and Describe operations can be used in different places in Go code (the templates for Crossplane generation specifically) that expect different return types (e.g. the number of returned objects).

**Describe the solution you'd like**
I think it would make sense and not be particularly difficult to implement adding an additional config to apply `SetManyOutputNotFoundErrReturn` options from the Operations configs.

I'm Imagining something like this:
```yaml
operations:
  CreateLoadBalancer:
    operation_type:
      - Create
    output_wrapper_field_path: LoadBalancers
    set_many_output_notfound_err_return: return nil, errors.New(errNotFound)
```

**Describe alternatives you've considered**
Other than setting the top level option to something no-op (e.g. setting to something like "_ = found"), I don't think there's really much of a workaround here.
