### ISSUE TITLE
DBSubnetGroup manifest created from AdoptedResource missing subnetIDs

### ISSUE THREAD

**Issue by cogren1** [aws-controllers-k8s/community#1389]
**Describe the bug**
One of our DBSubnetGroup manifests became detached from its AWS resource during a namespace migration. I created an AdoptedResource manifest to regenerate the manifest, but I received the following condition: 
```'DBSubnetGroup.rds.services.k8s.aws "default-subnet-group" is invalid: spec.subnetIDs: Required value'```
This suggests to me that the DBSubnetGroup manifest that the controller is generating is not including all the required fields.

Here is the full AdoptedResource manifest and status I used (with ARN redacted):
``` yaml
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: ar-default-subnet-group
  namespace: rds-operator-irsa
spec:
  aws:
    arn: REDACTED
    nameOrID: db-subnet-group
  kubernetes:
    group: rds.services.k8s.aws
    kind: DBSubnetGroup
    metadata:
      labels:
        app.kubernetes.io/instance: dev-rds-manifests
      name: default-subnet-group
      namespace: rds-operator-irsa
status:
  conditions:
  - message: 'DBSubnetGroup.rds.services.k8s.aws "default-subnet-group" is invalid:
      spec.subnetIDs: Required value'
    status: "False"
    type: ACK.Adopted
```

**Steps to reproduce**

0. Install RDS controller on a K8s cluster that can create RDS resources in an AWS account.
1. Create a DB Subnet Group in RDS.
2. Create an AdoptedResource manifest in the K8s cluster referencing the created DB Subnet Group.
3. Look at the conditions of the new AdoptedResource manifest.

**Expected outcome**
AdoptedResource reports a "True" Adopted status, and the DBSubnetGroup manifest appears in the cluster.

**Environment**
I started using v0.0.24 of the RDS controller before upgrading to v0.0.27 and then v0.0.28. All of them had this issue.

* Kubernetes version _1.21.8 via Rancher_
* Using EKS (yes/no), if so version? _No_
* AWS service targeted (S3, RDS, etc.) _RDS_
