### ISSUE TITLE
error validating data: ValidationError(Table.spec): unknown field "timeToLive" in aws.k8s.services.dynamodb.v1alpha1.Table.spec

### ISSUE THREAD

**Issue by karmingc** [aws-controllers-k8s/community#1397]
**Describe the bug**
Tried to declare a timeToLive field but receiving an unknown field error.

**Steps to reproduce**
```yaml
{{- $tableName :=  "tests" }}
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: {{ $tableName }}
spec:
  tableName: {{ $tableName }}
  attributeDefinitions:
    - attributeName: "id"
      attributeType: "N"
  keySchema:
    - attributeName: "id"
      keyType: "HASH"
  timeToLive:
    attributeName: "ttl"
    enabled: true
  billingMode: PAY_PER_REQUEST
```

**Expected outcome**
It should not error out given that it is an available field https://aws-controllers-k8s.github.io/community/reference/dynamodb/v1alpha1/table/

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 1.22.5
* AWS service targeted (S3, RDS, etc.): DynamoDB
