### ISSUE TITLE
S3 ACK - Unsupported Argument

### ISSUE THREAD

**Issue by stanenbaum-va** [aws-controllers-k8s/community#1407]
**Describe the bug**
After applying a bucket resource, the controller logs show the following error
```
2022-07-27T20:52:34.160Z        ERROR   controller.bucket       Reconciler error        {"reconciler group": "s3.services.k8s.aws", "reconciler kind": "Bucket", "name": "my-ack-s3-bucket", "namespace": "s3-test", "error": "UnsupportedArgument: The request contained an unsupported argument.\n\tstatus code: 400, request id: <redacted>, host id: <redacted>"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-07-27T20:52:34.164Z        DEBUG   exporter.field-export-reconciler        error did not need requeue      {"error": "the source resource is not synced yet"}
```
K8s bucket status:
```
Status:
  Ack Resource Metadata:
    Owner Account ID:  <redacted>
    Region:            us-gov-west-1
  Conditions:
    Message:               UnsupportedArgument: The request contained an unsupported argument.
                           status code: 400, request id: <redacted>, host id: <redacted>
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2022-07-28T00:35:13Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                UnsupportedArgument: The request contained an unsupported argument.
                           status code: 400, request id: <redacted>, host id: <redacted>
    Status:                Unknown
    Type:                  ACK.ResourceSynced
  Location:                http://<redacted>.s3-us-gov-west-1.amazonaws.com/
```
The bucket does get created, but deletion of the bucket, or any additional spec configurations that are added, do not actually get applied to the resource. To be noted, we are working on implementing S3 ACK in us-gov-west-1 via an AWS GovCloud account.
 
**Steps to reproduce**
1) Define following values in Helm values.yaml
```
aws:
  region: us-gov-west-1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: ack-s3-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws-us-gov:iam::<redacted>:role/project/project-ldx/<redacted>"

log:
  level: debug
  enable_development_logging: true
```
2) Helm install
```
export SERVICE=s3
export RELEASE_VERSION=$(curl -sL https://api.github.com/repos/aws-controllers-k8s/$SERVICE-controller/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
export ACK_SYSTEM_NAMESPACE=ack-system
helm upgrade --install -n $ACK_SYSTEM_NAMESPACE ack-$SERVICE-controller \
  oci://public.ecr.aws/aws-controllers-k8s/$SERVICE-chart --version="$RELEASE_VERSION" -f values.yaml
```
3) Apply bucket
```
cat <<EOF | kubectl apply -f -
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: test-bucket
spec:
  name: test-bucket
EOF
```
**Expected outcome**
An S3 bucket is created, no reconcile errors are shown in logs. Bucket can be updated, additional values can be specified in spec and applied correctly. 

Initial intuition is the potential gap of features available in commercial AWS versus GovCloud AWS. 

**Environment**

* Kubernetes version - 1.22
* Using EKS (yes/no), if so version?  Yes, 1.22
* AWS service targeted (S3, RDS, etc.) S3
