### ISSUE TITLE
RDS binding to wrong VPC by default

### ISSUE THREAD

**Issue by offbynull** [aws-controllers-k8s/community#1409]
**Describe the bug**
Our AWS account has two VPCs, one created for general use and another created by `eksctl` for the k8s cluster we're using. When the RDS manifest is applied, it binds to the wrong VPC.

**Steps to reproduce**

1. ensure you have a "default network" VPC setup already

2. stand up a basic EKS cluster using `eksctl` defaults, it should create a VPC for the new cluster.

3. `kubectl` apply the following

   ```yaml
   apiVersion: rds.services.k8s.aws/v1alpha1
   kind: DBInstance
   metadata:
     name: dh-api-service-db
   spec:
     allocatedStorage: 20
     dbInstanceClass: db.t4g.micro
     dbInstanceIdentifier: dh-api-service-db
     engine: postgres
     engineVersion: '14'
     masterUserPassword:
       key: password
       name: dh-api-service-db-password
       namespace: default
     masterUsername: postgres
   ```

4. note how the RDS instance gets set to the "default network" VPC instead of the VPC that the EKS cluster is on

**Expected outcome**

Cluster resources should be assigned by default to the VPC that the cluster is on. This is how it works for the EC2 instances spun up by a node group, so that's how it should be for RDS instances.

**Environment**

* Kubernetes version: 1.22
* Using EKS (yes/no), if so version: yes -- 1.21
* AWS service targeted: RDS
