### ISSUE TITLE
Expand FieldExport to support json `path` to target arbitrary fields of matching GNKV resources

### ISSUE THREAD

**Issue by tis-rpage** [aws-controllers-k8s/community#1417]
**Is your feature request related to a problem?**
Kustomize replacements/patches provide a means to modify specific attributes in a k8s resource via a json path. Field Exports enhanced with this capability could provide new functionality beyond targeting configMap/secrets.

For example, services of type `externalName` create a local DNS entry for connecting to services by a short name within the cluster.
FieldExport can be enhanced to update `spec.externalName` of a Service so that this DNS entry is dynamically updated to match newly created AWS resources.

**Describe the solution you'd like**
```yaml
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: postgres-rds
spec:
  from:
    resource:
      kind: DBInstance
      name: postgres
    path: ".status.endpoint.port"
  to:
    kind: Service
    name: postgres-rds
    path: "spec.externalName"
```

**Describe alternatives you've considered**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-init-rds-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-init-rds-endpoint
  template:
    metadata:
      labels:
        name: postgres-init-rds-endpoint
    spec:
      serviceAccountName: postgres
      containers:
        - name: postgres-init-rds-endpoint
          image: ansible:latest
          env:
            - name: DBINSTANCE
              value: postgres
            - name: SERVICE
              value: postgres-rds
          command:
            - /bin/sh
            - -c
            - |-
              get_rds_endpoint() { kubectl get "dbinstance/${DBINSTANCE}" -o json | yq -P e .status.endpoint.address - ; }
              get_service_endpoint() { kubectl get -o yaml "service/${SERVICE}" | yq e '.spec.externalName' - ; }
              set -x
              while sleep 7 ; do
                RDS_ENDPOINT="$(get_rds_endpoint)"
                SERVICE_ENDPOINT="$(get_service_endpoint)"
                case "${RDS_ENDPOINT}" in
                  null|"${SERVICE_ENDPOINT}") :;;
                  *) kubectl patch --type merge "service/${SERVICE}" -p "{ \"spec\": { \"externalName\": \"${RDS_ENDPOINT}\" } }";;
                esac
              done
```

**Comment by askulkarni2** [comment]
This would help with IRSA annotations for `ServiceAccount`.

```yaml
spec:  
  to:
    name: myserviceaccount
    kind: ServiceAccount
    key: metadata.annotations[eks.amazonaws.com/role-arn]
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: iam.services.k8s.aws
      kind: Role
      name: ack-irsa-role
```
