### ISSUE TITLE
EC2 SecurityGroup v0.18 fails when ingressRules are defined using `userIDGroupPairs` and `groupID`

### ISSUE THREAD

**Issue by apmclean** [aws-controllers-k8s/community#1443]
**Describe the bug**
Using release .18 of EC2 SecurityGroup where an IngressRule is defined to use an existing Security Group via `groupID` - the SecurityGroup creation is continuously retried even though it exists.  No IngressRules are present.

**Steps to reproduce**

1) Create a non-Default VPC, and note the VPC ID.  
2) Create a Security Group within the VPC created in step 1.  Note the Security Group ID.

Use the following definition with substitutions for `vpcID` and `groupID`:

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: security-group-with-ingress-sg
spec:
  name: security-group-with-ingress
  description: SecurityGroup with an Ingress Rule on Non Default VPC
  ingressRules:
    - fromPort: 5432
      toPort: 5432
      ipProtocol: tcp
      userIDGroupPairs:
        - groupID: sg-[existing-id]
          description: Source Security Group
  vpcID: vpc-[existing-id]
  tags:
    - key: Name
      value: security-group-with-ingress
```

Creation will fail with message:

```text
  Conditions:
    Message:               InvalidGroup.Duplicate: The security group 'security-group-with-ingress' already exists for VPC 'vpc-[...]'
                           status code: 400, request id: [...]
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2022-08-23T01:59:10Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                InvalidGroup.Duplicate: The security group 'security-group-with-ingress' already exists for VPC 'vpc-[...]'
                           status code: 400, request id: [...]
    Status:                Unknown
    Type:                  ACK.ResourceSynced
Events:                    <none>
```

The security group has been created by ACK (Confirmed via CloudTrail, and via Tags on resource), however the ingress rules are not present.  **NOTE** If `ipRanges` are used instead of `userIDGroupPairs` the groups and ingress rules will create successfully.

**Expected outcome**

The Security Group should be created permitting ingress from the noted Security Group ID.  Similar to `Example (Shared001)` in the [GoLang Documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.AuthorizeSecurityGroupIngress) for `AuthorizeSecurityGroupIngress`.

**Environment**

* Kubernetes version: v1.21
* Using EKS (yes/no), if so version?: Yes.  eks-5308cf7
* AWS service targeted (S3, RDS, etc.): EC2 SecurityGroup

**Comment by brycahta** [comment]
@apmclean I can't seem to reproduce the issue locally. I tried using **default vpc** for `vpcID` and **default security group** for `userIDGroupPairs.groupID` and saw the ingress rule created as expected. Per your instruction, I created a new vpc and security group and used those IDs, but again saw expected behavior. 

Let me check with some members of the team to see if they can repro

**Comment by apmclean** [comment]
The only other nuance is my default VPC is deleted. Don't think that will have any bearing though. I also upgraded from .17. Let me tear it all down and re-try from fresh.

**Comment by apmclean** [comment]
Apologies, my reproduction steps were incomplete.  When I encounter the issue I'm using `groupName` and not `groupID`.

Same steps as above, but instead use the `groupName` for the security group you created within that VPC.

ie:
```
  ingressRules:
    - fromPort: 5432
      toPort: 5432
      ipProtocol: tcp
      userIDGroupPairs:
        - groupName: [group-name-of-existing-security-group]
          description: Source Security Group
```
