### ISSUE TITLE
FieldExport unknown field "key" 

### ISSUE THREAD

**Issue by rgarrigue** [aws-controllers-k8s/community#1479]
**Describe the bug**

The documentation says one can specify to.key https://aws-controllers-k8s.github.io/community/reference/common/v1alpha1/fieldexport/#spec

Trying to use it, got the error

> error validating data: ValidationError(FieldExport.spec.to): unknown field "key" in aws.k8s.services.v1alpha1.FieldExport.spec.to

**Steps to reproduce**

Something like this (working on it atm so not sure it's functional)

```
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: "strapi-cms-database-instance"
spec:
  allocatedStorage: 10
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 14
  copyTagsToSnapshot: true
  # customIAMInstanceProfile: arn:
  dbInstanceClass: db.t4g.medium
  dbInstanceIdentifier: "gs-product-prod-strapi-cms"
  # dbSubnetGroupName:
  deletionProtection: true
  engine: aurora-postgresql
  engineVersion: "14"
  masterUsername: "strapicms"
  masterUserPassword:
    namespace: strapicms
    name: "strapi-cms-database-password"
    key: DATABASE_PASSWORD
  # maxAllocatedStorage: 100
  monitoringInterval: 0 # Enhanced monitoring disabled
  multiAZ: true
  # preferredBackupWindow: # Not applicable for Aurora
  preferredMaintenanceWindow: Sat:02:00-Sat:04:00 # ddd:hh24:mi-ddd:hh24:mi
  publiclyAccessible: false 
  tags:
    CreatedBy: ACK
    Department: product
    Environment: prod
    Service: strapi-cms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-cms-database-host
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: strapi-cms-database-host
spec:
  from:
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: strapi-cms-database-instance
    path: ".status.endpoint.address"
  to:
    kind: configmap
    name: strapi-cms-database-host
    key: DATABASE_HOST
```

**Expected outcome**

I expect to have my strapi-cms-database-host CM created with the endpoint address in the DATABASE_HOST key, so I can attach it to my deployment hence Strapi CMS will have its connection informations

**Environment**

EKS 1.23, ACK RDS v0.0.30 deployed via Helm
