### ISSUE TITLE
RDS DBCluster endpoints stuck at creating

### ISSUE THREAD

**Issue by rgarrigue** [aws-controllers-k8s/community#1484]
**Describe the bug**

My Aurora PostgreSQL endpoints have been stuck creating forever. I created a "test" one in the UI, which quickly became available. 

![image](https://user-images.githubusercontent.com/1872031/190587693-72eb94f5-8e54-4759-bff8-70e9803d7564.png)

I see no config option that could be relevant to be fixed

**Steps to reproduce**

Here are my quickly cleaned manifest

```yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cms-database-password
  namespace: backend
spec:
  encryptedData:
    DATABASE_PASSWORD: AgA71/Gap8yOCtX9CPKnNawuBEpH8d7CuTAsJY3lddPcvX9aHEX4lzUJoISJKi5PIGx+YSX0KLq+R1YCC26WQOSK5noN5LWPdpfKbXPguWMkcapN8dcW1/Ky9ejqGGIXcfXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXtR3GW0qD24aYrXOQEBKeGCZQb2zMOCt6r4xHMQmsBYnMpdt6pBfyDbNyaEtbgo7kORKjOsDPSocbH9eIifex0Z0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cms-database-password
      namespace: backend
# AWS RDS database via ACK
# https://aws-controllers-k8s.github.io/community/reference/rds/v1alpha1/dbcluster/
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: company-cms
  namespace: backend
spec:
  name: company-cms
  description: Managed by ACK
  # aws ec2 describe-subnets | jq -r '"- " + (.Subnets[] | select(.Tags|select(length > 0)|.[].Value|test(".*private.*")) | .SubnetId)'
  subnetIDs:
    - subnet-XXXXXXXXXX
    - subnet-XXXXXXXXXX
    - subnet-XXXXXXXXXX
  tags:
    - key: CreatedBy
      value: ACK
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: "cms-database-cluster"
spec:
  # allocatedStorage: 10 # Not applicable to Aurora
  # autoMinorVersionUpgrade: true # can only be specified for a Multi-AZ DB cluster. You can use CreateDBInstance to set AutoMinorVersionUpgrade for a DB instance in a different type of DB cluster.
  # availabilityZones: # aurora deal with that itself
  # backtrackWindow # undocumented ...
  backupRetentionPeriod: 14
  copyTagsToSnapshot: true
  databaseName: cms
  dbClusterIdentifier: "company-cms"
  # dbClusterInstanceClass: db.t4g.medium
  dbSubnetGroupName: company-cms
  deletionProtection: true
  # domain: # undocumented
  enableCloudwatchLogsExports:
    - postgresql
  # enablePerformanceInsights: false # isn't supported for DB engine aurora-postgresql at the cluster level
  # aws rds describe-db-engine-versions | jq '.DBEngineVersions[]|select(.Engine=="aurora-postgresql")|select(.EngineVersion|test("^14.*"))'
  engine: aurora-postgresql
  engineMode: provisioned
  engineVersion: "14.3"
  # globalClusterIdentifier: # only if attaching to a global database https://aws-controllers-k8s.github.io/community/reference/rds/v1alpha1/globalcluster/
  # iops: # Not applicable to Aurora
  masterUsername: "cms"
  masterUserPassword:
    namespace: backend
    name: "cms-database-password"
    key: DATABASE_PASSWORD
  # monitoringInterval: 0 # Enhanced monitoring disabled # Enhanced Monitoring interval isn't supported for DB engine aurora-postgresql at the cluster level.
  preferredBackupWindow: 00:00-01:59 # hh24:mi-hh24:mi
  preferredMaintenanceWindow: sat:02:00-sat:04:00 # ddd:hh24:mi-ddd:hh24:mi
  # publiclyAccessible: false # isn't supported for DB engine aurora-postgresql
  # scalingConfiguration: # "For DB clusters in serverless DB engine mode ..." hence no ?
  #   autoPause: boolean
  #   maxCapacity: integer
  #   minCapacity: integer
  #   secondsBeforeTimeout: integer
  #   secondsUntilAutoPause: integer
  #   timeoutAction: string
  # serverlessV2ScalingConfiguration:
  #   maxCapacity: number
  #   minCapacity: number
  storageEncrypted: true
  tags:
    - key: CreatedBy
      value: ACK
  # vpcSecurityGroupIDs:
# The database is protected from accidental deletion like ArgoCD going crazy
# But then AWS ACK controller says it's already created and it doesn't own it
# hence this resource to bring it back under control
---
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: "cms-database-cluster-adopt-existing"
  namespace: backend
spec:
  aws:
    nameOrID: company-cms
  kubernetes:
    group: rds.services.k8s.aws
    kind: DBCluster
    metadata:
      name: cms-database-cluster
      namespace: backend
# Export AWS RDS database via ACK info in a CM
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-database-host
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: cms-database-host
spec:
  from:
    resource:
      group: rds.services.k8s.aws
      kind: DBCluster
      name: cms-database-cluster
    path: ".status.endpoint"
  to:
    kind: secret
    name: cms-database-host
    key: DATABASE_HOST

```

**Expected outcome**

Endpoints created

**Environment**

EKS 1.23, ACK RDS 1.1.0 via helm
