### ISSUE TITLE
[emr-containers] Add retries, state for JobRun

### ISSUE THREAD

**Issue by Swalloow** [aws-controllers-k8s/community#1489]
**Is your feature request related to a problem?**
1. **JobRun state**
    JobRun is used to process batch or streaming jobs.
    State is required to manage the JobRun lifecycle.
    Ref: [SparkOperator - SparkApplicationStatus](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkoperator.k8s.io/v1beta2.SparkApplicationStatus
)

2. **JobRun retries**
    JobRun needed to restart through the controller when the task fails.
    For example, SparkOperator has `failureRetries`, `retryInterval` options.
    Ref: [SparkOperator - SparkAppicationsSpec](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkapplicationspec)

**Describe the solution you'd like**
```yaml
# For JobRun retries
apiVersion: emrcontainers.services.k8s.aws/v1alpha1
kind: JobRun
metadata:
    ...
spec:
    ...
    failureRetries: 2
    retryInterval: 5

# For JobRun state
$ kubectl get jobrun
NAME    STATE
test    running
```
state from SDK: `PENDING`, `SUBMITTED`, `RUNNING`, `FAILED`, `CANCELLED`, `CANCEL_PENDING`, `COMPLETED`

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
