### ISSUE TITLE
Sagemaker PipelineExecution

### ISSUE THREAD

**Issue by ryansteakley** [aws-controllers-k8s/community#1494]
**Is your feature request related to a problem?**
Pipeline Execution Operations

* [StartPipelineExecution](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_StartPipelineExecution.html)  - > Create (Creates a pipelineExeuctionArn unique identifier)
* `StopPipelineExecution` → Delete
* `UpdatePipelineExecution` → Update
* `DescribePipelineExecution`  → Describe
* `RetryPipelineExecution` →(Reuse existing pipelineExecutionArn to rerun may not support this) Does not appear to create a new PipelineExecutionArn instead re-using the existing one. Can be called when PipelineExecution has failed
 * Other methods are outside the scope of Control Plane operations and will not be implemented i.e 

    * `SendPipelineExecutionStepSuccess`

The api describes pipeline execution create as a “start” command. However we can equate this to a create operation since this generates a PipelinExecutionArn similar to any other Sagemaker Job i.e (Trainingjob,ProcessingJob, etc...)
The workflow would simply be to Start the Pipeline and have it execute, until user decides to delete it.

```
 StartPipelineExecution:
    operation_type: Create
    resource_name: PipelineExecution
 StopPipelineExecution:
    operation_type: Delete
    resource_name: PipelineExecution
```

Does the community have any issues with such a resource existing in ACK framework?

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
