### ISSUE TITLE
sseAlgorithm isn't Parsing as Expected

### ISSUE THREAD

**Issue by cogren1** [aws-controllers-k8s/community#1505]
**Describe the bug**
I have the following spec for adding encryption to a bucket:
``` yaml
spec:
  encryption:
    rules:
    - applyServerSideEncryptionByDefault:
        kmsMasterKeyID: arn:aws:kms:us-east-1:REDACTED:key/REDACTED
        sseAlgorithm: SSE-KMS
      bucketKeyEnabled: true
  name: REDACTED
```
It produces the following condition:
``` yaml
  - message: "Error syncing property 'Encryption': MalformedXML: The XML you provided
      was not well-formed or did not validate against our published schema\n\tstatus
      code: 400, request id: SB2HCAYHGG5DPC2N, host id: 82oCnV89OAnxXu3t/jiKzwAOt/74UMUSaj2iuVYS6/fVwVjTTebqu5tLEWWfNXs6CoPumdCm7iQ="
    status: "True"
    type: ACK.Recoverable
```
This error only appears when `sseAlgorithm` is present, which it has to be if `applyServerSideEncryptionByDefault` is present. I tried every permutation I could think of as a value. I made sure that the key itself is able to be used by the right IAM roles, although the error still appears even when `kmsMasterKeyID` is not specified.

**Steps to reproduce**
1. Install the S3 controller on a cluster
2. Apply an S3 bucket manifest with an `encryption` section like the one above.
3. Look at the status conditions for a failure.

**Expected outcome**
Encryption is applied to the bucket with the given key in KMS.

**Environment**

* Kubernetes version v1.21.13
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.) S3
