### ISSUE TITLE
S3 Controller and Minio

### ISSUE THREAD

**Issue by yaroslavkasatikov** [aws-controllers-k8s/community#1506]
Hi team,

Would it be possible to configure s3-controller and MiniO (or other s3 solution)?

I tried to change endpoint URL but got error:

2022-10-15T18:55:56.183Z        ERROR   setup   Unable to create controller manager     {"aws.service": "s3", "error": "unable to determine account ID: unable to get caller identity: InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: f755d445-9b92-48c5-bad7-1137a8cd0cb0"}

I started it with the following variables:

```
containers:
      - args:
        - --aws-endpoint-url
        - $(AWS_ENDPOINT_URL)
        - --enable-development-logging
        - $(ACK_ENABLE_DEVELOPMENT_LOGGING)
        - --log-level
        - $(ACK_LOG_LEVEL)
        - --resource-tags
        - $(ACK_RESOURCE_TAGS)
        - --watch-namespace
        - $(ACK_WATCH_NAMESPACE)
        command:
        - ./bin/controller
        env:
        - name: ACK_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AWS_ENDPOINT_URL
          value: http://172.30.16.228
        - name: ACK_WATCH_NAMESPACE
        - name: ACK_ENABLE_DEVELOPMENT_LOGGING
          value: "false"
        - name: ACK_LOG_LEVEL
          value: info
        - name: ACK_RESOURCE_TAGS
          value: services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%,services.k8s.aws/namespace=%K8S_NAMESPACE%
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /var/run/secrets/aws/credentials-file
        - name: AWS_PROFILE
          value: default
```

My credential file contains default minio root access id and key:

```
[default]
aws_access_key_id = minio
aws_secret_access_key = minio123
```

I tried different combination. but faced to the same mistake.

I 'm using this:
public.ecr.aws/aws-controllers-k8s/s3-controller:v0.1.4

Thanks!
