### ISSUE TITLE
Support for Key Rotation in KMS ACK Controller

### ISSUE THREAD

**Issue by sudohikumar** [aws-controllers-k8s/community#1508]
**Is your feature request related to a problem?**
As there is already a support of Key Rotation in [cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#aws-resource-kms-key-properties) and [terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_key), there should also be a feature parity in ACK Controller. 
Hence, I propose to add the same to the ACK Controller.

**Describe the solution you'd like**
We would like to contribute as following (initial proposition) 
In `generator.yaml`, we add a custom field `EnableKeyRotation` as follows. 
```
Key:
    fields:
      Origin:
        is_immutable: true
      MultiRegion:
        is_immutable: true
      ....
      ....
      EnableKeyRotation:
        type: bool
```

Why custom field, you ask?
From my basic understanding, if we reference operation from `EnableKeyRotation`, it brings the correct docs on the property, but, the type generated is of `*string`. 
Imo, it should be of type `*bool` to avoid basic type interpolation at the later stage.

After this, we intend to write custom hook which can be attached to `customUpdate` function in `hooks.go` file.
