### ISSUE TITLE
EC2: support SecurityGroup IDs in ingress and egress rules

### ISSUE THREAD

**Issue by chakch** [aws-controllers-k8s/community#1511]
**Is your feature request related to a problem?**
when I create a security group, I want to specify a rule based on other security group

**Describe the solution you'd like**
in the securitygroup spec, we can add in the rule:
ingressRules/EgressRules:
- fromPort: integer
  ipProtocol: string
  ipRanges:
  - cidrIP: string
    description: string
  ipv6Ranges:
  - cidrIPv6: string
    description: string
  securityGroupIDs: 
  - string
  securityGroupRefs: 
  - from: 
      name: string

**Comment by A-Hilaly** [comment]
Hi @chakch , QQs:

1- is this something supported by CF/CDK or the CLI?
2- Could you provide complete manifests for the current experience and the one you'd like to have? because i can't find securityGroupIDs in the [IPrange struct](https://github.com/aws-controllers-k8s/ec2-controller/blob/main/apis/v1alpha1/types.go#L1512-L1521)

**Comment by chakch** [comment]
hi @A-Hilaly I not in the IP range section (sorry for that), it's on the ingress section 
fromPort: integer
securityGroupIDs:
    - string
securityGroupRefs:
    - from:
      name: string
In the cloudformation, https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html we can provide https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html#cfn-ec2-security-group-rule-sourcesecuritygroupid

**Comment by A-Hilaly** [comment]
Hi @chakch thank you for the clarification! Looks like to support this we need to add a custom field and make extra [`{Authorize/Revoke}SecurityGroupIngress` API Calls](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html). 
/cc @LikithaVemulapalli

**Comment by LikithaVemulapalli** [comment]
Hi @chakch, as per the [{Authorize/Revoke}SecurityGroupEgress API calls](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupEgress.html) `sourceSecurityGroupName` and `sourceSecurityGroupOwnerId` are not supported. We can add the SecurityGroup in the Egress rules using IPPermissions only. As per the existing functionality, we can add SecurtiyGroup in the Ingress/Egress Rules using `userIDGroupPairs`. Below is the template on how to add SecurityGroupId in the Ingress/Egress rules:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: tutorial-security-group
spec:
  description: "ack security group"
  name: tutorial-sg
  vpcID: <VPC-ID>
  ingressRules:
    -ipProtocol: <IP_PROTOCOL>
      fromPort: <FROM_PORT>
      toPort: <TO_PORT>
      userIDGroupPairs:
      - groupID: <SecurityGroup-ID>
```
Based on the `SecurityGroup` we need to add the [userIDGroupPairs Properties](https://github.com/aws-controllers-k8s/ec2-controller/blob/9a27c82fc0424f98228a6ad43321f214e66ee083/config/crd/bases/ec2.services.k8s.aws_securitygroups.yaml#L100)
