### ISSUE TITLE
Failed to sync the DynamoDB resource

### ISSUE THREAD

**Issue by dexye-apt** [aws-controllers-k8s/community#1522]
**Describe the bug**
The DynamoDB table was created successfully, however the DynamoDB controller failed to sync the table. 

Based on my tests, it only happens to `PAY_PER_REQUEST` table, the `PROVISIONED` table was synced successfully.

**Steps to reproduce**
```
cat  <<EOF | kubectl apply -f -
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: debug-sync-1
  namespace: pe
spec:
  tableName: debug-sync-1
  billingMode: PAY_PER_REQUEST
  attributeDefinitions:
    - attributeName: ForumName
      attributeType: S
    - attributeName: LastPostDateTime
      attributeType: S
    - attributeName: Subject
      attributeType: S
  keySchema:
    - attributeName: ForumName
      keyType: HASH
    - attributeName: Subject
      keyType: RANGE
  localSecondaryIndexes:
    - indexName: LastPostIndex
      keySchema:
        - attributeName: ForumName
          keyType: HASH
        - attributeName: LastPostDateTime
          keyType: RANGE
      projection:
        projectionType: KEYS_ONLY
  streamSpecification:
    streamEnabled: true
    streamViewType: "NEW_AND_OLD_IMAGES"
EOF
```
The table was created successfully. The status is:
```
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:dynamodb:ap-southeast-2:xxxx:table/debug-sync-1
    Owner Account ID:  xxx
    Region:            ap-southeast-2
  Billing Mode Summary:
    Billing Mode:  PAY_PER_REQUEST
  Conditions:
    Last Transition Time:  2022-10-28T05:05:58Z
    Message:               Resource not synced
    Reason:
    Status:                False
    Type:                  ACK.ResourceSynced
```
From the controller logs:
```
2022-10-28T05:06:58.411Z	DEBUG	ackrt	requeue needed after error	{"account": "xxx", "role": "", "region": "ap-southeast-2", "kind": "Table", "namespace": "pe", "name": "debug-sync-1", "is_adopted": false, "generation": 2, "error": "temporary out of sync, reconcile after some time", "after": "30s"}
2022-10-28T05:06:58.420Z	DEBUG	exporter.field-export-reconciler	error did not need requeue	{"error": "the source resource is not synced yet"}
```

**Expected outcome**
Resource synced successfully

**Environment**

* Kubernetes version 1.20
* Using EKS (yes/no), if so version?  YES eks.9
* AWS service targeted (S3, RDS, etc.) DynamoDB
