### ISSUE TITLE
[S3] The status field of the lifecycle rules is required

### ISSUE THREAD

**Issue by aljoshare** [aws-controllers-k8s/community#1523]
**Describe the bug**
The documentation says that the status field of the lifecycle rules is optional but in fact it is required. It needs to be set to Enabled or Disabled.

Documentation: https://aws-controllers-k8s.github.io/community/reference/s3/v1alpha1/bucket/
![image](https://user-images.githubusercontent.com/12294054/198621959-e3f1bc46-0b5b-4726-868b-e247c5a4355f.png)

Error message:
```
- message: |
      Error syncing property 'Lifecycle': InvalidParameter: 1 validation error(s) found.
      - missing required field, PutBucketLifecycleConfigurationInput.LifecycleConfiguration.Rules[2].Status.
    status: "True"
    type: ACK.Recoverable
```

**Steps to reproduce**

Deploy an S3 with a lifecycle configuration and omit the status field, e.g.:

```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: test
spec:
  name: test
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true
    ignorePublicACLs: true
    restrictPublicBuckets: true
  versioning:
    status: Enabled
  encryption:
    rules:
      - bucketKeyEnabled: false
        applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
  lifecycle:
    rules:
      - id: "Non-Current Version Transition to STANDARD_IA"
        status: "Enabled"
        filter:
          prefix: "/topics"
        noncurrentVersionTransitions:
          - noncurrentDays: 30
            storageClass: "STANDARD_IA"
      - id: "Current Version Transition to STANDARD_IA"
        filter:
          prefix: "/topics"
        status: "Enabled"
        transitions:
          - days: 30
            storageClass: "STANDARD_IA"
      - id: "This one is broken"
        filter:
          prefix: "/topics"
        transitions:
          - days: 30
            storageClass: "STANDARD_IA"

```

**Expected outcome**
Either the documentation should say that its required or the operator should fill the field with a default value so that truly optional.

**Environment**

* Kubernetes version: 1.23.10
* Using EKS (yes/no), if so version? Yes 1.23.10
* AWS service targeted (S3, RDS, etc.) S3
