### ISSUE TITLE
AmazonMQ broker not sync due to permission problem ec2:ModifyNetworkInterfaceAttribute

### ISSUE THREAD

**Issue by csantanapr** [aws-controllers-k8s/community#1526]
**Describe the bug**
Trying to create Amazon MQ for new EKS workshop using ACK, and resources doesn't sync correctly.

Trying to create broker on the same VPC as the EKS cluster, using private subnet, and creating security group.

**Steps to reproduce**

Create Security Group
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: "mq-eks-workshop"
  namespace: default
spec:
  description: SecurityGroup mq-eks-workshop
  name: mq-eks-workshop
  vpcID: vpc-07488ff69b233a7c0
  ingressRules:
  - ipProtocol: tcp
    ipRanges:
    - cidrIP: "0.0.0.0/0"
    fromPort: 61616
    toPort: 61619
  - ipProtocol: tcp
    ipRanges:
    - cidrIP: "0.0.0.0/0"
    fromPort: 8162
    toPort: 8162
```

Create Broker
```yaml
apiVersion: mq.services.k8s.aws/v1alpha1
kind: Broker
metadata:
  name: "mq-eks-workshop"
spec:
  name: "mq-eks-workshop"
  deploymentMode: SINGLE_INSTANCE
  engineType: ActiveMQ
  engineVersion: "5.15.8"
  hostInstanceType: "mq.t3.micro"
  publiclyAccessible: false
  autoMinorVersionUpgrade: false
  users:
    - password:
        namespace: default
        name: "mq-eks-workshop"
        key: password
      groups: []
      consoleAccess: true
      username: admin
  subnetIDs:
  - subnet-091dc19cd206af16f
  securityGroups:
  - sg-020681d6cedde4a28
```

**Expected outcome**
Resource to be sync

**Environment**
Installed MQ controller, and setup iam with suggested iam role permissions https://github.com/aws-controllers-k8s/mq-controller/blob/main/config/iam/recommended-policy-arn
```
arn:aws:iam::aws:policy/AmazonMQFullAccess
```

* Kubernetes version
EKS 1.23
* AWS service targeted (S3, RDS, etc.)
MQ

Resources status
```yaml
    conditions:
    - message: |-
        ForbiddenException: Access Denied: You aren't authorized to perform this operation. You must have permission to call ec2:ModifyNetworkInterfaceAttribute.
        {
          RespMetadata: {
            StatusCode: 403,
            RequestID: "83aa8347-c132-429d-aa2e-35a12d086ff1"
          },
          Message_: "Access Denied: You aren't authorized to perform this operation. You must have permission to call ec2:ModifyNetworkInterfaceAttribute."
        }
      status: "True"
      type: ACK.Recoverable
    - lastTransitionTime: "2022-11-01T15:37:22Z"
      message: Unable to determine if desired resource state matches latest observed
        state
      reason: |-
        ForbiddenException: Access Denied: You aren't authorized to perform this operation. You must have permission to call ec2:ModifyNetworkInterfaceAttribute.
        {
          RespMetadata: {
            StatusCode: 403,
            RequestID: "83aa8347-c132-429d-aa2e-35a12d086ff1"
          },
          Message_: "Access Denied: You aren't authorized to perform this operation. You must have permission to call ec2:ModifyNetworkInterfaceAttribute."
        }
      status: Unknown
      type: ACK.ResourceSynced
```
