### ISSUE TITLE
Creating SNS FifoTopic

### ISSUE THREAD

**Issue by TheRockyOng** [aws-controllers-k8s/community#1528]
**Is your feature request related to a problem?**
Currently SNS FifoTopic doesn't seem to be supported in the sns-controller 

**Describe the solution you'd like**
Ability to create FifoTopic using sns-controller

**Comment by A-Hilaly** [comment]
Currently we are not able to regenerate the sns-controller and any new resource because of the issues mentioned in https://github.com/aws-controllers-k8s/community/issues/1292

**Comment by jaypipes** [comment]
@TheRockyOng working on adding this functionality now...

**Comment by TheRockyOng** [comment]
thanks @jaypipes !! really appreciate you

**Comment by jaypipes** [comment]
/reopen

(still working on this! :) )

**Comment by daviniagarcia** [comment]
Hi @jaypipes and @TheRockyOng,
yesterday I was trying to create a SNS Fifo Topic with ACK and I could create it:
```
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Topic
metadata:
  name: logs-events.fifo
  namespace: development
spec:  
  displayName: logs events SNS topic
  name: logs-events.fifo
  deliveryPolicy: "3"
```
It's true that there is not a fifo attribute in [TopicSpec struct](https://github.com/aws-controllers-k8s/sns-controller/blob/31a2f4709c6cb6c3109971b00b1b34f4cc81326f/apis/v1alpha1/topic.go#L27) but in line [46](https://github.com/aws-controllers-k8s/sns-controller/blob/31a2f4709c6cb6c3109971b00b1b34f4cc81326f/apis/v1alpha1/topic.go#L46) it says "For a FIFO (first-in-first-out) topic, the name must end with the .fifo suffix." 

IMHO it would be better to add the attribute.

Nevertheless, there are other attributes that I need and I can't set up like contentBasedDeduplication and [subscription](https://github.com/aws-controllers-k8s/community/issues/1491)
