### ISSUE TITLE
Ability to set an SDK input from a specific CR field

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1532]
**Is your feature request related to a problem?**
Currently it is not possible to instruct the code-generator to set a set the input of an sdk operation from a specific field. How ever is it possible to set a CR field from a specific sdk operation output. Using something like:
```yaml
resources:
  User:
    fields:
      X:
        set:
        - method: Update
          from: Path
```

**Describe the solution you'd like**
The same way i would like to be able to set an sdk input using a specific field:
```yaml
resources:
  User:
    fields:
      X:
        set:
        - method: Update
          to: NewPath
```

This will be helpful in fixing a bug within the iam-controller where the generated code that sets `UpdateUserInput` struct, doesn't include `NewPath`, because the field name is `Path` in the User CR.
