### ISSUE TITLE
Can't deploy updated deployment package for Lambda with ACK

### ISSUE THREAD

**Issue by timam** [aws-controllers-k8s/community#1550]
**Describe the bug**
I have created a lambda fuction with ACK. I am using a file from s3 to deploy lambda. 
Now, I have a new deployment package and want ack to deploy the new package. Unfortunately, ack is giving me following error. 
```
This resource already exists but is not managed by ACK. To bring the resource under ACK management, you should explicitly adopt the resource by creating a services.k8s.aws/AdoptedResource
```

**Steps to reproduce**
Create deployment package and upload it to s3
Create a lambda fuction with ACK with newly updated deployment package to s3
Make any code change, package it and upload it to s3 with a seperate name
Update yaml with new deployment package name
Deploy changes

**Expected outcome**
It should update lambda package

**Environment**

* Kubernetes version
1.23
* Using EKS (yes/no), if so version? 
EKS 1.23
* AWS service targeted (S3, RDS, etc.)
Lambda

**Comment by timam** [comment]
Hey @A-Hilaly

I have created a helm chart with following yam. 

```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: {{ .Values.function_name }}
  namespace: {{ .Values.namespace }}
  annotations:
    services.k8s.aws/region: {{ .Values.aws_region }}
spec:
  name: {{ .Values.function_name }}
  code:
    s3Bucket:  {{ .Values.artifact_bucket }}
    s3Key: {{ .Values.function_name }}/{{ .Values.artifact_tag }}
  role: {{ .Values.iam_role }}
  runtime: {{ .Values.runtime }}
  memorySize: {{ .Values.memory }}
  timeout: {{ .Values.timeout }}
  handler: {{ .Values.handler }}
  description: {{ .Values.function_name }} created by ACK lambda-controller
  environment:
    variables:
      {{- range $key, $val := .Values.env_vars }}
        {{ $key }} : {{ $val | quote }}
      {{- end }}
  vpcConfig:
    securityGroupIDs:
      - {{ .Values.security_group_id }}
    subnetIDs:
      {{- range .Values.subnet_ids }}
        - {{ . | quote }}
      {{- end }}

```

Next i have created a argocd pipeline. To deploy this helm chart. I supply all the helm values from a seperate (deployment) git repo. 

I was able to successfully create lambda with this approch. The problem is, when I update the value of artifact_tag in deployment git repo, argocd syncs it but the updated package doesn't get deployed. 

---
```This resource already exists but is not managed by ACK. ```
I deleted and recreated the lambda, the issue was resolved however, i am still enable to deploy updated package with ack-lambda with mentioned approch. 
---
