### ISSUE TITLE
Dynamic resource references

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1576]
The ACK ecosystem currently supports referencing resources from the same or different GVKs within a static implementation. For example, you can reference an `s3::bucket` in a `lambda::function` object. However, this implementation does not allow for the referencing of multiple resource types.

Ideally, we would like to expand this feature to support the referencing of any object managed by ACK controllers. This would allow for resources like `AWS EventBridge` Rule targets to reference a wide range of resources, such as `sns::topic` and `sqs::queue`.

The ACK ecosystem's current ability to reference resources is a new feature that was developed in response to a recent problem. @embano1 and I will continue exploring and working on a design document for this feature, which will involve refactoring the original resource reference implementation to allow for the referencing of multiple resource types. This will require moving the generation logic to the code-generator/pkg/generate package and switching to the k8s dynamic client.

**Comment by embano1** [comment]
+1  to simplify the code base (eventually) using dynamic client and make it easier to compose resources using `TypedLocalObjectReferences`.

For example, as an `EventBridge` controller user I want to reference an `SQS` queue as a target which is also managed by ACK:

```yaml
apiVersion: eventbridge.services.k8s.aws/v1alpha1
kind: Rule
metadata:
  name: rule-01
  namespace: namespace-01
spec:
  name: rule-01
  eventPattern: "{\"detail-type\":\"testevent\"}"
  # keep as is
  eventBusRef:
    name: eventbus-01
  # allows by arn and TypedLocalObjectReference
  targets:
    - id: someResourceFromArn
      arn: arn:aws:1234567890:someresource
    - id: queueFromRef
      objectRef:
        apiGroup: sqs.services.k8s.aws/v1alpha1
        kind: Queue
        name: queue-01
```

To be discussed: do we allow cross-namespace resource references (`ObjectReference`) or resources must be within the same namespace? I can see use cases for both.
