### ISSUE TITLE
IAM controller supports AttachRolePolicy

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1579]
**Is your feature request related to a problem?**
we have some cases to create roles before creating policies, then we need a proper/flexible way to attach policies to roles instead of updating role when new policy created.

**Describe the solution you'd like**
support k8s obj like 
- [IAM API - AttachRolePolicy](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html)
- [AWS::IAM::ManagedPolicy.Properties.Roles](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html)
```yaml
Type: AWS::IAM::ManagedPolicy
Properties: 
  Description: String
  Groups: 
    - String
  ManagedPolicyName: String
  Path: String
  PolicyDocument: Json
  Roles:   # this
    - String
  Users: 
    - String

```
- [crossplane IAMRolePolicyAttachment](https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMRolePolicyAttachment/v1beta1@v0.19.0)

example:
```yaml
kind: IAMRolePolicyAttachment
metadata:
  name: examplepolicyattach
spec:
    roles: 
        - examplerole
    policy: examplepolicy

```

**Comment by jaypipes** [comment]
@Julian-Chu we already support this. A `Role` resource has a `Spec.Policies` field that contains the Policy ARNs to associate with the role. You can also use the `Spec.PolicyRefs` field to refer to one or more `Policy` custom resources that you may have created (or intend to create).

**Comment by Julian-Chu** [comment]
@jaypipes  Thanks for hints.  it will be good alternative solution if we can't have policy attachment API.
Let me explain more detail. We are looking for loose coupling solution no need to update Role yaml when we deploy new resource with  policy.
for example:
```yaml
kind: IAMRolePolicyAttachment
metadata:
  name: examplepolicyattach
spec:
    roles: 
        - examplerole
    policy: examplepolicy
```
We are investigating ack to replace Crossplane.  Crossplane provides this similar policy attachment solution,  and we have something reply on this concept, and think it's not bad to have this flexibility. 😄
