### ISSUE TITLE
[dynamodb] Status always false when setting billingMode to PAY_PER_REQUEST

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1595]
**Describe the bug**
setting billingMode to PAY_PER_REQUEST makes status always false after table is created

**Steps to reproduce**
deploy 2 tables using following yaml(modified the E2E test example)

```yaml
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: ack-demo-table-pay-per-request
spec:
  keySchema:
    - attributeName: Id
      keyType: HASH
  attributeDefinitions:
    - attributeName: Id
      attributeType: 'S'
#  provisionedThroughput:
#    readCapacityUnits: 1
#    writeCapacityUnits: 1
  billingMode: "PAY_PER_REQUEST"
  tableName: "ack-demo-table-pay-per-request"
---
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: ack-demo-table-provisioned
spec:
  keySchema:
    - attributeName: Id
      keyType: HASH
  attributeDefinitions:
    - attributeName: Id
      attributeType: 'S'
  provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
  billingMode: "PROVISIONED"
  tableName: "ack-demo-table-provisioned"
```

after both tables have been created,
![image](https://user-images.githubusercontent.com/7224544/208050433-b5208db9-91f1-4d16-aa81-bbbb30d1abf1.png)

 the conditions are
- ack-demo-table-pay-per-request
```yaml
    - lastTransitionTime: "2022-12-16T07:53:09Z"
      message: Resource not synced
      reason: ""
      status: "False"
      type: ACK.ResourceSynced
```
- ack-demo-table-provisioned
```yaml
    conditions:
    - lastTransitionTime: "2022-12-16T07:45:35Z"
      message: Resource synced successfully
      reason: ""
      status: "True"
      type: ACK.ResourceSynced
```

**Expected outcome**
the Status should become True after table is created

**Environment**

* Kubernetes version: 1.23 
* EKS: 1.23 
* AWS service targeted: DynamoDB
