### ISSUE TITLE
[dynamodb] Spec.AttributeDefinitions must be sorted by ascii code order in manifest

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1599]
**Describe the bug**
the the Spec.AttributeDefinitions are not sorted by ascii code, the resource is not synced. 

**Steps to reproduce**
```yaml
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: ack-demo
spec:
  keySchema:
    - attributeName: id
      keyType: HASH
    - attributeName: externalId
      keyType: RANGE
  attributeDefinitions:
    - attributeName: id
      attributeType: S
    - attributeName: externalId
      attributeType: S
  provisionedThroughput:
    readCapacityUnits: 1
    writeCapacityUnits: 1
  tableName: "ack-demo-table"
```
log from controller 
`2022-12-19T12:32:16.641Z	INFO	ackrt	desired resource state has changed	{"account": "*******", "role": "", "region": "eu-west-1", "kind": "Table", "namespace": "default", "name": "ack-demo", "is_adopted": false, "generation": 1, "diff": [{"Path":{"Parts":["Spec","AttributeDefinitions"]},"A":[{"attributeName":"id","attributeType":"S"},{"attributeName":"externalId","attributeType":"S"}],"B":[{"attributeName":"externalId","attributeType":"S"},{"attributeName":"id","attributeType":"S"}]}]}`

format json:
```json
{
  "account": "*********",
  "role": "",
  "region": "eu-west-1",
  "kind": "Table",
  "namespace": "default",
  "name": "ack-demo",
  "is_adopted": false,
  "generation": 1,
  "diff": [
    {
      "Path": {
        "Parts": [
          "Spec",
          "AttributeDefinitions"
        ]
      },
      "A": [
        {
          "attributeName": "id",
          "attributeType": "S"
        },
        {
          "attributeName": "externalId",
          "attributeType": "S"
        }
      ],
      "B": [
        {
          "attributeName": "externalId",
          "attributeType": "S"
        },
        {
          "attributeName": "id",
          "attributeType": "S"
        }
      ]
    }
  ]
}
```

**Expected outcome**
resource should be synced.

**Environment**

Kubernetes version: 1.23
EKS: 1.23
AWS service targeted: DynamoDB
DynamoDB controller: 0.1.7

I also see similar  issue with GlobalSecondaryIndexes.indexName
