### ISSUE TITLE
Simple way to associate IAM OpenIDConnectProvider based on values of EKS cluster

### ISSUE THREAD

**Issue by mikestef9** [aws-controllers-k8s/community#1601]
**Is your feature request related to a problem?**
Need a way to create an IAM OpenIDConnectProvider based on an output value of an EKS cluster. More generically, many ACK resources might require an input value to be an output value of another ACK resource. FieldExport does not currently support this use case. 

**Describe the solution you'd like**
Something like this
```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: OpenIDConnectProvider
metadata:
  name: eks-cluster-OIDC-association
spec:
  clientIDs:
    - "sts.amazonaws.com"
  thumbprints:
    - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
  #url:
  urlRef:
    apiVersion: eks.services.k8s.aws/v1alpha1
    kind: Cluster
    name: my-cluster
    field: status.identity.oidc.issuer
```

Perhaps this could be made more generic where any ACK field could support a lookup to output status of another ACK resource

**Describe alternatives you've considered**
Haven't found any simple alternative. For now, need to create EKS cluster, copy OIDC issuer URL and hardcode into the OpenIDConnectProvider resource.
