### ISSUE TITLE
Cannot adopt EC2 security group

### ISSUE THREAD

**Issue by mathias-muench** [aws-controllers-k8s/community#1602]
**Describe the bug**

Trying to adopt an EC2 security group as adoptedresource fails with the following status:

```
Status:
  Conditions:
    Message:  SecurityGroup.ec2.services.k8s.aws "foo" is invalid: spec.name: Required value
    Status:   False
    Type:     ACK.Adopted
Events:       <none>
```

**Steps to reproduce**

Create security group:

```
$ aws ec2 create-security-group --vpc-id vpc-************* --description foo --group-name bar
{
    "GroupId": "sg-05bcc51954336de09"
}
```

Apply manifest and describe result.

```
(main *>) $ cat foo.yaml 
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: foo
spec:  
  aws:
    nameOrID: sg-05bcc51954336de09
  kubernetes:
    group: ec2.services.k8s.aws
    kind: SecurityGroup
(main *>) $ kubectl apply -f foo.yaml
adoptedresource.services.k8s.aws/foo created
(main *>) $ kubectl describe adoptedresources.services.k8s.aws
```

**Expected outcome**

Security group gets adopted.

**Environment**

* Kubernetes version: 1.22
* Using eksctl version 0.122.0
* AWS service targeted: ec2-controller v0.1.0
