### ISSUE TITLE
EC2 SecurityGroup fails when ingressRules or egressRules are defined

### ISSUE THREAD

**Issue by mustafasencer** [aws-controllers-k8s/community#1604]
**Describe the bug**
- The below error is experienced in case `ingressRules` and `egressRules` fields are included in the resource definition.

_K8S resource definition:_
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: ack-test-security-group
  namespace: cicd-platform
spec:
  description: The sg for the test application
  name: ack-test-security-group
  vpcID: {VPC_ID}
  egressRules:
    - ipProtocol: "-1"
      ipRanges:
        - cidrIP: 0.0.0.0/0
          description: Allow traffic from all IPs
  ingressRules:
    - ipProtocol: "-1"
      ipRanges:
        - cidrIP: 0.0.0.0/0
          description: Allow traffic from all IPs
  tags:
    - key: Name
      value: ack-test-security-group
```

_K8S resource status:_
```yaml
...
Status:
  Ack Resource Metadata:
    Owner Account ID:  {AWS_ACCOUNT_ID}
    Region:            eu-west-1
  Conditions:
    Message:               InvalidGroup.Duplicate: The security group 'ack-test-security-group' already exists for VPC '{VPC_ID}'
                           status code: 400, request id: {REQUEST_ID}
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2022-12-28T13:28:04Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                InvalidGroup.Duplicate: The security group 'ack-test-security-group' already exists for VPC '{VPC_ID}'
                           status code: 400, request id: {REQUEST_ID}
    Status:                Unknown
    Type:                  ACK.ResourceSynced
Events:                    <none>
```

_EC2-controller log:_
```
2022-12-28T13:19:52.700Z    ERROR    controller.securitygroup    Reconciler error    {"reconciler group": "ec2.services.k8s.aws", "reconciler kind": "SecurityGroup", "name": "ack-test-security-group", "namespace": "cicd-platform", "error": "InvalidGroup.Duplicate: The security group 'ack-test-security-group' already exists for VPC '{VPC_ID}'\n\tstatus code: 400, request id: {REQUEST_ID}"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

**Steps to reproduce**
- I applied the above resource with and without the `ingressRules` and `egressRules` fields.
- The resource was successfully synced when no security group rules have been applied.
- In presence of the security group rules the resource is created on AWS side but the K8S resource is unfortunately not synced and the above error is seen...

**Expected outcome**
- I would expect the K8S resource to be synced successfully as the resource is successfully created in AWS.

**Environment**

* Kubernetes version: `v1.23`
* EKS version: `v1.23.13-eks-fb459a0`
* ec2-controller `v0.1.0`, `SecurityGroup`resource is utilised.

**Comment by mustafasencer** [comment]
**An update on the situation:**

The error only occurs when the `egressRules` field is defined. Is there anything wrong with the SG rule that is present in the yaml definition?

**Comment by jaypipes** [comment]
@mustafasencer The error is stating that a security group with that name already exists... I don't think it has anything to do with ingressRules or egressRules. I think you need to simply delete the other `ack-test-security-group` SG.

**Comment by mustafasencer** [comment]
@jaypipes Thanks for the prompt response. 

It is the weird part of the problem which was bugging me. I deleted the SG prior to applying the above SG definition. I validated it via the console again before applying it to the cluster, so I can assure you that it was deleted. Whenever the above `egressRules` field is present in the custom resource, the SG custom resource is having trouble in syncing the resource (although the resource is created in AWS). To validate my point I tried multiple times with and without the `egressRules` field...

**Note:** Creating the SG without the `egressRules` field creates a **default outbound rule with all traffic allowed**. Could that be behind the sync issue for the SG custom resource? Thanks 🙂

**Comment by jaypipes** [comment]
Interesting... I will ask @LikithaVemulapalli to look into this and put together a reproduceable test case for it. Looks like you may have uncovered a latent bug! :)

**Comment by wanglei4687** [comment]
The same problem

```yaml
  Conditions:
    Last Transition Time:  2023-01-16T10:08:13Z
    Status:                True
    Type:                  ACK.ReferencesResolved
    Message:               InvalidGroup.Duplicate: The security group 'test-sg' already exists for VPC 'vpc-0854a1b843c796bd3'
                           status code: 400, request id: 1460adb1-580b-4b2d-a751-fac5a65a37f3
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2023-01-16T10:08:13Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                InvalidGroup.Duplicate: The security group 'test-sg' already exists for VPC 'vpc-0854a1b843c796bd3'
                           status code: 400, request id: 1460adb1-580b-4b2d-a751-fac5a65a37f3
    Status:                Unknown
    Type:                  ACK.ResourceSynced
```

remove egress rule will work.
