### ISSUE TITLE
RDS DBCluster: InvalidParameterValue: The input isn't valid. Input can't contain control characters. status code: 400

### ISSUE THREAD

**Issue by mustafasencer** [aws-controllers-k8s/community#1605]
**Describe the bug**
- When applying the same resource present in the e2e tests for `DBCluster` in the rds-controller, I encounter the following error:

_Resource applied:_
```yaml
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: my-aurora-mysql
spec:
  copyTagsToSnapshot: False
  dbClusterIdentifier: my-aurora-mysql
  databaseName: mydb
  engine: aurora-mysql
  engineMode: serverless
  masterUsername: root
  masterUserPassword:
    namespace: default
    name: dbclustersecrets
    key: master_user_password
  tags:
    - key: environment
      value: dev
```

_Error encountered:_
```
InvalidParameterValue: The input isn't valid. Input can't contain control characters. status code: 400, request id: {REQUEST_ID}
```

**Steps to reproduce:**
- I copied the same `DBCluster` resource present [here](https://github.com/aws-controllers-k8s/rds-controller/blob/main/test/e2e/resources/db_cluster_mysql_serverless.yaml) from the e2e tests with the same template values.
- After applying the resource, I constantly get the same error from the k8s custom resource.

_K8S resource status:_
```yaml
...
Status:
  Ack Resource Metadata:
    Owner Account ID:  {ACCOUNT_ID}
    Region:            eu-west-1
  Conditions:
    Message:               InvalidParameterValue: The input isn't valid. Input can't contain control characters.
                           status code: 400, request id: {REQUEST_ID}
    Status:                True
    Type:                  ACK.Terminal
    Last Transition Time:  2022-12-29T11:26:06Z
    Message:               Resource not synced
    Reason:                resource is in terminal condition
    Status:                False
    Type:                  ACK.ResourceSynced
Events:                    <none>
```

**Expected outcome**
- I expect the `DBCluster` resource to be created successfully as I am just testing the resource present in the e2e tests for the rds-controller.

**Environment**

- Kubernetes version: v1.23
- EKS version: v1.23.13-eks-fb459a0
- rds-controller v0.1.2, DBCluster is utilised.
