### ISSUE TITLE
RDS-controller - Referenced DB parameter group is not applied on DBInstance

### ISSUE THREAD

**Issue by pbikki** [aws-controllers-k8s/community#1612]
**Describe the bug**

**Update:** When a new CR is created with custom parameter group, it works fine. It doesn't take effect when applied on an existing DB instance

I'm trying to use `DBParameterGroup`  with `parameterOverrides`. I have something like below in my `DBInstance` CR spec 

```
spec:
  dbParameterGroupRef:
    from:
      name: enforce-ssl-rds-postgres
```
The `DBParameterGroup` referenced above is created with the following spec and is available
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBParameterGroup
metadata:
  name: enforce-ssl-rds-postgres
spec:
  description: for RDS postgres to enforce ssl
  family: postgres14
  name: enforce-ssl-rds-postgres
  parameterOverrides: {
    "rds.force_ssl": "1"
  }
  ```
 on reconciliation of `DBInstance` , I don't see the controller acting on it
 ```
 status:
  dbParameterGroups:
  - dbParameterGroupName: default.postgres14
    parameterApplyStatus: in-sync
  ```
  the instance still only has the default parameter group applied to the database instance
  anything that I'm missing here?
  
**Steps to reproduce**
- Create DBParameterGroup to override a default value
- Create DB instance for RDS Postgres with no custom parameter groups
- Modify DB Instance to reference a custom parameter group

**Expected outcome**
Expected new parameter group to be applied on the DB Instance

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
   - yes, "v1.23.13-eks-fb459a0"
* AWS service targeted (S3, RDS, etc.)
   - RDS
