### ISSUE TITLE
IAM Controller - does not change of policy

### ISSUE THREAD

**Issue by michalschott** [aws-controllers-k8s/community#1615]
**Describe the bug**
IAM controller does not reflect change of `spec.name` in `Policy` resource

I have not tested this for `Role`.

Controller keeps updating policy:

```
aws-iam-controller-iam-chart-58bb79ffb5-2s8zj controller 2023-01-09T13:15:50.910Z	INFO	ackrt	desired resource state has changed	{"account": "XXX", "role": "", "region": "eu-west-1", "kind": "Policy", "namespace": "XXX", "name": "my-test-policy", "is_adopted": false, "generation": 3, "diff": [{"Path":{"Parts":["Spec","Name"]},"A":"my-test-policy","B":"my-new-test-policy"}]}
```

Resource status:

```
  status:
    ackResourceMetadata:
      arn: arn:aws:iam::XXX:policy/my-test-policy
      ownerAccountID: "XXX"
      region: XXX
    attachmentCount: 0
    conditions:
    - lastTransitionTime: "2023-01-09T13:17:12Z"
      status: "False"
      type: ACK.ResourceSynced
    - lastTransitionTime: "2023-01-09T13:17:12Z"
      message: Late initialization did not complete, requeuing with delay of 5 seconds
      reason: Delayed Late Initialization
      status: "False"
      type: ACK.LateInitialized
```

**Steps to reproduce**
Apply:

```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: my-test-policy
spec:
  name: my-test-policy
  policyDocument: $(WHATEVER)
```

Update `spec.name` to whatever, for example `my-new-test-policy`

**Expected outcome**
I'd expect policy name to change (afaik you can not do that, so delete and recreate is also fine).

**Environment**

iam-controller 0.1.1
