### ISSUE TITLE
EKS Controller is asking for the ClusterName or reference when deploying a NodeGroup

### ISSUE THREAD

**Issue by matheushent** [aws-controllers-k8s/community#1627]
**Describe the bug**
According to the [documentation](https://aws-controllers-k8s.github.io/community/reference/eks/v1alpha1/nodegroup/), it is not needed to pass either the cluster name or the cluster name reference. What happens is, after setting up a manifest as follows:

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: t3-small-spot
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterName: whatever
  amiType: AL2_x86_64
  capacityType: SPOT
  diskSize: 40
  instanceTypes:
  - t3.small
    intent: apps
  name: t3-small-spot
  scalingConfig: 
    desiredSize: 0
    maxSize: 3
    minSize: 0
  subnets:
  - subnet-12345
  - subnet-123456
  tags:
    k8s.io/cluster-autoscaler/node-template/label/intent: apps
    k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
  taints:
  - effect: PreferNoSchedule
    key: spotInstance
    value: "true"
```

I see the following logs by checking the controller logs:

```
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2023-01-11T13:43:55.499Z	ERROR	controller.nodegroup	Reconciler error	{"reconciler group": "eks.services.k8s.aws", "reconciler kind": "Nodegroup", "name": "t3-small-spot", "namespace": "kube-system", "error": "resource reference wrapper or ID required: ClusterName,ClusterRef"}
```

**Steps to reproduce**

1.
```bash
# create the manifest
cat > manifest.yaml <<EOF
\ apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: t3-small-spot
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterName: whatever
  amiType: AL2_x86_64
  capacityType: SPOT
  diskSize: 40
  instanceTypes:
  - t3.small
    intent: apps
  name: t3-small-spot
  scalingConfig:
    desiredSize: 0
    maxSize: 3
    minSize: 0
  subnets:
  - subnet-12345
  - subnet-123456
  tags:
    k8s.io/cluster-autoscaler/node-template/label/intent: apps
    k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
  taints:
  - effect: PreferNoSchedule
    key: spotInstance
    value: "true"
\ EOF
```

2.
```bash
# apply the manifest
kubectl apply -f manifest.yaml
```

3.
```bash
# check the logs of eks controller pod
kubectl logs <pod>
```

**Expected outcome**
I expected to see a node groupd named `t3-small-spot` on the EKS console since I passed all the required arguments described in the documentation.

**Environment**

* Kubernetes version 1.23
* Using EKS (yes/no), if so version? yes, 1.23
* AWS service targeted (S3, RDS, etc.) EKS
