### ISSUE TITLE
BUG: sagemaker ACK operator sync issue

### ISSUE THREAD

**Issue by codekow** [aws-controllers-k8s/community#1628]
**Describe the bug**

`volumeSizeInGB` is a required field for a new CR otherwise the operator goes into an infinite loop and won't sync.

The notebook instance is created but cycles between the following states: `Updating`, `Stopping`
 
**Steps to reproduce**

Created following CR on cluster with ACK operator:

```
apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstance
metadata:
  name: example
spec:
  # NOTICE: There is no CRD for CodeRepository (manual creation) 
  defaultCodeRepository: 'https://github.com/redhat-na-ssa/demo-rosa-sagemaker.git'
  instanceType: ml.m5.4xlarge
  lifecycleConfigName: lifecycle-from-github
  notebookInstanceName: demo-0
  roleARN: 'arn:aws:iam::000000000000:role/AmazonSageMaker-ExecutionRole'
```

**Expected outcome**

Notebook exists in AWS

**Environment**

Sagemaker ACK Operator: 0.5.1
ROSA OpenShift: 4.10.42
