### ISSUE TITLE
Code-gen should add markers for nested shapes

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1645]
**Is your feature request related to a problem?**
Yes, in the EventBridge controller we use `custom_fields` to embed model shapes into a CR:

```yaml
Rule:
      Targets:
        custom_field:
          list_of: Target
```

Currently, neither comments (on the `Targets` field in a `Rule`) nor kube markers are added to required field to this shape in the resulting Kubernetes API definitions.

**Describe the solution you'd like**
Treat nested/custom fields like top level fields when it comes to adding comments, kube markers, setting immutability, etc. in code-gen.

**Describe alternatives you've considered**
n/a

**Comment by jaypipes** [comment]
@embano1 I don't recommend using `custom_field` except as a last resort. If you want the kube required markers for a field, use the `type` configuration option and the `is_required` configuration option.

For example, here's how I added a [custom `Policies` field in the IAM controller](https://github.com/aws-controllers-k8s/iam-controller/blob/2f0a8cb2c303d0d5ec8d5133b4b350f20d4752be/generator.yaml#L60-L64):

```yaml
      Policies:
        type: "[]*string"
        references:
          resource: Policy
          path: Status.ACKResourceMetadata.ARN
```

that particular field isn't required, but I could add:

```yaml
      Policies:
        is_required: true
        type: "[]*string"
        references:
          resource: Policy
          path: Status.ACKResourceMetadata.ARN
```

to make it so.

Still doesn't have documentation, though, which is a definite known issue!
