### ISSUE TITLE
EC2 Controller: securitygroup  InvalidGroup.Duplicate: The security group 'test-ack' already exists

### ISSUE THREAD

**Issue by wanglei4687** [aws-controllers-k8s/community#1652]
**Describe the bug**

update securitygroup spec, will report error

so, Should we check securitygroup name when update securitygroup spec

**Steps to reproduce**

kubectl apply -f sg.yaml

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test
spec:
  description: "ack test security group"
  name: test-ack
  # https://docs.aws.amazon.com/zh_cn/eks/latest/userguide/sec-group-reqs.html#security-group-restricting-cluster-traffic
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html
#  ingressRules:
#    - ipProtocol: "-1"
#      fromPort: -1
#      toPort: -1
#  egressRules:
#    - ipProtocol: "-1"
#      fromPort: -1
#      toPort: -1
#      ipRanges:
#        - cidrIP: "0.0.0.0/0"
#          description: "test egress"
  vpcRef:
     from:
       name: test
```

sg.yaml
```yaml
status:
  ackResourceMetadata:
    ownerAccountID:  <ACCOUNTID>
    region: us-west-2
  conditions:
  - lastTransitionTime: "2023-01-31T07:05:03Z"
    status: "True"
    type: ACK.ReferencesResolved
  - message: "InvalidGroup.Duplicate: The security group 'test-ack' already exists
      for VPC 'vpc-0894101e92626ff10'\n\tstatus code: 400, request id: 44c4facb-c514-4989-a987-3ac504d8af47"
    status: "True"
    type: ACK.Recoverable
  - lastTransitionTime: "2023-01-31T07:05:03Z"
    message: Unable to determine if desired resource state matches latest observed
      state
    reason: "InvalidGroup.Duplicate: The security group 'test-ack' already exists
      for VPC 'vpc-0894101e92626ff10'\n\tstatus code: 400, request id: 44c4facb-c514-4989-a987-3ac504d8af47"
    status: Unknown
    type: ACK.ResourceSynced
```

**Expected outcome**

update securitygroup, Not created sg

**Environment**

* Kubernetes version: 1.23
* Using EKS (yes/no), no
* AWS service targeted (S3, RDS, etc.)
