### ISSUE TITLE
`add_synced_column` not respected

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1659]
**Describe the bug**
Given this `generator.yaml` configuration for a resource to add `AGE` and `Synced` columns, `Synced` never shows up on the resource:

```yaml
    print:
      add_age_column: true
      add_synced_column: true
```

```console
k get rule -A
NAMESPACE   NAME                          ARN                                                                   SYNCED   AGE
default     filter-rule-01-eu-central-1   arn:aws:events:eu-central-1:331505801289:rule/bus-01/filter-rule-01            2m20s
```

The generated CRD code:

```yaml
    - jsonPath: .status.conditions[?(@.type=="ACK.ResourceSynced")].status
      name: Synced
      type: boolean
```

If I change `type` to `string` it works:

```console
NAMESPACE   NAME                                                            ARN                                                                   SYNCED   AGE
default     rule.eventbridge.services.k8s.aws/filter-rule-01-eu-central-1   arn:aws:events:eu-central-1:331505801289:rule/bus-01/filter-rule-01   True     15s
```

**Steps to reproduce**

See above.

**Expected outcome**
Generated code should correctly set the status to `True` or `False`.

**Environment**

`code-generator`

```console
git rev-parse HEAD
b55ae8752ece381c383ffe5b388ed2147c6b30d8
```
