### ISSUE TITLE
Consider changing `defaultResyncPeriod` values and doc string

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1671]
The current setting of `defaultResyncPeriod` such as in the Helm chart [`values.yaml`](https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/helm/values.yaml.tpl#L86-L91) is a bit misleading as it does not explain what the default value is when using `0`. In fact, it's `10h` (`36000s`).

```yaml
# controller reconciliation configurations
reconcile:
  # The default duration, in seconds, to wait before resyncing desired state of custom resources.
  defaultResyncPeriod: 0
  # An object representing the reconcile resync configuration for each specific resource.
  resourceResyncPeriods: {}
```

The logic in the Helm chart uses `gt` comparison against `0`. My proposal would be to make the **default** value represent the **actual** value i.e., `36000s`, and be explicit here. 

This change should also not have any effect on the controller template in [`deployment.yaml`](https://github.com/aws-controllers-k8s/code-generator/blob/adad76c83f3d68f419c7ca294fa50f068a1c97bb/templates/config/controller/deployment.yaml.tpl#L40-L41).
