### ISSUE TITLE
IAM controller: create a role suitable for IRSA

### ISSUE THREAD

**Issue by james-callahan** [aws-controllers-k8s/community#1694]
**Is your feature request related to a problem?**
When using the IAM controller, I expect to be able to create an IAM role suitable for use with IRSA

This would involve creation of an `assumeRolePolicyDocument` of something like: 

```json
"AssumeRolePolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789:oidc-provider/myoidcprovider.example.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "myoidcprovider.example.com:sub": "system:serviceaccount:mynamespace:myserviceaccount"
                }
            }
        }
    ]
}
```

**Describe the solution you'd like**
1. Instead of providing a opaque json/yaml blob for `assumeRolePolicyDocument`, have an (optional) kubernetes native form. e.g.
    ```yaml
    apiVersion: iam.services.k8s.aws/v1alpha1
    kind: Role
    metadata:
      name: myrole
    spec:
      name: myrole
      assumeRolePolicy:
        - sid: "" # should also be the default if absent
          effect: allow
          principal:
            type: federated
            value: arn:aws:iam::123456789:oidc-provider/myoidcprovider.example.com
          actions:
            - sts:AssumeRoleWithWebIdentity
          conditions:
            - test: StringEquals
              variable: myoidcprovider.example.com:sub
              values:
                - system:serviceaccount:mynamespace:myserviceaccount
   ```
2. Enhance `FieldExport` to be more like [kustomize replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/), supporting:
    - multiple targets
    - `delimiter` and `index`
   This point is possibly related to https://github.com/aws-controllers-k8s/community/issues/1417

   e.g.
    ```yaml
    apiVersion: iam.services.k8s.aws/v1alpha1
    kind: Role
    metadata:
      name: myrole
    spec:
      name: myrole
      assumeRolePolicy:
        - effect: allow
          principal:
            type: federated
            value: # to be filled in by `FieldExport`
          actions:
            - sts:AssumeRoleWithWebIdentity
          conditions:
            - test: StringEquals
              variable: :sub # to be filled in by `FieldExport`
              values:
                - system:serviceaccount:mynamespace:myserviceaccount
    ---
    apiVersion: services.k8s.aws/v1alpha1
    kind: FieldExport
    metadata:
      name: myrole-oidc
    spec:
      from:
        resource:
          kind: OpenIDConnectProvider
          name: myoidcprovider
          path: .ackResourceMetadata.arn
      to:
        - kind: Role
          name: myrole
          path: spec.assumeRolePolicy.0.principal.value
        - kind: Role
          name: myrole
          path: spec.assumeRolePolicy.0.conditions.0.variable
          delimiter: ":"
   ```

**Describe alternatives you've considered**
  - `assumeRolePolicyDocument` could be a templatable string?
  - variant of `Role` explicitly made for this purpose that can reference an `OIDCProvider`
