### ISSUE TITLE
Attribute-based APIs should check whether map of attributes is empty before setting Create Input shape

### ISSUE THREAD

**Issue by nielstenboom** [aws-controllers-k8s/community#1695]
**Describe the bug**
The sqs controller crashes with the following error if you try to create a queue without the delaySeconds field specified:

```
2023-02-15T10:00:13.577Z	ERROR	controller.queue	Reconciler error	{"reconciler group": "sqs.services.k8s.aws", "reconciler kind": "Queue", "name": "test-niels-queue", "namespace": "aws-controllers", "error": "MalformedInput: End of list found where not expected\n\tstatus code: 400, request id: 87b0a4ad-0ae0-5e82-8147-f8cba58d6c3f"}
```

**Steps to reproduce**
Create Queue object as follows:

```yaml
apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: my-test-queue
spec:
  queueName: my-test-queue
```

**Expected outcome**
I expected a default to be chosen and not a crash, since the resource does not mention this field to be required:

```console
$ kubectl explain queue.spec
   
KIND:     Queue
VERSION:  sqs.services.k8s.aws/v1alpha1

RESOURCE: spec <Object>

DESCRIPTION:
     QueueSpec defines the desired state of Queue.

FIELDS:
   contentBasedDeduplication	<string>

   delaySeconds	<string>
```

**Environment**
v0.0.3
