### ISSUE TITLE
Namespace references should default to the current namespace

### ISSUE THREAD

**Issue by james-callahan** [aws-controllers-k8s/community#1699]
**Is your feature request related to a problem?**

Currently if you don't specify a `namespace` then you get the `default` namespace.
This is rarely desired and means there's a easy place to forget changing a namespace as you deploy resources to a different namespace
e.g. in a `rds.services.k8s.aws/v1alpha1` `DBInstance` the `masterUserPassword` is a reference to a `Secret`

```yaml
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: mydb
  namespace: foo
spec:
  dbInstanceIdentifier: mydb
  dbSubnetGroupName: mysubnet
  engine: postgres
  engineVersion: "14.6"
  masterUsername: root
  masterUserPassword:
    namespace: foo # if not provided, uses the `default` namespace
    name: mysecret
    key: PGPASS
```

**Describe the solution you'd like**
When there is a `namespace` field in a reference and it is not set, use the namespace of the current resource.

**Describe alternatives you've considered**
  - Make the `namespace` field required instead of optional.
