### ISSUE TITLE
acm controller - certificate is created with mail and not dns validation

### ISSUE THREAD

**Issue by selfisch** [aws-controllers-k8s/community#1701]
**Describe the bug**
Just installed the acm-controller in eks k8s cluster. IAM role and policiy has been generated, service account configured, everything is fine. Certificates are created as well, but validation is always set to mail instead of dns.

Maybe its a missing documentation, because I am using public ca, not private. Is dns verification not available with public ca certs?

**Steps to reproduce**
Deploy acm-controller via [helm-chart](https://github.com/aws-controllers-k8s/acm-controller/tree/main/helm) and configure IAM like mentioned [here](https://github.com/aws-controllers-k8s/acm-controller/tree/main/config/iam)
```
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: host.sub.domain.com
spec:
  domainName: host.sub.domain.com
```

**Expected outcome**
Certificate should be created with dns validation. In worst case, one has to create cname records for validation initial manually.

**Environment**

* Kubernetes version: 1.23
* Using EKS: yes
* EKS version: eks.6
* AWS service targeted (ACM)
