### ISSUE TITLE
[apigatewayv2] Missing trigger when creating integration targeting lambda function

### ISSUE THREAD

**Issue by mbolek** [aws-controllers-k8s/community#1703]
**Describe the bug**
When creating a route and an integration with apigatewayv2 controller everything is set up properly on the Gateway side but the lambda function doesn't have any triggers that would allow it to be called by the API Gateway.

**Steps to reproduce**
```
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "ack-api"
spec:
  name: "ack-api"
  protocolType: HTTP
---
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "ack-integration"
spec:
  apiRef:
    from:
      name: "ack-api"
  integrationType: AWS_PROXY
  integrationURI: "arn:aws:lambda:${AWS_REGION}:${ACCOUNT_ID}:function:bla"
  integrationMethod: GET
  connectionType: INTERNET
  timeoutInMillis: 30000
  payloadFormatVersion: "2.0"
---
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "ack-route"
spec:
  apiRef:
    from:
      name: "ack-api"
  routeKey: "GET /ack-route-key"
  targetRef:
    from:
      name: "ack-integration"
---
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  name: "ack-stage"
spec:
  apiRef:
    from:
      name: "ack-api"
  stageName: "ack-stage"
  autoDeploy: true
  description: "auto deployed stage for ack-api"
```
Applying the above properly creates the `ack-api` API in the API GW service, route and integration are also in place:
![image](https://user-images.githubusercontent.com/4385195/220598592-676efb8c-4212-4d30-a305-09b290f96945.png)
The integration looks ok:
![image](https://user-images.githubusercontent.com/4385195/220599110-bb47fc3a-523f-4c37-8de3-f363a9117954.png)
but the lambda itself gets no triggers:
![image](https://user-images.githubusercontent.com/4385195/220599209-4c914b13-cb38-4469-b3a6-bb80442d1cd6.png)

**Expected outcome**
The lambda function can be called by the lambda

**Environment**
* Kubernetes version
1.22
* Using EKS (yes/no), if so version? 
no, kops based cluster
* AWS service targeted (S3, RDS, etc.)
api gateway v2 / lambda
