### ISSUE TITLE
Secrets Integration Lambda ACK

### ISSUE THREAD

**Issue by seanmcguigan** [aws-controllers-k8s/community#1710]
**Is your feature request related to a problem?**
Problem similar to [Alice's problem](https://github.com/aws-controllers-k8s/community/blob/9d9f86bbe760fc0fa92b2af843a0768026b5e530/docs/design/proposals/secrets/secrets.md) only for the Lambda ACK. There is no way to reference secrets that are already defined in k8s as Lambda env vars.

**Describe the solution you'd like**
I would like to see an option to do the following:
```
spec:
  environment:
    variables:
      FOO: "bar"
      SECRET_USERNAME:
        from:
          secretKeyRef:
            name: backend-user
            key: backend-username
```

**Describe alternatives you've considered**
An alternative would be to encrypt the manifest in version control with something like SOPS, but that's not really an option.

**Comment by blueacidification** [comment]
Hi, any updates on this ?

**Comment by smoke** [comment]
As a way to solve such needs and checking the code I would suggest the following example CRD using `environment.variablesFrom` as first step.

This will be supporting to env variables from configMapRef or secretRef

```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: my-lambda-function
spec:
  functionName: "my-lambda-function"
  handler: "index.handler"
  role: "arn:aws:iam::123456789012:role/lambda-role"
  runtime: "nodejs14.x"
  environment:
    variablesFrom:
      - configMapRef:
          name: general-config
      - secretRef:
          name: sensitive-config
    variables:
      LOG_LEVEL: "debug"
```

The relevant apis strics will be changed as follows:
```go
#### Modify `apis/v1alpha1/function.go`
type FunctionSpec struct {
    ...
    // Environment variables for the Lambda function
    Environment *Environment `json:"environment,omitempty"`
}
type Environment struct {
    Variables map[string]*string `json:"variables,omitempty"`
    // variablesFrom allows environment variables to be populated from Kubernetes ConfigMaps or Secrets
    VariablesFrom []VariablesFromSource `json:"variablesFrom,omitempty"`
}
// VariablesFromSource represents environment variables from ConfigMaps or Secrets
type VariablesFromSource struct {
    ConfigMapRef *ConfigMapEnvSource `json:"configMapRef,omitempty"`
    SecretRef    *SecretEnvSource    `json:"secretRef,omitempty"`
}
// ConfigMapEnvSource selects a ConfigMap for environment variables
type ConfigMapEnvSource struct {
    Name string `json:"name"`
}
// SecretEnvSource selects a Secret for environment variables
type SecretEnvSource struct {
    Name string `json:"name"`
}
```
