### ISSUE TITLE
Missing field ref in type definition for Attributes-Based fields

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1721]
Currently, the code-generator allows ACK devleopers to generate code that allows field references across multiple resource/controllers. However, we have identified an issue with the generated code Attributes-based fields. 
While building a controller (`sns` for example) with field references, the code generator outputs the code that handles reference resolving, but doesn't correctly generate the `Spec` type definition (Ref fields are missing)

**Comment by A-Hilaly** [comment]
NVM, worked when i added `type: string`:
```yaml
      Policy:
        is_attribute: true
        type: string
        references:
          service_name: iam
          resource: Policy
          path: Spec.PolicyDocument
```
/close
