### ISSUE TITLE
ACM Controller - Import certificate

### ISSUE THREAD

**Issue by migueleliasweb** [aws-controllers-k8s/community#1723]
**Is your feature request related to a problem?**
No. It's just a feature that isn't implemented yet.

**Describe the solution you'd like**

As the importing process takes in a private key which should be considered a secret, it wouldn't be wise to have that as a key straight in the definition of the `Kind`. Although it's possbie to restrict access to that specific kind with RBAC. But still...

I was thinking it could be interesting to load those information from secrets manager, for example.

So the CR could look like this:

```yaml
apiVersion: acm.services.k8s.aws/v1alpha1
kind: CertificateImport
metadata:
  name: $name
spec:
  certificateBody:
    fromSecretsManager:
      secretName: my-domain-com-body
  certificatePrivateKey:
    fromSecretsManager:
      secretName: my-domain-com-priv-key
  certificateChain:
    fromSecretsManager:
      secretName: my-domain-com-chain
```

**Describe alternatives you've considered**

I could use TF to do this, but it wouldn't be nearly as nice.

**Comment by A-Hilaly** [comment]
Hello @migueleliasweb - loading something from KMS would require giving KMS access to the acm-controller... How about loading the certificates for a kubernetes `Secret`?

**Comment by migueleliasweb** [comment]
Hi @A-Hilaly , yeah there's that. 

Maybe there isn't a huge problem on taking that leap as the controller can run with IRSA anyway so we can finely tune the permissions?

Regarding using a `Secret` from Kubernetes. I wonder if that would be much different than just inlining all of the required fields in the `CertificateImport` CR and just rely on K8s RBAC to restrict access. Does that make sense?

**Comment by A-Hilaly** [comment]
>Maybe there isn't a huge problem on taking that leap as the controller can run with IRSA anyway so we can finely tune the permissions?

@migueleliasweb If we do that we kinda breach one of the principals of ACK controllers, they ideally need to be as minimalist as possible and require the minimum possible to manage resources in a "single" service. Reading from KMS is kinda breaching this contract.

IMO The ACK-way of handling this case would be to use both `kms` and `acm` controllers, have the `kms-controller` export the certificate to a Kubernetes Secret, then import it from an `ACM` resource. Not an ACM/KMS expert here - correct me if i'm wrong :))

Also, we could definitely discuss this case during the community meeting with more folks

**Comment by migueleliasweb** [comment]
> @migueleliasweb If we do that we kinda breach one of the principals of ACK controllers, they ideally need to be as minimalist as possible and require the minimum possible to manage resources in a "single" service. Reading from KMS is kinda breaching this contract.

I see. Yeah that makes sense.

> IMO The ACK-way of handling this case would be to use both kms and acm controllers, have the kms-controller export the certificate to a Kubernetes Secret, then import it from an ACM resource. Not an ACM/KMS expert here - correct me if i'm wrong :))

I actually considered this but with with `SecretsManager`. Turns out the SecretsManager controller isn't out yet. Personally, I reckon it would be more suitable for this kind of work other than KMS.

> Also, we could definitely discuss this case during the community meeting with more folks

Yes, please! Let me know what comes out of it.

**Comment by migueleliasweb** [comment]
Maybe now we have a perfect excuse to put out the SecretsManager controller 👀 

```
apiVersion: acm.services.k8s.aws/v1alpha1
kind: CertificateImport
metadata:
  name: $name
spec:
  certificateBody:
    fromSecretsManagerController:
      secretName: my-domain-com-body
  certificatePrivateKey:
    fromSecretsManagerController:
      secretName: my-domain-com-priv-key
  certificateChain:
    fromSecretsManagerController:
      secretName: my-domain-com-chain
```

https://github.com/aws-controllers-k8s/community/issues/628

**Comment by migueleliasweb** [comment]
@A-Hilaly sorry to bother but it's been a while. Did anything come out of the meeting?

I wonder if there has been any pushback in implenenting this feature and/or what you it take for us to get some traction here 😉  .

**Comment by A-Hilaly** [comment]
Hi @migueleliasweb , we still didn't discuss this in the community meetings unfortunately. However we plans on creating the `secretsmanager` controller soon.
Also we can do references between `acm` and `secretsmanager` using something like https://github.com/aws-controllers-k8s/lambda-controller/blob/main/test/e2e/resources/alias-ref.yaml#L9-L12

**Comment by migueleliasweb** [comment]
Oh, that's some interesting news regarding the secrets manager controller!

The possibility of referencing a lambda is quite cool but would it still make sense to reference a lambda given there will be a secrets manager controller anyway? I'm just thinking from the users perspective as I'd rather not have to create a lambda to bridge that functionality.

**Comment by A-Hilaly** [comment]
@migueleliasweb I just mentionned an example, not sure referencing lambda will make sense. Here is `CertificateImport` can look like with current code-generator state:
```yaml
apiVersion: acm.services.k8s.aws/v1alpha1
kind: CertificateImport
metadata:
  name: $name
spec:
  certificateBodyRef:
    from:
      name: my-domain-com-body
  certificatePrivateKeyRef:
    from:
      name: my-domain-com-priv-key
  certificateChainRef:
    ref:
      name: my-domain-com-chain
```
