### ISSUE TITLE
spec.subnetIDs empty after adoption of `CacheSubnetGroup`

### ISSUE THREAD

**Issue by mustafasencer** [aws-controllers-k8s/community#1725]
**Describe the bug**
Similar to https://github.com/aws-controllers-k8s/community/issues/1389, the `spec.subnetIDs: Required value` error is encountered when an existing resource of type `CacheSubnetGroup` is adopted.

**Steps to reproduce**
- Create a basic `CacheSubnetGroup` configured with some dummy subnet ids.
- Adopt the resource via the `AdoptedResource` resource.
- The following error pops up in the status of the `AdoptedResource`:
```yaml
Status:
  Conditions:
    Message:  CacheSubnetGroup.elasticache.services.k8s.aws "{AWS_RESOURCE_NAME}" is invalid: spec.subnetIDs: Required value
    Status:   False
    Type:     ACK.Adopted
```

**Expected outcome**
Following the error `CacheSubnetGroup` resource is not created by the `AdoptedResource`. I expect the respective `CacheSubnetGroup` to be created and that the adoption is executed with success.

**Environment**

* Kubernetes version **1.23**
* Using EKS (yes/no), if so version? **yes**
* AWS service targeted (S3, RDS, etc.) **elasticache**
