### ISSUE TITLE
IAM controller does not correctly update inlinePolicies

### ISSUE THREAD

**Issue by matt-simons** [aws-controllers-k8s/community#1735]
**Describe the bug**

The IAM controller incorrectly calculates a delta for `map[string]*string` and erroneously removes policies that it should not. This appears to be due it [comparing the pointer](https://github.com/aws-controllers-k8s/iam-controller/blob/main/pkg/resource/role/hooks.go#L211) rather than the string. This bug may exist in other resources using the same method of comparison:

**Steps to reproduce**

create two resources `role-a.yaml` and `role-ab.yaml` like so:

```yaml
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: my-role
spec:
  assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Sid":"","Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
  inlinePolicies:
    a: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["ecr:GetAuthorizationToken","ecr:BatchGetImage","ecr:GetDownloadUrlForLayer"],"Resource":"*"}]}'
  name: my-role
```

```yaml
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: my-role
spec:
  assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Sid":"","Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
  inlinePolicies:
    a: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["ecr:GetAuthorizationToken","ecr:BatchGetImage","ecr:GetDownloadUrlForLayer"],"Resource":"*"}]}'
    b: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["ecr:GetAuthorizationToken","ecr:BatchGetImage","ecr:GetDownloadUrlForLayer"],"Resource":"*"}]}'
  name: my-role
```

Then follow the steps below:

```
❯ aws iam get-role --role-name my-role

An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name my-role cannot be found.

❯ kubectl apply -f role-a.yaml
role.iam.services.k8s.aws/my-role created

❯ aws iam get-role --role-name my-role
{
    "Role": {
        "Path": "/",
        "RoleName": "my-role",
        "RoleId": "AROA37ZSVHLWTL6HALRGH",
        "Arn": "arn:aws:iam::111111111111:role/my-role",
        "CreateDate": "2023-03-17T11:25:17+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "ec2.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
        "MaxSessionDuration": 3600,
        "Tags": [],
        "RoleLastUsed": {}
    }
}

❯ aws iam list-role-policies --role-name my-role
{
    "PolicyNames": [
        "a"
    ]
}

❯ kubectl apply -f role-ab.yaml
role.iam.services.k8s.aws/my-role configured

❯ aws iam list-role-policies --role-name my-role
{
    "PolicyNames": [
        "b"
    ]
}
```

Alternatively can be reproduce in go:

```go
package main

import (
	svcapitypes "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
	"github.com/kr/pretty"
	"github.com/samber/lo"
)

func main() {

	aStr := "a"
	bStr := "b"
	cStr := "a"

	a := &svcapitypes.Role{
		Spec: svcapitypes.RoleSpec{
			InlinePolicies: map[string]*string{
				"a": &aStr,
			},
		},
	}

	b := &svcapitypes.Role{
		Spec: svcapitypes.RoleSpec{
			InlinePolicies: map[string]*string{
				"a": &cStr,
				"b": &bStr,
			},
		},
	}

	existingPolicies := a.Spec.InlinePolicies
	desiredPolicies := b.Spec.InlinePolicies

	existingPairs := lo.ToPairs(existingPolicies)
	desiredPairs := lo.ToPairs(desiredPolicies)

	toDelete, toAdd := lo.Difference(existingPairs, desiredPairs)

	pretty.Printf("toDelete: %v\n", pretty.Sprint(toDelete))
	pretty.Printf("toAdd: %v\n", pretty.Sprint(toAdd))

}
```

```
❯ go run main.go
toDelete: []lo.Entry[string,*string]{
    {
        Key:   "a",
        Value: &"a",
    },
}
toAdd: []lo.Entry[string,*string]{
    {
        Key:   "a",
        Value: &"a",
    },
    {
        Key:   "b",
        Value: &"b",
    },
}
```

**Expected outcome**

The IAM controller should not have deleted policy a.

Because the reconciling code deletes after it adds it removes policy a. It could be fixed by swapping this order but ideally it shouldn't remove at all

**Environment**

* Kubernetes version v1.24.6
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.) IAM
