### ISSUE TITLE
[Elasticache] when using redis >=6, the controller still compares the patch version 

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1737]
**Describe the bug**
when I set `engineVersion: 6.2` in the manifest, the controller always logs the engineVersion is diff because of patch version.
```shell
2023-03-20T12:48:56.000Z	INFO	ackrt	desired resource state has changed	{"account": "647927084307", "role": "", "region": "eu-west-1", "kind": "ReplicationGroup", "namespace": "cloud-application-platform", "name": "oamapp-0083-version-test", "is_adopted": false, "generation": 2, "diff": [{"Path":{"Parts":["Spec","EngineVersion"]},"A":"6.2","B":"6.2.6"}]}
```

based on elasticache doc, the patch version is managed by AWS when redis >=6:
> Beginning with Redis 6.0, ElastiCache for Redis will offer a single version for each Redis OSS minor release, rather than offering multiple patch versions.

This issue also prevents the sequent modification like description change.

 
**Steps to reproduce**
apply the following yaml,  and log the elasticache controller
```yaml
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: oamapp-0083-version-test
spec:
    cacheNodeType: cache.t3.micro
    cacheParameterGroupName: default.redis6.x
    cacheSubnetGroupName: default
    description: version test
    engine: redis
    engineVersion: "6.2"
    numNodeGroups: 1
    replicationGroupID: oamapp-0083-version-test
    replicasPerNodeGroup: 0
    transitEncryptionEnabled: true
    tags:
      - key: test
        value: "test"
```

**Expected outcome**
if set minor version explicitly like `7.0` or `6.2`,  controller should skip the patch version 

[source code](https://github.com/aws-controllers-k8s/elasticache-controller/blob/d36fa20fe92ed0b9dc05d7e35d2778493ed83d8b/pkg/resource/replication_group/delta_util.go#L46)

**Environment**

* Kubernetes version: 1.23
* Using EKS: 1.23
* AWS service targeted: elasticache controller v0.0.22
