### ISSUE TITLE
[Elasticache] tags not modified

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1738]
**Describe the bug**
modify the tags in the yaml file, but tags are not modified

**Steps to reproduce**
apply the following manifest
```yaml
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: oamapp-0083-tags-test
spec:
    cacheParameterGroupName: default.redis6.x
    engine: redis
    engineVersion: "6.x"
    replicationGroupID: oamapp-0083-tags-test
    description: tag modification
    cacheNodeType: cache.t3.micro
    numNodeGroups: 1
    replicasPerNodeGroup: 0
    transitEncryptionEnabled: true
    cacheSubnetGroupName: default
    tags:
      - key: test
        value: "test"
     # - key: newTag
     #  value: "add"
```

then modify the tag value and add new tag
```yaml
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: oamapp-0083-tags-test
spec:
    cacheParameterGroupName: default.redis6.x
    engine: redis
    engineVersion: "6.x"
    replicationGroupID: oamapp-0083-tags-test
    description: tag modification
    cacheNodeType: cache.t3.micro
    numNodeGroups: 1
    replicasPerNodeGroup: 0
    transitEncryptionEnabled: true
    cacheSubnetGroupName: default
    tags:
      - key: test
        value: "test modified"
      - key: newTag
        value: "add"
```

and controller doesn't print any diff or info on log info level.

**Expected outcome**
tags should be modified and some log from controller

**Environment**

* Kubernetes version: 1.23
* Using EKS: 1.23
* AWS service targeted: elasticache controller v0.0.22
