### ISSUE TITLE
Feature Request: Add optional values to deployment for IRSA

### ISSUE THREAD

**Issue by ShacharMalachi** [aws-controllers-k8s/community#1756]
**Is your feature request related to a problem?**

- For self-hosted clusters, it is required to install and use aws-pod-identity-webhook in order to use IRSA for external helm-charts, such as aws controllers, and then add the required annotation to service account with role-arn and api-audience.
- Webhhok must be deployed and running before any other app that needs IRSA credentials, so the webhook will be able catch pod creation event and inject the required values to the pod.
- Sometimes it is difficult to control the order of deployment, for example when cluster is being hibernated and then wake up all pods at once without any order. In such case, webhook might start running just after other pods, and won't catch their pod creation event.
- Currently we're solving this problem by restarting all relevant deployments if it's needed, but I would like to request a feature that would help preventing this problem specifically for aws controllers: adding an option to pass the required IRSA values with helm templating instead of using the webhook.

**Describe the solution you'd like**

Add to deployment.yaml:
1. Additional env variables (in the container item) - you can add an option to add additional env variables in a range, in the same fashion you're doing in annotations here: https://github.com/aws-controllers-k8s/iam-controller/blob/90330ae3aca857a5e8d03e4bfa9d5b6e6621dfe3/helm/templates/deployment.yaml#L22
or you can add specifically just the required env vars for an easy use for the user.

2. Additional volumeMounts (in the container item).
3. Additional volumes.

This is all the required properties the deployment yaml should have for using IRSA:

```yaml
spec:
  template:
    spec:
      containers:
      - env:
        - name: AWS_ROLE_ARN
          value: <role-arn>
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        volumeMounts:
        - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          name: aws-iam-token
          readOnly: true
      volumes:
      - name: aws-iam-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
```

Thanks,
Shachar.
