### ISSUE TITLE
Add new `$field.set[].To` configuration 

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1775]
Currently `ack-generate` support generating sdk code that set CR fields from custom/unusual sdk response fields using [`SetConfigField`](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/config/field.go#L159-L217) option. Example:
```yaml
  Instance:
    fields:
      SecurityGroups:
        set:
          - from: GroupName
```

Similarily it would be benefitial for few controllers (cloudtrail, ecs, elbv2 etc...) to be able to set sdk inputs from custom/unusual CR fields instead of having to inject custom code like
- https://github.com/aws-controllers-k8s/cloudtrail-controller/blob/main/templates/hooks/event_data_store/sdk_delete_post_build_request.go.tpl

We can follow the same pattern and use [`SetConfigField`](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/config/field.go#L159-L217) to set an input from a specific Field e.g:

```yaml
  EventDataStore:
    fields:
      ACKResourceMetadata.ARN:
        set:
          - to: EventDataStore
```
and

```yaml
  TaskDefinition:
    fields:
      ServiceName:
        set:
          - to: Service
            operation: Update
      Family:
        set:
          - to: TaskDefinition
            operation: ReadOne
```
