### ISSUE TITLE
ec2-controller - v1.0.1 - Security Group Resource fails with Dup Resource when Configured with Ingress/Egress Rules

### ISSUE THREAD

**Issue by bmac423** [aws-controllers-k8s/community#1783]
**Describe the bug**
The security group resource fails with a duplicate resource error when configured with an Ingress or Egress rule. It seems to create an empty security group (no rules), and is unable to add the configured rules. An empty security group comes up as expected. The controller has all the premissions needed for EC2.

**** Error
```
Message:               Unable to determine if desired resource state matches latest observed state
Reason:                InvalidGroup.Duplicate: The security group 'redacted' already exists for VPC 'redacted'
                           status code: 400, request id: redacted
```

This appears to be a recent regression, as it works for an earlier version `v0.1.0`.

**Steps to reproduce**
Apply the following against an `v1.0.1` ec2 controller:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: redacted
  namespace: redacted
spec:
  description: Security group for the redacted RDS instance
  ingressRules:
  - fromPort: 5432
    ipProtocol: tcp
    toPort: 5432
    userIDGroupPairs:
    - groupID: redacted
  name: redacted
  vpcID: redacted
```

**Expected outcome**
I expected a security group to be created with the configured ingress rule.

**Environment**

* Kubernetes version 1.23
* Using EKS (yes/no), if so version?  yes
* AWS service targeted (S3, RDS, etc.) EC2
