### ISSUE TITLE
[dynamodb] allow specification of point-in-time recovery (PITR)

### ISSUE THREAD

**Issue by msvechla** [aws-controllers-k8s/community#1790]
Hello everyone,

I like the `DynamoDB` controller so far. One feature I'm missing is to be able to enable point-in-time recovery / continuous backups for a table.

It looks like this is available via the [UpdateContinuousBackup](https://github.com/aws/aws-sdk-go-v2/blob/service/dynamodb/v1.19.6/service/dynamodb/api_op_UpdateContinuousBackups.go#L25) function in the go sdk already.

Thanks & best regards!

**Comment by A-Hilaly** [comment]
Hi @msvechla ! Would like to work on this issue? happy to help implementing it, it should be fairly easy one to deal with and get familiar with ACK controllers development tools :)

**Comment by A-Hilaly** [comment]
@msvechla Awesome! please ping me on Kubernetes slack if I can help with anything!

**Comment by A-Hilaly** [comment]
Also this is a good place to start learning about generating new controller features https://aws-controllers-k8s.github.io/community/docs/contributor-docs/overview/

**Comment by A-Hilaly** [comment]
@msvechla are you still working on this? let us know if we can help with anything

**Comment by joaquinservetto** [comment]
Hi @msvechla @A-Hilaly, do you have any updates about this? we are also interested in this feature

**Comment by A-Hilaly** [comment]
I'll wait and see if @msvechla wants to still work on this. Other wise we'll reassign it to someone else.

**Comment by msvechla** [comment]
Hi, I might have some time to work on this today. I will let you know if I can not contribute, so someone else can take over.

**Comment by a-hilaly** [comment]
@msvechla Fix is available checkout https://github.com/aws-controllers-k8s/community/issues/1848#issuecomment-1642742008

**Comment by a-hilaly** [comment]
@msvechla @joaquinservetto  Dynamodb `v1.2.0` just got released with `ContinuousBackup` support - images and helm charts should be live soon.

Thanks a lot for your contributions @msvechla !! :pray:

**Comment by davidglia** [comment]
I was trying to enable PITR but it does not seem to recognise the field `continuousBackups`.

This is the manifest:
```
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: dynamodb-table
  namespace: k8s-controllers
spec:
  attributeDefinitions:
  - attributeName: Id
    attributeType: S
  billingMode: PAY_PER_REQUEST
  continuousBackups:
    pointInTimeRecoveryEnabled: true
  keySchema:
  - attributeName: Id
    keyType: HASH
  tableClass: STANDARD
  tableName: tableName
  timeToLive:
    attributeName: ExpiresAt
    enabled: true
```

Got this error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": 
error validating data: ValidationError(Table.spec): unknown field "continuousBackups" in 
aws.k8s.services.dynamodb.v1alpha1.Table.spec
```
