### ISSUE TITLE
Request to support Force Removal of Non-empty ECR repositories

### ISSUE THREAD

**Issue by Infra-Red** [aws-controllers-k8s/community#1798]
**Is your feature request related to a problem?**

ECR controller supports deleting an empty ECR repository, but doesn't support force deleting a non-empty ECR repository.

**Describe the solution you'd like**

Allow to modify `Force` field when deleting a ECR Repository resource.

https://github.com/aws/aws-sdk-go-v2/blob/ae835ecd4db83e5aff241520ec643afba522d704/service/ecr/api_op_DeleteRepository.go#L39

**Describe alternatives you've considered**
None.

**Comment by A-Hilaly** [comment]
Hello @Infra-Red - i don't think it makes sense to have a `forceDeletion` field in spec, however we could definetly change the default deletion path to always set force to True.

**Comment by Infra-Red** [comment]
@A-Hilaly thank you for quick response! Making force deletion default behavior also works 👍

**Comment by A-Hilaly** [comment]
Double thinking about this feature right now, maybe we should not change the behavior of the controller since it's already GA and some users might be relying on that feature. How about adding an annotation to set the deletion mode ? something like
```yaml
apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  name: $REPOSITORY_NAME
  annotations:
    ecr.services.k8s.aws/sdk-delete: force=true
spec:
  name: $REPOSITORY_NAME
```

Maybe we should leverage this/something similar for all controllers?
