### ISSUE TITLE
ACK Chart failing to Successfully Install Controllers

### ISSUE THREAD

**Issue by WahabEhsan** [aws-controllers-k8s/community#1800]
**Describe the bug**
Using the Ack chart, the controllers enabled are not starting up. Error stating no AWS_REGION found, even though the region is being passed in several ways. 

**Steps to reproduce**
Using the current values.yaml file in, https://github.com/aws-controllers-k8s/ack-chart/blob/main/values.yaml, 
install the controllers on to a cluster and check the status of the controllers in cluster. 

**Expected outcome**
Should be able to have successful running pods for controller for any service. 

**Environment**

* EKS Kubernetes version 1.25

**Comment by WahabEhsan** [comment]
Was able to fix the issue with removing the `-chart` from the values.yaml file for all services. It would be good idea to have that updated in the repository.

Now:
```
rds-chart:
  enabled: false
s3-chart:
  enabled: false
sagemaker-chart:
  enabled: false
sfn-chart:
  enabled: false
sns-chart:
  enabled: false
```

Recommended Solution:

```
rds:
  enabled: false
s3:
  enabled: false
sagemaker:
  enabled: false
sfn:
  enabled: false
sns:
  enabled: false
  ```
