### ISSUE TITLE
apigatewayv2-controller and HTTP headers management

### ISSUE THREAD

**Issue by Khuman2** [aws-controllers-k8s/community#1803]
Hello!

I try to manage my AWS HTTP API gateway and its resources by the controller. I got a confusion due to manipulation by the HTTP header.
I need to overwrite the header `Host: my.local.host`.
I use `Integration` manifest to manage it:
```yaml
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: integration-my
  namespace: rental-connect
spec:
  apiRef:
    from:
      name: adopt-api-gateway-my
  connectionID: id
  integrationType: HTTP_PROXY
  connectionType: VPC_LINK
  integrationURI: arn:aws:elasticloadbalancing:eu-central-1:...
  integrationMethod: ANY
  payloadFormatVersion: "1.0"
  requestParameters: <here I need help>
```
I suppose `requestParameters` can help me. But I have absolutely no idea in what format I can use it.
Any ideas?
