### ISSUE TITLE
EC2 controller, Security Group, reference by groupName is not working

### ISSUE THREAD

**Issue by elops** [aws-controllers-k8s/community#1807]
**Describe the bug**
Using EC2 ACK controller I create 2 security groups. e.g.
In next step I try to update groups and add some rules. I want one group to allow traffic from systems that have other group attached.
When specifying group by name e.g.
```
      userIDGroupPairs:
        - vpcID: vpc-XXX
          groupName: some-group-name
```
I get error in controller log that it was unable to find the group in the default VPC. 
```
2023-05-21T17:54:40.975Z	ERROR	controller.securitygroup	Reconciler error	{"reconciler group": "ec2.services.k8s.aws", "reconciler kind": "SecurityGroup", "name": "test-a", "namespace": "default", "error": "InvalidGroup.NotFound: The security group 'test-b' does not exist in default VPC 'vpc-ZZZ'\n\tstatus code: 400, request id: 83771ab8-2900-462b-acdb-dbd71883cd24"}
```

**Steps to reproduce**
Create 2 security groups where vpc-XXX is non default vpc!
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test-container
spec:
  description: Security Group for test-container
  name: test-container
  vpcID: vpc-XXX
  tags:
    - key: Name
      value: test-container
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test-rds
spec:
  description: Security Group for test-rds
  name: test-rds
  vpcID: vpc-XXX
  tags:
    - key: Name
      value: test-rds
```
Now try to add some rules that reference these groups
```
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test-container
spec:
  name: test-container
  description: Security Group for test-container
  vpcID: vpc-XXX
  ingressRules:
    - fromPort: 0
      toPort: 65535
      ipProtocol: tcp
      userIDGroupPairs:
        - vpcID: vpc-XXX
          groupName: test-rds
  tags:
    - key: Name
      value: test-container
```

**Expected outcome**
I expect that controller finds test-rds security group in the vpc specified by vpcID in the userIDGroupPairs block and not search the default VPC. Finally when it finds the group by name to update security group and add ingress rule that allows all tcp traffic from systems that have test-rds security group attached. 

**Environment**

* Kubernetes version
1.24

* Using EKS (yes/no), if so version? 
yes, 1.24

* AWS service targeted (S3, RDS, etc.)
