### ISSUE TITLE
AdoptedResource S3 is not working

### ISSUE THREAD

**Issue by masterkain** [aws-controllers-k8s/community#1808]
I did a lot of testing but apparently `AdoptedResource` for s3 is not working.

the generations here are incrementing I guess because I'm testing out different things but if there's a log mentioning that that bucket got adopted it is not shown.

`s3-controller:1.0.4`:

```
2023-05-23T17:17:42.147Z    INFO    adoption.adopted-reconciler    starting adoption reconciliation    {"target_group": "s3.services.k8s.aws", "target_kind": "Bucket", "namespace": "myns", "name": "mybucket", "generation": 2}
2023-05-23T17:18:06.888Z    INFO    adoption.adopted-reconciler    starting adoption reconciliation    {"target_group": "s3.services.k8s.aws", "target_kind": "Bucket", "namespace": "myns", "name": "mybucket", "generation": 3}
2023-05-23T17:19:10.404Z    INFO    adoption.adopted-reconciler    starting adoption reconciliation    {"target_group": "s3.services.k8s.aws", "target_kind": "Bucket", "namespace": "myns", "name": "mybucket", "generation": 4}
2023-05-23T17:20:57.203Z    INFO    adoption.adopted-reconciler    starting adoption reconciliation    {"target_group": "s3.services.k8s.aws", "target_kind": "Bucket", "namespace": "myns", "name": "mybucket", "generation": 5}
```

bucket status

```
Status:
  Ack Resource Metadata:
    Owner Account ID:  xxxxx
    Region:            eu-west-1
  Conditions:                   
    Last Transition Time:  2023-05-23T17:09:19Z
    Message:               Resource already exists
    Reason:                This resource already exists but is not managed by ACK. To bring the resource under ACK management, you should explicitly adopt the resource by creating a services.k8s.aws/AdoptedResource
    Status:                True
    Type:                  ACK.Terminal
    Last Transition Time:  2023-05-23T17:09:19Z
    Message:               Resource not synced
    Reason:                resource is in terminal condition
    Status:                False
    Type:                  ACK.ResourceSynced
```

```yaml
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: mybucket-adopted
spec:
  kubernetes:
    group: s3.services.k8s.aws
    kind: Bucket
    # tested also with metadata, no change
  aws:
    # tested also with nameOrID, no change
    arn: arn:aws:s3:::mybucket
```

```yaml
Name:         mybucket-adopted
Namespace:    myns
Labels:       kustomize.toolkit.fluxcd.io/name=apps
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  services.k8s.aws/v1alpha1
Kind:         AdoptedResource
Metadata:
  Creation Timestamp:  2023-03-15T11:19:26Z
  Finalizers:
    finalizers.services.k8s.aws/AdoptedResource
  Generation:  5
  Managed Fields:
    API Version:  services.k8s.aws/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:aws:
          f:arn:
        f:kubernetes:
          f:group:
          f:kind:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2023-05-23T17:20:57Z
    API Version:  services.k8s.aws/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.services.k8s.aws/AdoptedResource":
    Manager:      controller
    Operation:    Update
    Time:         2023-03-15T11:19:26Z
    API Version:  services.k8s.aws/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         controller
    Operation:       Update
    Subresource:     status
    Time:            2023-03-15T11:19:26Z
  Resource Version:  351351889
  UID:               0fd2bb2d-f9b2-463c-ac60-f99e9ac189ec
Spec:
  Aws:
    Arn:  arn:aws:s3:::mybucket
  Kubernetes:
    Group:  s3.services.k8s.aws
    Kind:   Bucket
Status:
  Conditions:
    Status:  True
    Type:    ACK.Adopted
Events:      <none>
```
