### ISSUE TITLE
Lambda `ValidationException` when setting `fileSystemConfigs`

### ISSUE THREAD

**Issue by christopher-wong** [aws-controllers-k8s/community#1820]
**Describe the bug**
When I try and deploy a Lambda with the ACK using the `fileSystemsConfigs` block, I get a status 400 `ValidationException`. Interestingly, the Lambda ACK spec doesn't appear to have a section to configure the File System access point, unlike the console - could this be part of the issue?

```
2023-06-09T15:38:03.222Z ERROR Reconciler error {"controller": "function", "controllerGroup": "lambda.services.k8s.aws", "controllerKind": "Function", "Function": {"name":"xxx","namespace":"ack-system"}, "namespace": "ack-system", "name": "xxx", "reconcileID": "xxx", "error": "ValidationException: \n\tstatus code: 400, request id: xxx"
```

**Steps to reproduce**
```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
...
  fileSystemConfigs:
  - arn: arn:aws:elasticfilesystem:us-west-2:1234567:file-system/fs-abc123
    localMountPath: /mnt/hf_models_cache
```

**Expected outcome**
I expect the Lambda ACK to allow me to configure EFS including the EFS arn, access point, and local mount point.

**Environment**

* Kubernetes version 1.24
* Using EKS (yes/no) yes
* AWS service targeted - Lambda
