### ISSUE TITLE
RDS controller requires namespace specification for password secret

### ISSUE THREAD

**Issue by interone-ms** [aws-controllers-k8s/community#1830]
**Describe the bug**
The RDS controller needs the namespace for the secret object explicitly specified.

If it is not given, an error appears in `kubectl describe dbinstance/foo`:
```
Status:
  Ack Resource Metadata:
    Owner Account ID:  xxx
    Region:            eu-central-1
  Conditions:
    Message:               kubernetes secret not found
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2023-06-16T11:59:16Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                kubernetes secret not found
    Status:                Unknown
    Type:                  ACK.ResourceSynced
```

**Steps to reproduce**
`kubectl apply` the following to a namespace not `default`:

```yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dbpw-xyz
data:
  admin: xxx

---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: db-xyz
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t2.micro
  dbInstanceIdentifier: db-xyz
  engine: mariadb
  engineVersion: "10.3"
  masterUsername: "admin"
  masterUserPassword:
    name: "dbpw-xyz"
    key: admin
```
**Expected outcome**
Expected the the database to be created without explicitly specifying the namespace in the yml file.

**Environment**

* Kubernetes version: v1.24.13-eks-0a21954
* Using EKS (yes/no), if so version? yes, see above for precise version
* AWS service targeted: RDS
