### ISSUE TITLE
Nodegroup - specify securitygroup to use

### ISSUE THREAD

**Issue by tomitesh** [aws-controllers-k8s/community#1836]
**Describe the bug**
A concise description of what the bug is.

1. We utilize the EKS controller to facilitate the provisioning of clusters, node groups, and addons. When defining a cluster, I have the capability to specify the desired security group to be used. However, I was hoping to have the same functionality available for node groups, where I can designate the security group to be utilized on the launch template created by the EKS controller (launch template is not provided as part of defination. please check example below). Is there any way to specify the security group during node group creation?

2. If not possible without a launch template, which controller provides the functionality to create a launch template?

**Steps to reproduce**

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  annotations:
    services.k8s.aws/deletion-policy: delete
  creationTimestamp: "2023-07-05T09:33:26Z"
  finalizers:
  - finalizers.eks.services.k8s.aws/Nodegroup
  generation: 3
  name: galaxy-nodegroup
  namespace: control
spec:
  amiType: AL2_x86_64
  capacityType: SPOT
  clusterName: galaxy
  diskSize: 20
  instanceTypes:
  - m4.xlarge
  - m5.xlarge
  - m5a.xlarge
  - m5d.xlarge
  - m5n.xlarge
  - m5dn.xlarge
  name: galaxy-nodegroup
  nodeRoleRef:
    from:
      name: galaxy-eks-worker
  releaseVersion: 1.25.9-20230607
  scalingConfig:
    desiredSize: 1
    maxSize: 1
    minSize: 1
  subnets:
  - subnet-123
  - subnet-456
  - subnet-789
  updateConfig:
    maxUnavailable: 1
  version: "1.25"
```

**Expected outcome**
A concise description of what you expected to happen.
when we try to create nodegroup without launchtemplate (above example), it should provide way to specify securitygroupid to use

**Environment**
dev

* Kubernetes version 1.25
* Using EKS (yes/no), if so version?  1.0.2
* AWS service targeted (S3, RDS, etc.) EKS

**Comment by A-Hilaly** [comment]
Hi @tomitesh - you can set a launch template by referencing one here https://github.com/aws-controllers-k8s/eks-controller/blob/main/apis/v1alpha1/nodegroup.go#L67-L70. To create one you'll probably have to do so using the ec2 api ( the ec2-controller doesn't support launch templates for now)

**Comment by tomitesh** [comment]
That's fine. Thanks for you time and quick response. Cheers.

**Comment by tomitesh** [comment]
@A-Hilaly I tried creating launch template using ec2 api. When i used LaunchTemplateid in nodegroup definations (exmple below), nodegroup shows creating status for 20mins and then fails with "NodeCreationFailure - Instances failed to join the kubernetes cluster".

```yaml
  launchTemplate:
    id: lt-12344567890
    version: "1"
```

Do i need to specify any specific lablels tags while creating launch template?

Kindly suggest.
