### ISSUE TITLE
[ElastiCache] Cannot enable snapshotting after creation

### ISSUE THREAD

**Issue by jdnurmi** [aws-controllers-k8s/community#1846]
**Describe the bug**
If a redis cluster is created without snapshotting, it cannot be enabled within the object

**Steps to reproduce**
```
spec:
  atRestEncryptionEnabled: false
  cacheNodeType: cache.t3.micro
  cacheSubnetGroupName: SGNAME
  description: Redis node for user-service
  engine: redis
  numNodeGroups: 1
  replicasPerNodeGroup: 0
  replicationGroupID: NAME
  securityGroupIDs:
  - SGID
  snapshotWindow: 01:00-02:00
  transitEncryptionEnabled: false
```

Add `snapshotRetentionLimit: 7`

Results in:
```
  - status: "True"
    type: ACK.ResourceSynced
  - message: "InvalidParameterCombination: Must specify both SnapshotRetentionLimit
      and SnapshottingClusterId to turn on snapshots\n\tstatus code: 400, request
      id: f46f7981-6bc2-4322-965c-82177694acdf"
    status: "True"
    type: ACK.Terminal
```

Presumably either we need to be able to specify SnapshottingClusterId  or it must be automatically calculated

**Expected outcome**

Snapshots enabled on the cluster.

**Environment**

* Kubernetes version? EKS, 1.28
* AWS service targeted? Elasticache
