### ISSUE TITLE
Support custom nested fields injection

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1850]
Currently the `code-generator` allow users to inject new custom fields to CRDs, e.g [`InlinePolicies`](https://github.com/aws-controllers-k8s/iam-controller/blob/main/generator.yaml#L71-L72) in the `iam-controller` . 

We typically using something like in the `generator.yaml` to instruct the code-generator to inject a new `ABC` field in `XYZ` resource spec.
```yaml
resources:
  XYZ:
    fields:
      ABC:
        type: string
```

However this feature doesn't work well when trying to inject fields in a nested struct in the Spec/Status of a CRD. For example:
```yaml
resources:
  XYZ:
    fields:
      A.B.C:
        type: string
```

`A.B.C` is supposed to inject a `C` field of type string in a new `B` struct in the top level field `A`. This is not currently the case and the code generator just transforms `A.B.C` to `ABC`.
We will need to extend the code generator to support inject custom nest fields into CRDs.

/assign @Vandita2020
