### ISSUE TITLE
Elasticache controller - make usage of SecurityGroup Ref.

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1860]
Good day!

I am extensively using Elasticache controller. Unfortunately, right now I need to create SG BEFORE creating the redis instance and getting the precise ID of security group by console means:

```yaml
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: redisapp
  namespace: infra-production
spec:
  cacheSubnetGroupName: cache-subnet
  transitEncryptionEnabled: false
  engine: redis
  description: redisapp
  replicationGroupID: redisapp
  cacheNodeType: cache.m6g.2xlarge
  securityGroupIDs:
    - sg-00f317b1a0953075c
```

I am kindly asking to add `securityGroups` field in `ec2.services.k8s.aws/v1alpha1` `Instance` or like `vpcSecurityGroupRefs` in `DBInstance` from `rds.services.k8s.aws/v1alpha`. This field will contain references to sg names instead of precise ids.
It will allow to remove some unnecessary manual steps.
