### ISSUE TITLE
Provide a good adoption procedure

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1862]
Yes. I have a preexisting amazon account with some resources like vpc. I want to make controllers reconciling this resource i.e. adopting it. Right now it is possible only with https://aws-controllers-k8s.github.io/community/docs/user-docs/adopted-resource/ procedure. And I don't like it.

For instance. I have a set of resources described in gitops repo like VPC, subnets etc. Then there may be two cases:
1. the control cluster with all manifests and ack controllers instances was lost. I want to create a new one, connect it to gitops repo and I am expecting that all resources will be synced. Unfortunately, all controllers will give the error, that the resources already exists.
2. I have already precreated environment and I want to move all resources to gitops repo.

If automatically adopting is not desired, it could be good idea to agree that it's behaviour can be changed by some kind of annotation like:

```yaml
# if it is already created - it won't be adopted
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  name: production
  namespace: infra-production
spec:
  cidrBlocks:
    - 10.3.0.0/16
  enableDNSSupport: true
  enableDNSHostnames: true
  tags:
    - key: Name
      value: production
```

```yaml
# if it is already created - it will be adopted, the controller will populate status field from the Amazon account
# and all further changes will be controlled in gitops way
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  annotations:
    services.k8s.aws/adoption: true
  name: production
  namespace: infra-production
...
```
