### ISSUE TITLE
Discrepancy between different resources.

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1866]
**Describe the bug**

It is very difficult to maintain infra code because different keys with the same name in different resources. The example is below.
If I want to create an EC2 instance with some tag, I write something like this:

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: test
  namespace: infra-production
spec:
...
  tags:
    - key: Name
      value: mg-main-a
    - key: env
      value: production
```

but for KMS it will look like:

```yaml
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Key
metadata:
  name: rds-dbserver
  namespace: infra-production
spec:
  description: "Key for rds-dbserver"
  enableKeyRotation: true
  tags:
    - tagKey: Name
      tagValue: rds-dbserver
    - tagKey: env
      tagValue: production
```

**Steps to reproduce**

**Expected outcome**

tags in `kind: Key` must use the same schema for `tags:` with key name under `key` and value under `value` 

The same must apply to all controllers and all APIs.
