### ISSUE TITLE
SNS Topics fail to reconcile due to empty policy field

### ISSUE THREAD

**Issue by jessebye** [aws-controllers-k8s/community#1867]
**Describe the bug**
SNS topics enter a failed state with an error that the policy field is invalid (empty). It seems like the controller is passing an empty field in the SDK request, causing this error. If the field was omitted altogether I think the error wouldn't happen.

**Steps to reproduce**

Create an SNS topic like this:
```
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Topic
metadata:
  name: services-api-checkin-sent-event
  namespace: services
spec:
  displayName: services/api - checkin-sent-event
  kmsMasterKeyID: alias/aws/sns
  name: services-api-checkin-sent-event
```
Observe the error in the status field:
```
InvalidParameter: Invalid parameter: Policy is empty\n\tstatus code: 400
```

**Expected outcome**
The topic is reconciled correctly and there is no error.

**Environment**

* Kubernetes version 1.27
* Using EKS (yes/no), if so version? yes - 1.27
* AWS service targeted (S3, RDS, etc.) SNS
