### ISSUE TITLE
S3 controller - cryptic error message

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1872]
Hi!

When I am creating bucket like:

```yaml
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: test-rec
spec:
  name: test-rec
  logging:
    loggingEnabled:
      targetBucket: "test-rec-access"
      targetPrefix: "test-"
  objectLockEnabledForBucket: true
```

I am getting the next cryptic error message in controller:

```
  conditions:
    - message: "Error syncing property 'Versioningc': InvalidBucketState: An Object Lock configuration is present on this bucket, so the versioning state cannot be changed.\n\tstatus code: 409, request id: CEPWE7F806XMFF57, host id: o7n5o/9dqirQcSILbyRpbUBkknyZPIX//Io9SG9bdqaCzl+k8S/9aG0y8B3pp7Iuobdc7VMaD/s="
      status: 'True'
      type: ACK.Recoverable
    - lastTransitionTime: '2023-08-09T09:18:37Z'
      message: >-
        Unable to determine if desired resource state matches latest observed
        state
      reason: "Error syncing property 'Versioningc': InvalidBucketState: An Object Lock configuration is present on this bucket, so the versioning state cannot be changed.\n\tstatus code: 409, request id: CEPWE7F806XMFF57, host id: o7n5o/9dqirQcSILbyRpbUBkknyZPIX//Io9SG9bdqaCzl+k8S/9aG0y8B3pp7Iuobdc7VMaD/s="
      status: Unknown
      type: ACK.ResourceSynced
```
and bucket never goes to `ACK.ResourceSynced` state

Desired behaviour:

1. correct error message, I think there is no property like `Versioningc`
2. If there are default settings - make them explicit
3. don't throw error as `objectLockEnabledForBucket` already suppose some versioning config. Otherwise - implement admission that will force compliant settings between different keys.
