### ISSUE TITLE
EKS controller does not update node group

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1874]
**Describe the bug**

I am trying to change the settings of NodeGroup. Particularly I suddenly understood that I create nodes with very small disks (default 20GiB) and I want to simultaneously upgrade them to latest version of image.
I tried to change from
```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng
  namespace: infra-production
spec:
  name: production-main-ng
  clusterName: production
  subnetRefs:
  - from:
      name: production-private-eu-west-2a
  - from:
      name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::966321756598:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 10
    maxSize: 10
    desiredSize: 10
  instanceTypes:
    - m5.4xlarge
```
to
```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng
  namespace: infra-production
spec:
  name: production-main-ng
  clusterName: production
  diskSize: 50
  subnetRefs:
  - from:
      name: production-private-eu-west-2a
  - from:
      name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::966321756598:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 10
    maxSize: 10
    desiredSize: 10
  instanceTypes:
    - m5.4xlarge
  releaseVersion: 1.27.3-20230728
```

But I don't see any changes in Amazon WebUI. The release version is still old and disk size is not changed.

What is interesting - if I made manual changes through Amazon Console to scaling config, the controller reverts it back after some time. So it means that the reconciliation is working.

**Expected outcome**

either
1. the changes to fields like `releaseVersion` and `diskSize` are forbidden (because they are immutable?), so the updated YAML could not be applied (via admission controller?)
or
2. write a particular status that this change could not be synced in Status field of k8s object
or
3. apply all changes in some sequence to target node group leveraging the operator pattern and achieving the desired state described by `Nodegroup` object.

**Environment**

* Kubernetes version 1.27
* Using EKS (yes/no), if so version?  yes
* AWS service targeted (S3, RDS, etc.) EKS controller
