### ISSUE TITLE
KMS controller - can't create an alias

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1878]
**Describe the bug**

I want to create an alias for the key managed by ACK but it is impossible

**Steps to reproduce**

Create a KMS key with manifest like:

```yaml
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Key
metadata:
  name: rds-dbserver-8
  namespace: infra-production
spec:
  description: "Key for rds-dbserver-8"
  enableKeyRotation: true
  tags:
    - tagKey: Name
      tagValue: rds-dbserver-8
    - tagKey: env
      tagValue: production
```

Then apply manifest for the alias:

```yaml
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Alias
metadata:
  name: alias-rds-dbserver-8
  namespace: infra-production
spec:
  name: alias-rds-dbserver-8
  targetKeyRef:
    from:
      name: rds-dbserver-8
```

The alias is not created:

```
status:
  ackResourceMetadata:
    ownerAccountID: '966321756598'
    region: eu-west-2
  conditions:
    - lastTransitionTime: '2023-08-22T13:41:53Z'
      status: 'True'
      type: ACK.ReferencesResolved
    - message: "ValidationException: Alias must start with the prefix \"alias/\". Please see https://docs.aws.amazon.com/kms/latest/developerguide/kms-alias.html\n\tstatus code: 400, request id: 87750736-3cec-4256-99c7-3c41d7140492"
      status: 'True'
      type: ACK.Terminal
    - lastTransitionTime: '2023-08-22T13:41:53Z'
      message: Resource not synced
      reason: resource is in terminal condition
      status: 'False'
      type: ACK.ResourceSynced
```

**Expected outcome**

Alias is created within the appropriate key

**Comment by gecube** [comment]
Finally it worked with the next manifest

```yaml
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Alias
metadata:
  name: rds-dbserver-8
  namespace: infra-production
spec:
  name: alias/rds-dbserver-8
  targetKeyRef:
    from:
      name: rds-dbserver-8
```

But it was a little bit ambiguous, as from the Amazon Web UI there is no necessity to add alias/ prefix...
Probably the "alias/" prefix could be added programmatically or Alias object can be protected by admission controller to disallow creation of improper objects (just refuse to create an Alias without alias/ on k8s level)
