### ISSUE TITLE
EC2 controlle - FlowLog substitute VPC Ref Id

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1897]
Good day!

I am playing around with FlowLog object and found that I need to precisely know the RoleID and VpcID before the creation of FlowLog:

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: FlowLog
metadata:
  name: vpc-production-flow-log
  namespace: infra-production
spec:
  resourceID: vpc-04fe286b0d4fe8ccc
  resourceType: VPC
  logDestinationType: cloud-watch-logs
  logGroupName: vpc-flow-logs
  trafficType: ALL
  deliverLogsPermissionARN: arn:aws:iam::966321756598:role/vpcflow-cloudwatch-role
  tags:
    - key: Name
      value: vpc-production-flow-log
    - key: env
      value: production
```

The standard way of referencing different objects in ACK framework is using of something like:

```yaml
vpcRef: 
  from: 
    name: string
```
or 
```yaml
roleRef: 
  from: 
    name: string
```

I am kindly asking to leverage the same approach to `FlowLog`, or otherwise propose some better alternative. The mechanism like `FieldExport` in case of support a generic k8s object like a target could be good option. Right now it works only with Secrets and/or Configmaps according to the [documentation](https://aws-controllers-k8s.github.io/community/docs/user-docs/field-export/).

Other option could be usage of some FluxCD features (no idea what will be the suitable one).
