### ISSUE TITLE
ACM Certificate + Route53 dns validation example / tutorial

### ISSUE THREAD

**Issue by ecerulm** [aws-controllers-k8s/community#1904]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/docs/community/overview/ 

**Which section(s) is the issue in?**

Tutorials 

**What needs fixing?**

A basic example on how to use the `acm-controller` should be provided. 

Like creating a `acm.services.k8s.aws/Certificate` and how to use it together with `aws-load-balancer-controller` .  In particular it would be great to include the DNS validation as well, 

**Additional context**

I googled and  can't find any example of the `acm-controller`. 

So I think now my only options is to manually inspect the CRDs in `acm-controller` 
* [Certificate](https://github.com/aws-controllers-k8s/acm-controller/blob/main/config/crd/bases/acm.services.k8s.aws_certificates.yaml) 

And then trying to guess how to use it, specially how to the DNS validation will be implemented.

**Comment by indrekj** [comment]
I also didn't find any examples, so here's one:
```
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: mydomain
spec:
  domainName: "mydomain.com"
  subjectAlternativeNames:
    - "*.mydomain.com"
```

This creates a certificate with two records. But I have no idea how to automate the route 53 verification, or if it is even possible atm.

**Comment by peak-stephen** [comment]
After skimming the code in https://github.com/aws-controllers-k8s/acm-controller/blob/v0.0.9/pkg/resource/certificate/sdk.go I don't think this resource controller is actually capable of verifying the certificates it requests. In order to do so it would need to also use the API of Route53 (or some other DNS provider) and at the moment it only uses the ACM API.

This was previously discussed [here](https://github.com/aws-controllers-k8s/community/issues/482#issuecomment-1511067399) where @jaypipes said it's not planned, as there is/was also a route53 controller in the works.

**Comment by john-r-swyftx** [comment]
I can create a certificate with:
```
apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: "mydomain"
spec:
  domainName: "mydomain.com"
```

and using the [route53-controller](https://github.com/aws-controllers-k8s/route53-controller), add the cname resource record for validation.
```
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: "mydomain-validation"
spec:
  hostedZoneID:<hosted-zone-id>
  recordType: CNAME
  name: <ResourceRecord.name>
  resourceRecords:
    - value: <ResourceRecord.value>
  ttl: 300
```

but I can't figure out how to fully automate this. Are there examples on how to do this?
