### ISSUE TITLE
Need a convenient way to reconcile resource

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1905]
Hello!

Right now I have the next issue. I have a bunch of resources like VPC, Subnets, RouteTables. The dependency between resources are expressed with vpcRef, subnetRef etc. and other type of references. So the pipeline looks like this: apply all resources in a bunch and wait till the controller(s) will reconcile them. Unfortunately, it could take as much as 1h for the whole reconciliation. Particularly - if you are hit by limits of Amazon cloud (like exceeding quota on some of resources). So then you are writing ticket to Amazon with the request to increase quota.... and wait.... wait.... wait... till the controller(s) will reconcile. 

So I am looking for some way to explain to controller(s) that resources must be reconciled right now. Probably the decrease of interval also could help, but I don't want to overload amazon api with a bunch of requests. Also I wonder if controller(s) are really watching all changes in Status fields of relevant objects.

**Comment by a-hilaly** [comment]
Hello @gecube !

[It is possible to tweak](https://github.com/aws-controllers-k8s/s3-controller/blob/main/helm/values.yaml#L123-L128) the default reconciliation period for all the resources and for specific resources using something like:

```yaml
# in the helm chart values.yaml
reconcile:
  defaultResyncPeriod: 36000 # 10 Hours
  resourceResyncPeriods:
    bucket: 18000 # override the default value for a specific resource
```

More docs here: https://aws-controllers-k8s.github.io/community/docs/user-docs/drift-recovery/
