### ISSUE TITLE
Creating an S3 Bucket lifecycle policy requires an optional argument

### ISSUE THREAD

**Issue by rigaspapas** [aws-controllers-k8s/community#1909]
**Describe the bug**
As suggested by the documentation [here](https://aws-controllers-k8s.github.io/community/reference/s3/v1alpha1/bucket/), `lifecycle.rules.[].filter` and `lifecycle.rules.[].filter.prefix` are optional parameters, but in practice, they are not. To match all the files we added a prefix and set it to the empty string. When omitted, we got the following error:
```
Error syncing property 'Lifecycle': MalformedXML: The XML you provided was not well-formed or did not validate against our published schema status code: 400, request id: ...
```

**Steps to reproduce**

Create a bucket like this:
```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: foo
  annotations:
    services.k8s.aws/deletion-policy: delete
spec:
  acl: private
  encryption:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
        bucketKeyEnabled: true
  name: foo
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true
    ignorePublicACLs: true
    restrictPublicBuckets: true
  versioning:
    status: Enabled
  lifecycle:
    rules:
      - id: "expire_old_files"
        expiration:
          days: 5
        status: "Enabled"
```

**Expected outcome**

The bucket should be created.

**Environment**

EKS version: `1.25`
Controller: `public.ecr.aws/aws-controllers-k8s/s3-controller:1.0.4`

**Comment by oliverjfletcher** [comment]
I had the same issue @rigaspapas, from what I understand from the docs this is expected behavior as the [Rule data type](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Rule.html) for the S3 API requires a Prefix for the Lifecycle rule. Though, it can be removed if a tag is used instead of a prefix. One of the two is required though. 

_"Bucket lifecycle configuration now supports specifying a lifecycle rule using an object key name prefix, one or more object tags, or a combination of both. Accordingly, this section describes the latest API. The previous version of the API supported filtering based only on an object key name prefix, which is supported for backward compatibility. For the related API description,_ see: [PutBucketLifecycle](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycle.html)

I agree it's not a great user experience, and maybe something @a-hilaly can raise internally to have the API respond with a better message.

@a-hilaly as the controller docs aren't aligned with the API docs, happy to update. But, let me know, thanks!

### Manifest using `prefix`

```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: foo
  annotations:
    services.k8s.aws/deletion-policy: delete
spec:
  acl: private
  encryption:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
        bucketKeyEnabled: true
  name: foo
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true
    ignorePublicACLs: true
    restrictPublicBuckets: true
  versioning:
    status: Enabled
  lifecycle:
    rules:
      prefix: "/"
      expiration:
        days: 5
      status: "Enabled"
```

### Manifest using `tag`

```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: foo
  annotations:
    services.k8s.aws/deletion-policy: delete
spec:
  acl: private
  encryption:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
        bucketKeyEnabled: true
  name: foo
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true
    ignorePublicACLs: true
    restrictPublicBuckets: true
  versioning:
    status: Enabled
  lifecycle:
    rules:
      # prefix: "/"
      filter:
        tag:
          key: key
          value: value
      expiration:
        days: 5
      status: "Enabled"
```
