### ISSUE TITLE
Cannot install the ec2 controller helm chart with secret credentials

### ISSUE THREAD

**Issue by alanreji** [aws-controllers-k8s/community#1913]
**Describe the bug**
I am trying to install the ec2 controller by overriding the "credentials" from values.yaml of the ec2-chart. But I am receiving this error.

`Error: INSTALLATION FAILED: YAML parse error on ec2-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 106: mapping values are not allowed in this context`

When I took a look at the deployment template in debug mode, I get this.

```yaml
# Source: ec2-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-chart
  namespace: default
  labels:
    app.kubernetes.io/name: ec2-chart
    app.kubernetes.io/instance: ec2-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "1.0.7"
    k8s-app: ec2-chart
    helm.sh/chart: ec2-chart-1.0.7
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ec2-chart
      app.kubernetes.io/instance: ec2-chart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ec2-chart
        app.kubernetes.io/instance: ec2-chart
        app.kubernetes.io/managed-by: Helm
        k8s-app: ec2-chart
    spec:
      serviceAccountName: ack-ec2-controller
      containers:
      - command:
        - ./bin/controller
        args:
        - --aws-region
        - "$(AWS_REGION)"
        - --aws-endpoint-url
        - "$(AWS_ENDPOINT_URL)"
        - --log-level
        - "$(ACK_LOG_LEVEL)"
        - --resource-tags
        - "$(ACK_RESOURCE_TAGS)"
        - --watch-namespace
        - "$(ACK_WATCH_NAMESPACE)"
        - --deletion-policy
        - "$(DELETION_POLICY)"
        - --reconcile-default-resync-seconds
        - "$(RECONCILE_DEFAULT_RESYNC_SECONDS)"
        image: public.ecr.aws/aws-controllers-k8s/ec2-controller:1.0.7
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
        - name: ACK_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          value: eu-central-1
        - name: AWS_ENDPOINT_URL
          value: ""
        - name: ACK_WATCH_NAMESPACE
          value: 
        - name: DELETION_POLICY
          value: delete
        - name: LEADER_ELECTION_NAMESPACE
          value: ""
        - name: ACK_LOG_LEVEL
          value: "info"
        - name: ACK_RESOURCE_TAGS
          value: "services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%,services.k8s.aws/namespace=%K8S_NAMESPACE%"
        - name: RECONCILE_DEFAULT_RESYNC_SECONDS
          value: "36000"
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /var/run/secrets/aws/credentials
        - name: AWS_PROFILE
          value: default
        volumeMounts:
          - name: aws-creds
            mountPath: /var/run/secrets/aws
            readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      nodeSelector: 
        kubernetes.io/os: linux
      hostIPC: false
      hostPID: false
      hostNetwork: false
      dnsPolicy: ClusterFirst
      volumes:- name: aws-creds
          secret:
            secretName: aws-creds
```

I think the volumes part is given in wrong YAML syntax

**Steps to reproduce**
1. Create secrets using AWS credentials
`kubectl create secret generic aws-creds --from-file=credentials=files/aws-credentials`
2. Install ec2-controller helm chart
`helm install ec2-chart charts/ec2-chart-1.0.7.tgz --set aws.region=eu-central-1,aws.credentials.secretName=aws-creds,aws.credentials.secretKey=credentials,aws.credentials.profile=default`

**Expected outcome**
I want it to install the ec2-controller and the CRDs as normal.

**Environment**
Minikube running on Macos Apple Silicon

* Kubernetes version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4
* Using EKS (yes/no), if so version?  no
* AWS service targeted (S3, RDS, etc.) EC2
