### ISSUE TITLE
SecurityGroup incorrectly reports "InvalidGroup.Duplicate: The security group already exists for VPC"

### ISSUE THREAD

**Issue by mattzech** [aws-controllers-k8s/community#1930]
**Describe the bug**
Trying to create a security group with 2 basic ingress rules and 1 egress rule fails with incorrect error code. Have checked and there are no other securitygroups with this name. Seems to be similar to [this issue](https://github.com/aws-controllers-k8s/community/issues/1783)

**Steps to reproduce**
Create a security group with this config:
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: sg-test
  namespace: netgen-test
spec:
  description: Test
  egressRules:
  - fromPort: 0
    toPort: 0
    ipProtocol: "-1"
    ipRanges:
    - cidrIP: 0.0.0.0/0
      description: Allow traffic from all IPs
  ingressRules:
  - fromPort: 80
    toPort: 80
    ipProtocol: tcp
    ipRanges:
    - description: Test HTTP
  - fromPort: 443
    toPort: 443
    ipProtocol: tcp
    ipRanges:
    - description: Test HTTPS
  name: netgen-sg-test-2
  vpcID: vpc-03b59d234a31a79c7
```

**Expected outcome**
Successful Create

**Environment**
Openshift 4.13.12 running on AWS

* Kubernetes version 1.26
* Using EKS (yes/no), if so version? No
* AWS service targeted (S3, RDS, etc.) EC2
