### ISSUE TITLE
RouteTable update using vpcEndpointID results in CR spec getting converted from vpcEndpointID to GatewayID

### ISSUE THREAD

**Issue by nnbu** [aws-controllers-k8s/community#1935]
**Describe the bug**
Steps mentioned below describe the issue

**Steps to reproduce**
1. Create RouteTable CR without any routes 
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  name: rt1
spec:
  vpcID: vpc-03fab91f7a1866946
```

2. Add routes to the CR which has `vpcEndpointID` and apply the CR again
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  labels:
    app.kubernetes.io/created-by: cluster-api-provider-aws-ack
    app.kubernetes.io/part-of: cluster-api-provider-aws-ack
    cluster-name: prad-e2e-test
  name: rt1
spec:
  routes:
  - destinationCIDRBlock: 192.168.16.0/26
     vpcEndpointID: vpce-0d16fc08e2473fc4b
  vpcID: vpc-03fab91f7a1866946
```

3. After this, CR spec changes and `vpcEndpointID` gets removed and `gatewayID` gets added to the CR. Value of `gatewayID` remains same as `vpcEndpointID`

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  labels:
    app.kubernetes.io/created-by: cluster-api-provider-aws-ack
    app.kubernetes.io/part-of: cluster-api-provider-aws-ack
    cluster-name: prad-e2e-test
  name: rt1
spec:
  routes:
  - destinationCIDRBlock: 192.168.16.0/26
     gatewayID: vpce-0d16fc08e2473fc4b
  vpcID: vpc-03fab91f7a1866946
```

**Expected outcome**
CR spec should remain unchanged

**Environment**

* Kubernetes version
1.26

* Using EKS (yes/no), if so version? 
Seen with and without EKS

* AWS service targeted (S3, RDS, etc.)
EC2 controller
