### ISSUE TITLE
RDS stale value on `DBInstance` updating `dbParameterGroups` `parameterApplyStatus`

### ISSUE THREAD

**Issue by dweebo** [aws-controllers-k8s/community#1945]
**Describe the bug**
Sometimes our `DBInstance` instance have a stale value in `status.dbParameterGroups.parameterApplyStatus`.  

I'm not sure but it seems like the rds operator stops reconciling the `DBInstance` resource once it thinks it is "available".  I stop seeing logs for the instances that I see with this issue.

**Steps to reproduce**
Create a `DBInstance` from snapshot (`dbSnapshotIdentifier`) and with a custom `dbParameterGroupName`.
Wait for RDS instance to be available and for the db parameter group to be set/applied.
Check the `DBInstance.status.dbParameterGroups.parameterApplyStatus`.  3 out of 10 times in my testing the value was not updated on the `DBInstance` custom resources, even after waiting for an hour after the RDS instances were fully running.

**Expected outcome**
I expect the RDS operator to keep reconciling until after the db parameter group is applied and the value is set to `in-sync`.

**Environment**

* Kubernetes version
1.25

* Using EKS (yes/no), if so version? 
No

* AWS service targeted (S3, RDS, etc.)
RDS

**Comment by dweebo** [comment]
Might be related but on occasion I also see my `DbInstance` get stuck in `pending-reboot`.
```
status:
...
  dbInstanceStatus: available
  conditions:
    - lastTransitionTime: '2023-11-29T15:10:53Z'
      message: Late initialization successful
      reason: Late initialization successful
      status: 'True'
      type: ACK.LateInitialized
    - lastTransitionTime: '2023-11-29T15:10:53Z'
      message: Resource synced successfully
      reason: ''
      status: 'True'
      type: ACK.ResourceSynced
...
  dbParameterGroups:
    - dbParameterGroupName: foo
      parameterApplyStatus: pending-reboot
```

The operator is no longer-reconciling and the RDS instance doesn't reboot automatically.  I have to manually reboot it OR I can hack it by adding a new tag on the `DBInstance` which causes a new reconciliation.
