### ISSUE TITLE
Function creation fails with Lambda ACK Controller. 

### ISSUE THREAD

**Issue by grv180290** [aws-controllers-k8s/community#1948]
**Describe the bug**
I want to create a function using the below manifest. The function fails to create with a TLS handshake timeout to the STS endpoint. 

**Steps to reproduce**
 In my EKS/VPC setup, we don't allow access to STS global endpoint. Access is only allowed to the regional STS endpoint via a VPC endpoint and hence the function creation fails. However there seems to be no obvious way to force the controller to use regional STS endpoint when creating a function. 

This is my function manifest 

```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: K8s-querier
 annotations:
   services.k8s.aws/region: us-east-1
spec:
 name: k8s-lambda
 code:
   s3Bucket: my-bucket-name
   s3Key: lambda-deployment.zip
 role: "arn:aws:iam::AWS_ACCOUNTID:role/lambda-basic-role"
 runtime: python3.11
 handler: k8s-pods-list.lambda_handler
 description: function created by ACK lambda-controller to test K8s APIs

```

kubectl describe function o/p [ Other fields omitted]
```
Status:
  Ack Resource Metadata:
    Owner Account ID:  **********
    Region:            us-east-1
  Conditions:
    Message:  WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": net/http: TLS handshake timeout
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2023-11-29T20:55:59Z
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": net/http: TLS handshake timeout
    Status:  Unknown
    Type:    ACK.ResourceSynced
Events:      <none>

```

When installing the lambda controller using the community helm, I ran into the same issue and my controller pods won't come up. 
Looking at the code [here](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/config/config.go#L47C40-L47C65), I modified the community Helm chart with the below contents in deployment.yaml and  values file pointing to my regional STS endpoint  and my controller came up. 

Deployment.yaml [ Abridged] 
```
spec:
  containers:
  -  command:
     - ./bin/controller
     args:
     - --aws-identity-endpoint-url
     -  "$(AWS_IDENTITY_ENDPOINT_URL)"
    env:
    - name: AWS_IDENTITY_ENDPOINT_URL
      value: {{ .Values.aws.identity_endpoint_url | quote }}
```
 
 Values.yaml 
 ```
aws:
  # If specified, use the AWS region for AWS API calls
  region: "us-east-1"
  endpoint_url: ""
  identity_endpoint_url: "sts.us-east-1.amazonaws.com"
```

On similar lines, I tried using the below manifest, passing identity_endpoint_url as an environment variable to my function manifest, but it seems like the controller is still for some reason pointing to STS global endpoint as indicated in the kubectl describe function output. 

```
sh-4.2$ cat my-function-s3.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: k8s-querier
 annotations:
   services.k8s.aws/region: us-east-1
spec:
 name: k8s-lambda
 code:
   s3Bucket: MY_BUCKET_NAME
   s3Key: lambda-deployment.zip
 role: "arn:aws:iam::***********:role/lambda-basic-role"
 runtime: python3.11
 environment:
   variables:
     AWS_IDENTITY_ENDPOINT_URL: "sts.us-east-1.amazonaws.com"
 handler: k8s-pods-list.lambda_handler
 description: function created by ACK lambda-controller to test K8s APIs
```

 
**Expected outcome** 
How do I force the lambda function creation to use the regional STS endpoint? 

**Environment**
Dev 

* Kubernetes version 1.28
* Using EKS (yes/no), if so version?  Yes , 1.28
* AWS service targeted (S3, RDS, etc.) AWS Lambda
