### ISSUE TITLE
ec2: networkAcl update fails if ruleAction field has camelcase `Allow`/`Deny`

### ISSUE THREAD

**Issue by nnbu** [aws-controllers-k8s/community#1966]
**Steps to reproduce**
Repro steps:

1. Create CR (Make sure `ruleAction` field has camelcase `Allow`/`Deny`)
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: NetworkACL
metadata:
  name: netacl1
  namespace: default
spec:
  associations:
  - subnetID: subnet-xxxxx1
  - subnetID: subnet-xxxxx2
  entries:
  - cidrBlock: 0.0.0.0/0
    egress: false
    protocol: "-1"
    ruleAction: Allow
    ruleNumber: 100
  vpcID: vpc-xxxx
```

2. Update the CR with following
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: NetworkACL
metadata:
  name: netacl1
  namespace: default
spec:
  associations:
  - subnetID: subnet-xxxxx1
  - subnetID: subnet-xxxxx2
  entries:
  - cidrBlock: 0.0.0.0/0
    egress: false
    protocol: "-1"
    ruleAction: Allow
    ruleNumber: 100
  - cidrBlock: 0.0.0.0/0
    egress: true
    protocol: "-1"
    ruleAction: Allow
    ruleNumber: 100
  vpcID: vpc-0xxxx
```

3. CR update cause the entry present in first steps to get deleted and ec2 logs show following error

```
reason: "InvalidNetworkAclEntry.NotFound: no ingress entry with number 100 in
      network ACL acl-xxxx\n\tstatus code: 400, request id: xxxxxxx"
```

**Expected outcome**
Update should be successful and we should see both entries (egress and ingress) in aws console

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version?  No
* AWS service targeted (S3, RDS, etc.)
