### ISSUE TITLE
Function updates (description, env vars) are not applied if the ImageURI also changed in an update

### ISSUE THREAD

**Issue by aszmyd** [aws-controllers-k8s/community#1968]
**Describe the bug**
Updating other things than ImageURI in one update makes only the ImageURI to be updated. Other changes (like description, env variables) are not updated.

**Steps to reproduce**
1. Make a function using ACK based on Docker image with some description
2. Change the Docker ImageURI and description and trigger the update with ACK

**Expected outcome**
All changes made to the function gets eventually applied to the AWS Lambda function

**Actual outcome**
The ImageURI is properly updated in the function but other parts of the update are not.

**Environment**

* Kubernetes version **1.28**
* Using EKS (yes/no), if so version? yes - **eks.5**
* AWS service targeted (S3, RDS, etc.) - **AWS Lambda**

**Additional notes**

Initial function:
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: "adamtest1"
  annotations:
    services.k8s.aws/region: "us-east-1"
spec:
  name: "adamtest1"
  role: "arn:aws:iam::123:role/k8s/dev/k8s-dev-LambdaManagement"
  packageType: Image
  code:
    imageURI:  "123.dkr.ecr.us-east-1.amazonaws.com/registry:105"
  imageConfig:
    command: 
      - "co.example.Lambda::handle"
  description: "Test function v105"
```

Function update:
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: "adamtest1"
  annotations:
    services.k8s.aws/region: "us-east-1"
spec:
  name: "adamtest1"
  role: "arn:aws:iam::123:role/k8s/dev/k8s-dev-LambdaManagement"
  packageType: Image
  code:
    imageURI:  "123.dkr.ecr.us-east-1.amazonaws.com/registry:106"
  imageConfig:
    command: 
      - "co.example.Lambda::handle"
  description: "Test function v106"
```

ACK Logs:
```
ack-lambda-controller-lambda-chart-7b47cc5647-4ftdl controller {"level":"info","ts":"2023-12-20T08:33:31.179Z","logger":"ackrt","msg":"created new resource","account":"123","role":"","region":"us-east-1","kind":"Function","namespace":"default","name":"adamtest1","is_adopted":false,"generation":6}
ack-lambda-controller-lambda-chart-7b47cc5647-4ftdl controller {"level":"info","ts":"2023-12-20T08:34:20.513Z","logger":"ackrt","msg":"desired resource state has changed","account":"123","role":"","region":"us-east-1","kind":"Function","namespace":"default","name":"adamtest1","is_adopted":false,"generation":7,"diff":[{"Path":{"Parts":["Spec","Code","ImageURI"]},"A":"879130378853.dkr.ecr.us-east-1.amazonaws.com/registry:106","B":"123.dkr.ecr.us-east-1.amazonaws.com/registry:105"},{"Path":{"Parts":["Spec","Description"]},"A":"Test function v106","B":"Test function v105"}]}
ack-lambda-controller-lambda-chart-7b47cc5647-4ftdl controller {"level":"info","ts":"2023-12-20T08:34:21.227Z","logger":"ackrt","msg":"updated resource","account":"123","role":"","region":"us-east-1","kind":"Function","namespace":"default","name":"adamtest1","is_adopted":false,"generation":7}
```

An interesting and potentially related part is that when image gets updated, lambda function goes into some "update pending" state (when you go to it just after the update, you can see the blue bar saying that):

![Screenshot 2023-12-20 at 09 34 29](https://github.com/aws-controllers-k8s/community/assets/3050805/f1436c6e-915a-4e66-a5f5-73ae50eda394)

This suggests that maybe the bulk updates (with image + other things) are not working because maybe AWS does not allow for updates while it's in pending state (because of the image state?)
