### ISSUE TITLE
Changing .Spec.Name on a Cloudwatch.MetricAlarm does not delete the old alarm

### ISSUE THREAD

**Issue by jose-fully-ported** [aws-controllers-k8s/community#1980]
**Describe the bug**

When updating a field that results in a new Cloudwatch MetricAlarm - such as the Name - the new alarm is created, but the old one is not deleted. 

**Steps to reproduce**

Run `kubectl apply -f metric-alarm.yaml` against the following resource

```yaml
---
apiVersion: cloudwatch.services.k8s.aws/v1alpha1
kind: MetricAlarm
metadata:
  name: cpu-alarm
  annotations:
    services.k8s.aws/region: us-east-1
spec:
  actionsEnabled: true
  alarmActions:
  - arn:aws:sns:us-east-1:1234567890:fake
  alarmDescription: |-
    Some alarm

    See Graphs for more details.
  comparisonOperator: GreaterThanOrEqualToThreshold
  datapointsToAlarm: 1
  dimensions:
  - name: AutoScalingGroupName
    value: fake
  evaluationPeriods: 1
  metricName: CPUUtilization
  name: new
  namespace: AWS/EC2
  period: 300
  statistic: Average
  threshold: 90
  treatMissingData: missing
```

Let it converge, then update the name and let it converge again. You'll see two alarms in the AWS dashboard.

**Expected outcome**

The one with the old name should be deleted.

**Environment**

* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? Yes, 1.27
* AWS service targeted (S3, RDS, etc.): Cloudwatch
