### ISSUE TITLE
MemoryDB controller - broken helm chart.

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1982]
v1.0.1:

```bash
$ git checkout v1.0.1
Previous HEAD position was cdee277 Update to ACK runtime v0.27.1, code-generator v0.27.1 (#85)
HEAD is now at 719fe91 Update to ACK runtime `v0.26.0`, code-generator `v0.26.1` (#83)
```

with default values:

```bash
$ helm template . | kubectl apply --dry-run=client -f - 
serviceaccount/ack-memorydb-controller created (dry run)
clusterrole.rbac.authorization.k8s.io/ack-memorydb-controller configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/release-name-memorydb-chart created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-reader created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-writer created (dry run)
deployment.apps/release-name-memorydb-chart created (dry run)
```

Add secret with amazon access key:

```yaml
aws:
  # If specified, use the AWS region for AWS API calls
  region: "eu-west-2"
  endpoint_url: ""
  credentials:
    # If specified, Secret with shared credentials file to use.
    secretName: "amazon-secret-key"
    # Secret stringData key that contains the credentials
    secretKey: "credentials"
    # Profile used for AWS credentials
    profile: "default" 
```

apply successful :

```bash
$ helm template . | kubectl apply --dry-run=client -f - 
serviceaccount/ack-memorydb-controller created (dry run)
clusterrole.rbac.authorization.k8s.io/ack-memorydb-controller configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/release-name-memorydb-chart created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-reader created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-writer created (dry run)
deployment.apps/release-name-memorydb-chart created (dry run)
```

Now try use v1.0.2:

```bash
$ git checkout v1.0.2
Previous HEAD position was 719fe91 Update to ACK runtime `v0.26.0`, code-generator `v0.26.1` (#83)
HEAD is now at cdee277 Update to ACK runtime v0.27.1, code-generator v0.27.1 (#85)
```

With default values:

```bash
$ helm template . | kubectl apply --dry-run=client -f - 
serviceaccount/ack-memorydb-controller created (dry run)
clusterrole.rbac.authorization.k8s.io/ack-memorydb-controller configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/release-name-memorydb-chart created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-reader created (dry run)
role.rbac.authorization.k8s.io/ack-memorydb-writer created (dry run)
deployment.apps/release-name-memorydb-chart created (dry run)
```

Change the secret:

```
helm template . | kubectl apply --dry-run=client -f - 
Error: YAML parse error on memorydb-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 106: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
error: no objects passed to apply
```

So conclusion - the adding of secret to values.yaml of MemoryDB Chart v1.0.2 breaks it. Other controllers (EC2, IAM etc.) are not affected.
