### ISSUE TITLE
Error creating Eventbridge Rule with empty ScheduleExpression on non-default Eventbridge EventBus

### ISSUE THREAD

**Issue by jose-fully-ported** [aws-controllers-k8s/community#1984]
**Describe the bug**

When an Eventbridge Rule against a custom Eventbridge EventBus, I get the following error:

```
ValidationException: ScheduleExpression is supported only on the default event bus.
```

The ScheduleExpression is empty, so I think this is likely due to the field being submitted regardless.

**Steps to reproduce**

Create an EventBus:

```yaml
apiVersion: eventbridge.services.k8s.aws/v1alpha1
kind: EventBus
spec:
  name: custom-bus
```

Create a Rule (I manually created an sns topic in the ui)

```
apiVersion: eventbridge.services.k8s.aws/v1alpha1
kind: Rule
spec:
  description: Send guard duty output to SNS
  eventBusRef:
    from:
      name: custom-bus
  eventPattern: '{"detail":{"severity":[4,4,4.1,4.2,4.3,4.4,4.5,4.6,4.7,4.8,4.9,5,5,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.9,6,6,6.1,6.2,6.3,6.4,6.5,6.6,6.7,6.8,6.9,7,7,7.1,7.2,7.3,7.4,7.5,7.6,7.7,7.8,7.9,8,8,8.1,8.2,8.3,8.4,8.5,8.6,8.7,8.8,8.9]},"detail-type":["GuardDuty
    Finding"],"source":["aws.guardduty"]}'
  name: guard-duty-rule
  scheduleExpression: ""
  targets:
  - arn: some-sns-arn
    id: guard-duty
    inputTransformer:
      inputPathsMap:
        Account_ID: $.detail.accountId
        Finding_ID: $.detail.id
        Finding_Type: $.detail.type
        Finding_description: $.detail.description
        region: $.region
        severity: $.detail.severity
      inputTemplate: |-
        Test template
```

**Expected outcome**

I think the rule should be created _without_ submitting the `ScheduleExpression` field if a bus is specified.

A concise description of what you expected to happen.

**Environment**

* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? : 1.27
* AWS service targeted (S3, RDS, etc.): Eventbridge
