### ISSUE TITLE
SecretKeyReference requires the 'Key' field

### ISSUE THREAD

**Issue by ndbhat** [aws-controllers-k8s/community#2001]
**Is your feature request related to a problem?**
'Key' is a required field for the SecretKeyReference
Description of the field:
```
                description: SecretKeyReference combines a k8s corev1.SecretReference
                  with a specific key within the referred-to Secret
                properties:
                  key:
                    description: Key is the key within the secret
                    type: string
                  name:
                    description: name is unique within a namespace to reference a
                      secret resource.
                    type: string
                  namespace:
                    description: namespace defines the space within which the secret
                      name must be unique.
                    type: string
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
```

**Describe the solution you'd like**
'Key' should be an optional field
