### ISSUE TITLE
Kafka controller enhancements

### ISSUE THREAD

**Issue by kkopuru** [aws-controllers-k8s/community#2017]
Today, we are binding Kafka to applications by provisioning secret manually. Having broker/zookeeper connection strings and user information exposed via status helps to bind Kafka automatically using FieldExport
```
  status:
    ackResourceMetadata:
      arn: XXXX
      ownerAccountID: "XXXX"
      region: us-west-2
    conditions:
    - message: not implemented
      status: "True"
      type: ACK.Terminal
    - lastTransitionTime: "2024-02-14T19:45:27Z"
      message: Resource not synced
      reason: resource is in terminal condition
      status: "False"
      type: ACK.ResourceSynced
    state: CREATING
```

Additional findings identified while creating MSK cluster that were not being handled
- Custom configuration creation
https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html
- Associating secret from secret manager when client authentication enabled
