### ISSUE TITLE
ACK controller have duplicate CRD causing issues when using kustomize

### ISSUE THREAD

**Issue by leofvo** [aws-controllers-k8s/community#2018]
**Is your feature request related to a problem?**
Yes.
To understand our issue, we are using argocd and kustomize, and we have defined an argocd application that is regrouping all ACK controller we want to use. 
Basically, we use IAM, RDS, S3.
We have an issue due to kustomize, when kustomize is building the yaml, it throws an error due to CRDs duplication...

The CRDs concerned are the following:
services.k8s.aws_adoptedresources.yaml
services.k8s.aws_fieldexports.yaml

Theses CRDs are present in each helm charts, and they are exactly the same..

**Step to reproduce our problem** 
Create your kustomize file:
```yml
helmCharts:
- repo: oci://public.ecr.aws/aws-controllers-k8s
  name: s3-chart
  includeCRDs: true
  releaseName: s3
  version: 1.0.9
- repo: oci://public.ecr.aws/aws-controllers-k8s
  name: rds-chart
  includeCRDs: true
  releaseName: rds
  version: 1.1.11
```

Then apply:
`kustomize build --enable-helm .`

At this step, kustomize will fail saying that some CRDs are the same, and need to be merge or patch.

**Describe the solution you'd like**
Define this CRDs as helm dependencies could allow us to activate the CRD creation once.

**Describe alternatives you've considered**
Giving more flexibility to choose which CRDs are deployed from the helm values.

**Comment by gecube** [comment]
Hi!

Interesting thing. I really wonder how I did not notice it, as I am using `FluxCD` and did not run into this issue. For the more context - I am installing every chart as a separate release.

**Comment by jon-rei** [comment]
I also ran into the same problem with ArgoCD. We use ArgoCD to deploy all our applications and use the ack-chart to enable all the controllers we want to deploy in our clusters. 

ArgoCD now displays the following for our application:

```
Resource apiextensions.k8s.io/CustomResourceDefinition//adoptedresources.services.k8s.aws appeared 2 times among application resources.
Resource apiextensions.k8s.io/CustomResourceDefinition//fieldexports.services.k8s.aws appeared 2 times among application resources.
```

For us, the deployment of the controllers does not fail, but there is a warning in the application, but it would be great if the CRD deployment could be improved.

**Comment by james-callahan** [comment]
Trying to do a kustomization with multiple upstream controllers fail:
```
Error: accumulating resources: accumulation: may not add resource with an already registered id: CustomResourceDefinition.v1.apiextensions.k8s.io/adoptedresources.services.k8s.aws.[noNs]
```

**Comment by pandvan** [comment]
We're just hit the same issue.
Maybe if could be better to move shared CRDs to https://github.com/aws-controllers-k8s/ack-chart Chart and let them optional on single charts. It could be helpful to treat them as resources instead of CRDs. Many other charts are moving in this direction to allow better upgrade management by Helm, ArgoCD and other deployment tools

**Comment by mmclane** [comment]
We are also seeing the issue and are using the ack-chart helm chart.

I have seen the pattern where the CRDs are moved to a separate helm chart and that is what my gut says is the right answer.  It doesn't have to be all of them, just the common ones (two of them currently right?).  That common chart can be a dependency for the other charts.

**Comment by MalibuKoKo** [comment]
@rushmash91 

Hi,
Could you please clarify why the initial issue [#2018](https://github.com/aws-controllers-k8s/community/issues/2018) was closed? It seems that the more recent one ([#2300](https://github.com/aws-controllers-k8s/community/issues/2300)) is actually a duplicate of the original, rather than the other way around.

This issue has been known for over a year and a half, yet it appears the original ticket was closed without any resolution and based on a questionable rationale. Could you kindly provide some context or next steps?

Thanks in advance!

**Comment by MalibuKoKo** [comment]
That's good news; things are moving forward!
Thanks for the feedback.

**Comment by mateocolina** [comment]
any news on this? we are experiencing the same issue as well, when trying to render/template the helm chart (using `helmfile template --include-crds`), as we try to apply "what you see is what you deploy" with ArgoCD.

**Comment by james-callahan** [comment]
FWIW we work around this by having our local ACK applications defined as e.g.:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/aws-controllers-k8s/sqs-controller/config/default?ref=3bf4c64846ddef0e2dacc9a09c7083e439591a5c # tag=v1.2.1
patches:
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: adoptedresources.services.k8s.aws
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: fieldexports.services.k8s.aws
  - # Delete the namespace resource included upstream
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ack-system
  - # Delete AWS_REGION from upstream
    # We expect it to be filled in by the amazon-eks-pod-identity-webhook
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ack-sqs-controller
        namespace: ack-system
      spec:
        template:
          spec:
            containers:
              - name: controller
                env:
                  - $patch: delete
                    name: AWS_REGION
namespace: default # The namespaces in the upstream kustomization are inconsistent
commonLabels:
  # These labels are applied inconsistently by the upstream kustomization
  # This will set them consistently.
  app.kubernetes.io/name: ack-sqs-controller
  app.kubernetes.io/part-of: ack
images:
  - name: public.ecr.aws/aws-controllers-k8s/sqs-controller
    newTag: 1.2.1@sha256:3cca3747d8aaab2d8a767c1b8805d542ae95619b015fa44d7db640e274cc72fb
```
