### ISSUE TITLE
CloudFront CachePolicy missing required field

### ISSUE THREAD

**Issue by CosminMartinas** [aws-controllers-k8s/community#2025]
**Describe the bug**
The CachePolicy deploy fails with "error":"InvalidParameter: 1 validation error(s) found.\n- missing required field, UpdateCachePolicyInput.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Quantity.\n"

**Steps to reproduce**

```
`apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: CachePolicy
metadata:
  name: poctestclient
spec:
  cachePolicyConfig:
    comment: "cachepolicy test"
    defaultTTL: 86400
    maxTTL: 31536000
    minTTL: 60
    name: poctestclient
    parametersInCacheKeyAndForwardedToOrigin:
      cookiesConfig:
        cookieBehavior: none
      enableAcceptEncodingBrotli: true
      enableAcceptEncodingGzip: true
      headersConfig:
        headerBehavior: whitelist
        headers:
          items:
          - Authorization
      queryStringsConfig:
        queryStringBehavior: all`
```

**Expected outcome**
It seems that AWS is expecting a field called "Quantity" which is not defined in the cachepolicy CRD

**Environment**
dev

* Kubernetes version
* Using EKS (yes), version:v1.27.9 
* AWS service targeted (CloudFront)
