### ISSUE TITLE
EKS `Cluster` resource type refuses updates due to unexpected `subnetRefs` and `securityGroupRefs` resolutions

### ISSUE THREAD

**Issue by jcrowthe** [aws-controllers-k8s/community#2038]
**Describe the bug**
When deploying an EKS `Cluster` resource using ACK EKS controller, the first time you `kubectl apply` the resource will work just fine if you have `subnetRefs` or `securityGroupRefs` in your yaml file. However, when you later attempt to update the `Cluster` resource, if you still have these references in your yaml, the update will fail with the following:
```
  conditions:
  - lastTransitionTime: "2024-03-13T04:55:59Z"
    message: Reference resolution failed
    reason: 'both resource reference wrapper and ID cannot be used together: ResourcesVPCConfig.SecurityGroupIDs,ResourcesVPCConfig.SecurityGroupRefs'
    status: Unknown
    type: ACK.ReferencesResolved
```

and likewise log the following on the eks-controller pod:
```
{"level":"error","ts":"2024-03-13T04:55:38.745Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"eks.services.k8s.aws","controllerKind":"Cluster","Cluster":{"name":"prod1-eks","namespace":"prod1"},"namespace":"prod1","name":"prod1-eks","reconcileID":"4effb6b2-1582-435d-8fb0-2127fab36ce0","error":"both resource reference wrapper and ID cannot be used together: ResourcesVPCConfig.SecurityGroupIDs,ResourcesVPCConfig.SecurityGroupRefs","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```

This is unexpected, as only the `*Refs` were specified by the human operator in the yaml spec, but on further investigation of the `Cluster` object, we find that the EKS controller has unexpectedly injected the actual subnet and security group IDS into the `Cluster` object.

```
    securityGroupIDs:
    - sg-0b9646a83ce1e809e
    securityGroupRefs:
    - from:
        name: prod1-eks-security-group
    subnetIDs:
    - subnet-031595d930ab95d76
    - subnet-07123c7f4eca0c93a
    subnetRefs:
    - from:
        name: prod1-private-subnet1
    - from:
        name: prod1-private-subnet2
```

This breaks the declarative nature of ACK and CRDs, or in other words, as a human user, I can apply the first yaml with `*Refs` for convenience, but then I will be required to remove those refs and lookup the actual IDs in order to later update that YAML file. This breaks the intent behind CRDs.

**Expected outcome**
I would expect that I can continue to apply my original YAML spec which has only references in it. I should not have to do manual work between my first `kubectl apply` and my second.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)
