### ISSUE TITLE
CloudFront Function functionCode expects base64 encoded bytes; just use string

### ISSUE THREAD

**Issue by doctorpangloss** [aws-controllers-k8s/community#2039]
**Describe the bug**
```
              functionCode:
                description: |-
                  The function code. For more information about writing a CloudFront function,
                  see Writing function code for CloudFront Functions (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/writing-function-code.html)
                  in the Amazon CloudFront Developer Guide.
                format: byte
                type: string
```
Don't use `format: byte` here, it is kind of painful. It's nice to author these in plain, multiline strings.
**Steps to reproduce**

Author a function with plain text instead of a base64-encoded string.
Observe ` spec.functionCode in body must be of type byte` for the resource.

**Expected outcome**
I should be able to author functions like this:

```yaml
---
apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: some-function
  namespace: default
spec:
  functionConfig:
    runtime: cloudfront-js-1.0
    comment: "..."
  name: "..."
  functionCode: |
    function handler(event) {
      var request = event.request;
      var response = event.response;
      if (request.queryString ...
```

**Environment**

* Kubernetes version 1.26
* Using EKS (yes/no), if so version? 1.23
* AWS service targeted (S3, RDS, etc.) CloudFront
