### ISSUE TITLE
Add DescribeFunction, etc. to CloudFront IAM Policy suggestions

### ISSUE THREAD

**Issue by doctorpangloss** [aws-controllers-k8s/community#2040]
**Describe the bug**
CloudFront functions will fail with

```
  status:
    ackResourceMetadata:
      ownerAccountID: "2...6"
      region: us-west-2
    conditions:
    - message: "AccessDenied: User: arn:aws:sts::2...6:assumed-role/e...7/1...9
        is not authorized to perform: cloudfront:DescribeFunction on resource: arn:aws:cloudfront::2...6:function/SetContentDispositionFunction
        because no identity-based policy allows the cloudfront:DescribeFunction action\n\tstatus
        code: 403, request id: ..."
      status: "True"
      type: ACK.Recoverable
    - lastTransitionTime: "2024-03-14T19:18:10Z"
      message: Unable to determine if desired resource state matches latest observed
        state
      reason: "AccessDenied: User: arn:aws:sts::2...6:assumed-role/e...7/1...9
        is not authorized to perform: cloudfront:DescribeFunction on resource: arn:aws:cloudfront::2...6:function/SetContentDispositionFunction
        because no identity-based policy allows the cloudfront:DescribeFunction action\n\tstatus
        code: 403, request id: ..."
      status: Unknown
      type: ACK.ResourceSynced
```

https://github.com/aws-controllers-k8s/cloudfront-controller/blob/c4173425a03d539642c1bb8817998f49df9248fe/config/iam/recommended-inline-policy#L4 Needs to be updated
**Steps to reproduce**
Create a function
Check its status
**Expected outcome**
The suggested policy needs to have all the CloudFront permissions
**Environment**

* Kubernetes version 1.26
* Using EKS (yes/no), if so version? 1.23
* AWS service targeted (S3, RDS, etc.) CloudFront
