### ISSUE TITLE
Reference resolution failed: vpcs.ec2.services.k8s.aws "vpc-*******" not found when creating ack security group

### ISSUE THREAD

**Issue by salimadr** [aws-controllers-k8s/community#2045]
**Describe the bug**
Hello, I created ack security group. And it got created successfully, I specifically used already created vpc by referencing in the vpc-id field in the aws account. I am trying to field export the security group id into the configmap, which should have been shown in the status based on the [docs.](https://aws-controllers-k8s.github.io/community/reference/ec2/v1alpha1/securitygroup/#spec) But in the status: I have the following message:
         

```
   status:
              conditions:
                - lastTransitionTime: '2024-03-18T17:31:16Z'
                  message: Reference resolution failed
                  reason: vpcs.ec2.services.k8s.aws "vpc-************" not found
                  status: Unknown
                  type: ACK.ReferencesResolved
```

**Steps to reproduce**

**Expected outcome**
Also in my ack security group created, i see that  vpcRef field was added, even though I didn't specify in the config, since it's optional.
```
vpcID: vpc-***********
vpcRef:
    from:
      name: vpc-************
```
Do I need to adopt the already created vpc as an ack resource? or any other thoughts?

**Environment**

* Kubernetes version : 1.28
* Using EKS (yes/no), if so version?  yes. 1.28
* AWS service targeted (S3, RDS, etc.) EC2 controller-Security Group 1.24 version

**Comment by a-hilaly** [comment]
Hi @salimadr - thank you for opening this issue. ACK Resource references only work with Kubernetes resources, meaning that they have to point to an "ACK" VPC resource `metadata.name`. e.g

```yaml
kind: Subnet
apiVersion: ec2.services.k8s.aws
metadata: {...}
vpcRef:
    from:
      name: my-vpc
---
kind: VPC
apiVersion: ec2.services.k8s.aws
metadata:
  name: my-vpc
spec: {...}
```
