### ISSUE TITLE
Feature request - taints in NodeGroup have ambiguous syntax

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2047]
Good day!

I am trying to create new NodeGroup with Bottlerocket OS.

So I wrote the next manifest:

```
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng-20240323-b
  namespace: infra-production
spec:
  name: production-main-ng-20240323-b
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::966321756598:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 10
    maxSize: 10
    desiredSize: 10
  instanceTypes:
    - m5.4xlarge
  amiType: BOTTLEROCKET_x86_64
  taints:
  - effect: NoSchedule
    key: com.zodiamarkets.role
    value: zodia-platform-b
```

I got the next error in the status field when applying:

```
    - message: |-
        InvalidParameterException: Invalid taint effect: NoSchedule, must be one of these [NO_SCHEDULE, NO_EXECUTE, PREFER_NO_SCHEDULE]
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "2ec55cc1-c3a9-4561-89d6-b90c818fc34b"
          },
          ClusterName: "production",
          Message_: "Invalid taint effect: NoSchedule, must be one of these [NO_SCHEDULE, NO_EXECUTE, PREFER_NO_SCHEDULE]",
          NodegroupName: "production-main-ng-20240323-b"
        }
      status: 'True'
      type: ACK.Terminal
```

It would be nice to allow to use k8s names for the taints effects, because like k8s engineer I usually use them in other k8s manifests. We could support both type of values - k8s native ones (`NoSchedule`, `NoExecute`...) and amazon API compliant ones (`[NO_SCHEDULE, NO_EXECUTE, PREFER_NO_SCHEDULE]`)
