### ISSUE TITLE
ImageConfig changes are not detected by Lambda Controller

### ISSUE THREAD

**Issue by yemi-gbenebor** [aws-controllers-k8s/community#2051]
**Describe the bug**

When updating `imageConfig.command`, the AWS Lambda Controller does not detect changes. The controller reports that sync is successful and does not update the function ImageConfig. 

Got the following log from the AWS Lambda Controller when editing this field: 
```
2024-04-02T19:22:59.569Z	DEBUG	ackrt	no difference found between metadata and spec for desired and latest object.	{"account": "452601555275", "role": "", "region": "us-east-1", "kind": "Function", "namespace": "default", "name": "hello-world-lambda-hello", "is_adopted": false, "generation": 9}
```
**Steps to reproduce**

1. Create a lambda function, function should be created using an image. 
```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: $FUNCTION_NAME
 annotations:
   services.k8s.aws/region: $AWS_REGION
spec:
 name: $FUNCTION_NAME
 packageType: Image
 code:
     imageURI: $IMAGE_URI
 imageConfig:
    command: [hello.open_handler]
 role: $LAMBDA_ROLE
 description: function created by ACK lambda-controller e2e tests

```
2. Edit the imageConfig.command
```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: $FUNCTION_NAME
 annotations:
   services.k8s.aws/region: $AWS_REGION
spec:
 name: $FUNCTION_NAME
 packageType: Image
 code:
     imageURI: $IMAGE_URI
 imageConfig:
    command: [thanks.open_handler]
 role: $LAMBDA_ROLE
 description: function created by ACK lambda-controller e2e tests

```

You should see in the AWS console that the function command was not updated. 

**Expected outcome**
A concise description of what you expected to happen.

After updating the imageConfig.command, I expected to see the ImageConfig of the function updated to match the value used for `imageConfig.command`
 
**Environment**
`prod`

* Kubernetes version 1.25
* Using EKS (yes/no), if so version?  Yes, 1.25
* AWS service targeted (S3, RDS, etc.) Lambda
