### ISSUE TITLE
Routetable table routes are different compared with the ones used during the creation of the object

### ISSUE THREAD

**Issue by adriananeci** [aws-controllers-k8s/community#2054]
**Describe the bug**
I've noticed that the routetable rules rules are changed by the ack controller once created.
This affect an ArgoCD application that is creating such objects because it is constantly in an out of sync status.

**Steps to reproduce**

Create a routetable using 
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  annotations:
    ec2.services.k8s.aws/deletion-policy: retain
  name: dev-va6-k8s-public
spec:
  routes:
    - destinationCIDRBlock: 0.0.0.0/0
      gatewayRef:
        from:
          name: dev-va6-k8s
    - destinationCIDRBlock: 10.15.20.0/21
      transitGatewayID: tgw-abc123
  vpcRef:
    from:
      name: dev-va6-k8s
```

Once created the routes are getting changed into something like:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  annotations:
    ec2.services.k8s.aws/deletion-policy: retain
  name: dev-va6-k8s-public
spec:
  routes:
    - destinationCIDRBlock: 10.15.20.0/21
      transitGatewayID: tgw-abc123
    - destinationCIDRBlock: 0.0.0.0/0
      gatewayID: igw-abc123
    - destinationPrefixListID: pl-123abc
      gatewayID: vpce-123
    - destinationPrefixListID: pl-abc123
      gatewayID: vpce-xxxx
  vpcRef:
    from:
      name: dev-va6-k8s
```

**Expected outcome**
Routetable routes should remain the same after object creation

**Environment**

* Kubernetes version 1.27
* Using EKS (yes/no), if so version? 1.27
* AWS service targeted (S3, RDS, etc.) EC2

cc @a-hilaly

**Comment by a-hilaly** [comment]
@adriananeci looks like those are "defaults" created by the ec2 API, can you confirm? If it's the case, then it's an expected behaviour. The controllers can default some fields on Create/Update if they are not specified in the spec.

**Comment by a-hilaly** [comment]
Mmmmm looks like the gatewayRef also disapeared ...

```yaml
      gatewayRef:
        from:
          name: dev-va6-k8s
```

Are you referring to this specific behaviour?
