### ISSUE TITLE
RDS DBInstance with Aurora enters broken state after upgrade

### ISSUE THREAD

**Issue by nik843** [aws-controllers-k8s/community#2060]
**Describe the bug**
The bug is related to application behaviour after the Aurora DB cluster upgrade. All DB instances have the following error:
````
InvalidParameterCombination: The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API
````
This is the desired state deployed to the cluster by ArgoCD:
````
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  annotations:
  name: test-aurora2-mysql-instance-0
  namespace: test
spec:
  autoMinorVersionUpgrade: false
  dbClusterIdentifier: test-aurora2-mysql
  dbInstanceClass: db.serverless
  dbInstanceIdentifier: test-aurora2-mysql-instance-0
  dbSubnetGroupName: test-subnet
  engine: aurora-mysql
  promotionTier: 2
  publiclyAccessible: false
  tags:
    - key: 'costs:envName'
      value: test
    - key: 'costs:type'
      value: internal
````

Life manifest is the following:
````
spec:
  allocatedStorage: 1
  autoMinorVersionUpgrade: false
  backupRetentionPeriod: 7
  caCertificateIdentifier: rds-ca-2019
  copyTagsToSnapshot: false
  dbClusterIdentifier: test-aurora2-mysql
  dbInstanceClass: db.serverless
  dbInstanceIdentifier: test-aurora2-mysql-instance-0
  dbSubnetGroupName: test-subnet
  deletionProtection: false
  engine: aurora-mysql
  engineVersion: 8.0.mysql_aurora.3.03.1
  kmsKeyID: >-
    arn:aws:kms:eu-central-1:id
  licenseModel: general-public-license
  masterUsername: root
  monitoringInterval: 0
  multiAZ: false
  performanceInsightsEnabled: false
  preferredBackupWindow: '20:05-20:35'
  preferredMaintenanceWindow: 'tue:22:36-tue:23:06'
  promotionTier: 2
  publiclyAccessible: false
  storageEncrypted: true
  storageThroughput: 0
  storageType: aurora
  tags:
    - key: 'costs:envName'
      value: test
    - key: 'costs:type'
      value: internal
````
**Steps to reproduce**
upgrade Aurora DB cluster - works the same way for MySQL and PostgreSQL

**Expected outcome**
DBinstance shouldn't have engineVersion set in the case of the Aurora cluster (serverless)

**Environment**

* Kubernetes version - 1.24.16
* Using EKS - no
* AWS service targeted - rds
* ACK version - 1.1.8
