### ISSUE TITLE
Lambda function is not updated when s3Key changed

### ISSUE THREAD

**Issue by blueacidification** [aws-controllers-k8s/community#2067]
**Describe the bug**
My team uses gitops to deploy apps in kubernetes, we thought we could do the same for lambdas. 

**Steps to reproduce**
Apply manifest. 

function.yaml 
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: test-lambda-access-2
 annotations:
   services.k8s.aws/region: eu-central-1
spec:
 name: test-lambda-access-2
 code:
   s3Bucket: lambda-function-devops
   s3Key: my-deployment-package-1.zip
 role: arn:aws:iam::535479077865:role/lambda_basic_execution
 runtime: python3.9
 handler: lambda_function.lambda_handler
 description: function created by ACK lambda-controller e2e tests
```

Change the s3Key.
The function says successfully synced and has the latest changes.
The function does NOT update on AWS. 

**Expected outcome**
The function is updated with the expected s3Key.

**Environment**

* Kubernetes version 1.28
* Using EKS (yes/no), if so version? 1.28
* AWS service targeted (S3, RDS, etc.) s3
