### ISSUE TITLE
EC2 controller throws `resource reference wrapper or ID required: GroupName,GroupRef` when referencing a SecurityGroup using `groupID` in `userIDGroupPairs`

### ISSUE THREAD

**Issue by wjf3121** [aws-controllers-k8s/community#2068]
**Describe the bug**
This bug is a regression observed since Ec2 controller v1.2.6, the following resource will throw `resource reference wrapper or ID required: GroupName,GroupRef` error:

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    services.k8s.aws/region: us-east-1
  name: testsg
spec:
  description: test security group
  egressRules:
  - fromPort: 0
    ipProtocol: "-1"
    toPort: 0
    userIDGroupPairs:
    - description: allow all traffic
      groupID: sg-0xxxxxxxxxxxxxxxxxx
  ingressRules:
  - fromPort: 0
    ipProtocol: "-1"
    toPort: 0
    userIDGroupPairs:
    - description: allow all traffic
      groupID: sg-0xxxxxxxxxxxxxxxxxx
  name: testsg
  tags:
  - key: Project
    value: Test
  vpcID: vpc-xxxxxxxxxxxxxx
```

The resource can be successfully reconciled after downgrading EC2 controller to v1.2.5

**Steps to reproduce**
See bug description

**Expected outcome**
Security groups with rules referring to other source/dest security groups using groupID should succeed.

**Environment**

* Kubernetes version: 1.27
* Using EKS (yes/no): yes, 1.26
* AWS service targeted (S3, RDS, etc.): EC2 (security group)
