### ISSUE TITLE
EC2 controller for vpcendpoint does not update status

### ISSUE THREAD

**Issue by nnbu** [aws-controllers-k8s/community#2075]
**Describe the bug**
When we create vpc endpoint, the status becomes active in aws console after a minutes. But it is not updated in the CR itself. To be specific, it would get updated correctly if we force reconciliation by restarting the ec2 controller pod or by waiting for 10h (default reconciliation time)

**Steps to reproduce**
1. Apply CR
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCEndpoint
metadata:
  name: vpce
spec:
  dnsOptions:
    dnsRecordIPType: ipv4
  ipAddressType: ipv4
  policyDocument: "{\n  \"Statement\": [\n    {\n      \"Action\": \"*\", \n      \"Effect\":
    \"Allow\", \n      \"Principal\": \"*\", \n      \"Resource\": \"*\"\n    }\n
    \ ]\n}"
  privateDNSEnabled: false
  securityGroupIDs:
  - sg-<id>
  serviceName: aws.sagemaker.us-west-2.studio
  subnetIDs:
  - subnet-<id>
  vpcEndpointType: Interface
  vpcID: vpc-<id>
```

2. Check in aws console that vpc endpoint becomes active after 1 minutes
3. Check the status of the CR to see status has not changed to `active`

**Expected outcome**
Status in the CR should show the status as active after a minute or so.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? yes
* AWS service targeted (S3, RDS, etc.): ec2
