### ISSUE TITLE
Add support for DynamoDB Global Table V2 (2019.11.21)

### ISSUE THREAD

**Issue by gcalv0** [aws-controllers-k8s/community#2077]
**Is your feature request related to a problem?**
Yes, actually ACK creates version 2017 (2017.11.29) which requires to create an empty table in the destination before adding global tables for a region. Also there are several restrictions/changes regarding the legacy version.

This request is related with the following closed issue:
https://github.com/aws-controllers-k8s/community/issues/1034

**Describe the solution you'd like**
Use the actual version as a default to avoid braking changes and offer the possibility to specify the version in the ACK manifest.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables_upgrade.html

**Comment by michaelhtm** [comment]
Hey @gcalv0, to support this feature we need to introduce the `ReplicaUpdates` field to the Table resource. We would also need to be careful in comparing the delta between the ReplicationGroupUpdates to see which replicas need to be created, updated, or deleted. I'm not absolutely sure this feature will work for ACK,
but for now a workaround that worked for me was to create the GlobalTable using the and adopting it to ACK using something similar to this:

```yaml
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: mytable
  annotations:
    services.k8s.aws/deletion-policy: retain
    services.k8s.aws/read-only: "true"
    services.k8s.aws/region: us-west-2
    services.k8s.aws/adoption-policy: adopt-or-create
    services.k8s.aws/adoption-fields: | 
        {
          "tableName": "mytable"
        }

```
I hope this helps!
