### ISSUE TITLE
Add support for elasticache CacheClusters

### ISSUE THREAD

**Issue by jessectl** [aws-controllers-k8s/community#2079]
**Describe the bug**
No CRD to create a redis cluster?

**Steps to reproduce**
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheCluster
metadata:
  name: my-redis-cluster
  namespace: kube-system
spec:
  cacheNodeType: cache.t4g.micro
  numCacheNodes: 1
  engine: redis
  engineVersion: "7.1"
  cacheSubnetGroupName: test
  securityGroupIDs:
    - sg-0e899eb4268ec8427
```
```
kubectl get crds | grep elasticache                 

cacheparametergroups.elasticache.services.k8s.aws         2024-05-28T15:58:40Z
cachesubnetgroups.elasticache.services.k8s.aws              2024-05-28T15:58:40Z
replicationgroups.elasticache.services.k8s.aws                  2024-05-28T15:58:41Z
snapshots.elasticache.services.k8s.aws                             2024-05-28T15:58:41Z
usergroups.elasticache.services.k8s.aws                           2024-05-28T15:58:42Z
users.elasticache.services.k8s.aws                                    2024-05-28T15:58:42Z
```
**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* 1.30
* AWS service targeted (S3, RDS, etc.)
* Redis
