### ISSUE TITLE
[ecs] AlarmNames should be optional

### ISSUE THREAD

**Issue by axot** [aws-controllers-k8s/community#2087]
**Describe the bug**
When updating service.ecs.services.k8s.aws, the controller shows the following error

> "error": "InvalidParameter: 1 validation error(s) found.\n- missing required field, UpdateServiceInput.DeploymentConfiguration.Alarms.AlarmNames.\n",

**Steps to reproduce**
1. import exists ecs service
2. edit service's desiredCount 

an example AdoptedResource
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: hello
  namespace: hello
spec:
  aws:
    nameOrID: hello
    additionalKeys:
      cluster: cluster-hello
  kubernetes:
    group: ecs.services.k8s.aws
    kind: Service
```

**Expected outcome**
No error when applying service

**Environment**
EKS

* Kubernetes version 1.29
* Using EKS (yes/no), if so version?  yes, 1.29
* AWS service targeted (S3, RDS, etc.) ecs
