### ISSUE TITLE
Bucket status on longer includes the ARN, it did previously at some point. Docs also state that it's supposed to.

### ISSUE THREAD

**Issue by jbilliau-rcd** [aws-controllers-k8s/community#2094]
**Describe the bug**

While testing version `1.0.10` of the ack-s3-controller, I noticed the `Bucket` object no longer has the ARN of the created bucket in its status field no more. According to the docs, it's supposed to, and I know it used to when I was playing with a previous version. https://aws-controllers-k8s.github.io/community/reference/s3/v1alpha1/bucket/

```
status:
  ackResourceMetadata:
    ownerAccountID: '414323852230'
    region: us-east-2
  conditions:
    - lastTransitionTime: '2024-06-19T12:49:17Z'
      message: Resource synced successfully
      reason: ''
      status: 'True'
      type: ACK.ResourceSynced
```

**Steps to reproduce**

Create a `Bucket` object, note the status.

**Expected outcome**

`Bucket` has the ARN of the bucket it it's status, and thus can be used for `FieldExport`

* Kubernetes version: 1.28
* Using EKS (yes/no), if so version?  Yes
* AWS service targeted (S3, RDS, etc.) S3
