### ISSUE TITLE
InvalidGroup.Duplicate: The security group '**' already exists

### ISSUE THREAD

**Issue by Scumwong** [aws-controllers-k8s/community#2095]
**Describe the bug**
I created a security group in the aws console, but when I tried to change it via ec2-controllers, I got an error that the security group already exists. This case does not support modifying manually created security groups? Is the only way to rebuild the security group is via ec2-controllers?
**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version?  yes 1.25
* AWS service targeted (S3, RDS, etc.)

**Comment by a-hilaly** [comment]
@Scumwong can you please provide a manifest of the SG you're trying to create? also tell us more about what fields you're trying to modify.

**Comment by Scumwong** [comment]
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: example-security-group
spec:
  name: "example-security-group"
  description: "Example security group"
  vpcID: "vpc-xxxxxxxx" 
  ingressRules:
    - fromPort: 22
      toPort: 22
      ipProtocol: "tcp"
      ipRanges:
        - cidrIP: "0.0.0.0/0"
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: "-1"
      ipRanges:
        - cidrIP: "0.0.0.0/0"
This is my yaml for updating a sg that has been created  manually with aws console, but after apply the yaml ,log shows the sg exits and can not update

**Comment by gecube** [comment]
@Scumwong Good day! Please add a proper formatting (markdown) to your last message

**Comment by michaelhtm** [comment]
@Scumwong it seems like you just need to adopt the resource, ensuring it is managed by ACK, in order to make updates..
https://aws-controllers-k8s.github.io/community/docs/user-docs/adopted-resource/
https://aws-controllers-k8s.github.io/community/docs/user-docs/features/#resourceadoption

**Comment by michaelhtm** [comment]
@Scumwong 
Is this issue resolved for you?

**Comment by knottnt** [comment]
From the provided manifest the ACK controller was attempting to create a new duplicate security group resulting in the InvalidGroup.Duplicate error from AWS. To allow the ACK controller to manage resources that have been created through the AWS console you can use the [resource adoption feature](https://aws-controllers-k8s.github.io/docs/guides/adoption/) (example shown below).

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: ack-demo-sg
  annotations:
    services.k8s.aws/adoption-policy: "adopt-or-create"
    services.k8s.aws/adoption-fields: |
      {"groupID": "sg-123456"}
spec:
  name: ack-demo-sg
  description: "Sample security group managed by ACK"
  vpcID: vpc-123456
  tags:
    - key: Name
      value: ack-demo-sg
    - key: Environment
      value: staging
```

Additionally, since ec2-controller [v1.6.1](https://github.com/aws-controllers-k8s/ec2-controller/releases/tag/v1.6.1) the error message should be improved to better highlight that resource adoption is required.

```
  Conditions:
    Last Transition Time:  2026-04-30T23:20:49Z
    Message:               Resource already exists
    Reason:                This resource already exists but is not managed by ACK. To bring the resource under ACK management, you should explicitly adopt the resource by enabling the ResourceAdoption feature gate and populating the `services.k8s.aws/adoption-policy` and `services.k8s.aws/adoption-fields` annotations.
    Status:                True
    Type:                  ACK.Terminal
    Last Transition Time:  2026-04-30T23:20:49Z
    Message:               Resource not synced
    Reason:                resource is in terminal condition
    Status:                False
    Type:                  ACK.ResourceSynced
    Last Transition Time:  2026-04-30T23:20:49Z
    Message:               Resource already exists
    Reason:                ACK.Terminal
    Status:                False
    Type:                  Ready
```
