### ISSUE TITLE
Annotations don't update from AdoptedResource to the child resource

### ISSUE THREAD

**Issue by PowerSurj** [aws-controllers-k8s/community#2104]
**Describe the bug**

I deployed an AdoptedResource for prometheusservice Workspace without an annotation first.
Resource got successfully adopted and the Workspace custom resource got created.

Then I added an annotation in the metadata of the resource spec in the AdoptedResource.
```
spec:
  aws:
    nameOrID: ws-11111
  kubernetes:
    group: prometheusservice.services.k8s.aws
    kind: Workspace
    metadata:
      annotations:
        services.k8s.aws/deletion-policy: retain
      name: myworkspace
      namespace: mynamespace
```

However this annotation never got added to the Workspace resource.

Noticed that annotations only get set when you deploy a new resource, though.

**Expected outcome**

Annotations should've been set / updated on the Workspace / managed resource.

**Environment**

EKS 1.29
prometheusservice-controller:1.2.9
