### ISSUE TITLE
[Security Group] Circular references do not resolve

### ISSUE THREAD

**Issue by jantzenallphin** [aws-controllers-k8s/community#2119]
**Describe the bug**
We are creating/grouping multiple SecurityGroups ACK objects into a single helm chart. Among these are two SecurityGroups that contain rules that reference each other via `userIDGroupPairs` using `groupRef` field. The problem we are facing is that neither of these two SecurityGroups will successfully sync due to the referenced SecurityGroup not showing a synced status. 

The error status produced is as follows.

For the first SecurityGroup:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: jallphin00-sbx-va6-sg-k8s-control-plane
  namespace: sbx-clusters
...
status:
  conditions:
  - lastTransitionTime: "2024-07-23T23:19:11Z"
    message: Reference resolution failed
    reason: the referenced resource is not synced yet. resource:SecurityGroup, namespace:sbx-clusters,
      name:jallphin00-sbx-va6-sg-k8s-all
    status: Unknown
    type: ACK.ReferencesResolved

```

For the second SecurityGroup:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: jallphin00-sbx-va6-sg-k8s-all
  namespace: sbx-clusters
...
status:
  conditions:
  - lastTransitionTime: "2024-07-23T23:19:31Z"
    message: Reference resolution failed
    reason: the referenced resource is not synced yet. resource:SecurityGroup, namespace:sbx-clusters,
      name:jallphin00-sbx-va6-sg-k8s-control-plane
    status: Unknown
    type: ACK.ReferencesResolved
```

**Steps to reproduce**
Create two SecurityGroups referencing each other like so:

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: jallphin00-sbx-va6-sg-k8s-control-plane
  namespace: sbx-clusters
spec:
  description: k8s-control-plane security group rules for jallphin00-sbx-va6
  ingressRules:
  - fromPort: 443
    ipProtocol: tcp
    toPort: 443
    userIDGroupPairs:
    - description: Allow HTTPS access to control tier from workers
      groupRef:
        from:
          name: jallphin00-sbx-va6-sg-k8s-all
      userID: <account id>
  name: jallphin00-sbx-va6-sg-k8s-control-plane
  vpcID: <vpc id>
```

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: jallphin00-sbx-va6-sg-k8s-all
  namespace: sbx-clusters
spec:
  description: k8s-all security group rules for jallphin00-sbx-va6
  ingressRules:
  - fromPort: 443
    ipProtocol: tcp
    toPort: 443
    userIDGroupPairs:
    - description: Allow HTTPS access to Worker tier from Control
      groupRef:
        from:
          name: jallphin00-sbx-va6-sg-k8s-control-plane
      userID: <account id>
  name: jallphin00-sbx-va6-sg-k8s-all
  vpcID: <vpc id>
```
Neither of the SecurityGroups will reach a Synced state due the aforementioned error status. 

**Expected outcome**
The SecurityGroups should be created without issues. 

**Environment**

* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? 1.28
* AWS service targeted (S3, RDS, etc.): SecurityGroups
