### ISSUE TITLE
Lambda Function Advanced Logging Features Support

### ISSUE THREAD

**Issue by urton** [aws-controllers-k8s/community#2122]
Is there a timeline to support the new advanced logging features for Lambda? Specifically, "Customizing Lambda function’s CloudWatch log group".

https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/

**Comment by urton** [comment]
@Vandita2020 any update on the timeline?

**Comment by urton** [comment]
@a-hilaly @Vandita2020 do we have a target yet for getting this feature added?

**Comment by purkhusid** [comment]
This would be a great addition! Needed to lower the log volume of high volume Lambdas.

**Comment by purkhusid** [comment]
@michaelhtm Is this somewhere one the roadmap?

**Comment by michaelhtm** [comment]
Hello @purkhusid @urton 
This feature has now been released in [v1.7.0](https://github.com/aws-controllers-k8s/lambda-controller/releases/tag/v1.7.0)
Feel free to reopen this issue, or open a new one for any questions :)
/close

**Comment by urton** [comment]
@michaelhtm  I have confirmed the new feature works! One caveat, I had to delete my functions and aliases and recreate them (using Helm) in order for the new logging config to update.

**Comment by michaelhtm** [comment]
Thank you for the feedback @urton 
Can you share more about what happened? Were the functions already configured in AWS?
I do know that helm does not update CRDs, but this is the first i'm hearing of needing to delete 
a resource.
/reopen

**Comment by purkhusid** [comment]
For what it's worth it worked correctly for all of our existing Lambdas and new as well so I also suspect that the CRD might not have been updated in @urton case.

**Comment by urton** [comment]
@michaelhtm, see below for relevant info (hopefully).

Here's the log from the controller after I make a change to an existing function (via Helm):
```json
{"level":"info","ts":"2025-05-14T21:23:00.428Z","logger":"ackrt","msg":"desired resource state has changed","kind":"Function","namespace":"mynamespace","name":"myfunction","account":"123456789","role":"","region":"us-west-1","is_adopted":false,"generation":4,"diff":[{"Path":{"Parts":["Spec","Code","SHA256"]},"A":"foo17","B":"McgHQSnExi0Ef3NnUdDwX76vJ4YACRROMwxeOVqL6k0="},{"Path":{"Parts":["Spec","LoggingConfig","ApplicationLogLevel"]},"A":"INFO","B":null},{"Path":{"Parts":["Spec","LoggingConfig","LogFormat"]},"A":"JSON","B":"Text"},{"Path":{"Parts":["Spec","LoggingConfig","LogGroup"]},"A":"/aws/lambda/mygroup","B":"/aws/lambda/myfunction"},{"Path":{"Parts":["Spec","LoggingConfig","SystemLogLevel"]},"A":"WARN","B":null}]}
```

And the status of my function CR:
```yaml
status:
  ackResourceMetadata:
    arn: arn:aws:lambda:us-west-1:123456789:function:myfunction
    ownerAccountID: "123456789"
    region: us-west-1
  codeSHA256: McgHQSnExi0Ef3NnUdDwX76vJ4YACRROMwxeOVqL6k0=
  codeSize: 4187705
  conditions:
  - lastTransitionTime: "2025-05-14T21:23:02Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  lastModified: 2025-05-14T21:23:01.000+0000
  lastUpdateStatus: InProgress
  lastUpdateStatusReason: The function is being created.
  lastUpdateStatusReasonCode: Creating
  revisionID: 96a471ce-eae3-41c1-9583-03dfe1ecb77f
  state: Active
  version: $LATEST
```

But the spec in the CR is still the old config and the AWS console still shows the old log group:
```yaml
spec:
...
  loggingConfig:
    logFormat: Text # Should be JSON
    logGroup: /aws/lambda/myfunction # Should be /aws/lambda/mygroup
...
```
Versions:
```bash
$ oc -n devops-ack-operator get csv  | grep ack
ack-cloudwatchlogs-controller.v1.0.9       AWS Controllers for Kubernetes - Amazon CloudWatch Logs   1.0.9                     ack-cloudwatchlogs-controller.v1.0.8     Succeeded
ack-eventbridge-controller.v1.0.22         AWS Controllers for Kubernetes - Amazon EventBridge       1.0.22                    ack-eventbridge-controller.v1.0.21       Succeeded
ack-lambda-controller.v1.7.0               AWS Controllers for Kubernetes - Amazon Lambda            1.7.0                     ack-lambda-controller.v1.6.3             Succeeded
ack-sqs-controller.v1.1.11                 AWS Controllers for Kubernetes - Amazon SQS               1.1.11                    ack-sqs-controller.v1.1.10               Succeeded
$ oc version
Client Version: 4.12.42
Kustomize Version: v4.5.7
Server Version: 4.12.47
Kubernetes Version: v1.25.16+5c97f5b
```
Also note, I have an issue [open](https://github.com/aws-controllers-k8s/community/issues/2294) for similar behavior when I try to update ENV VARs. Maybe this is a version "incompatibility" situation?
