### ISSUE TITLE
S3 bucket doesn't populate ARN in the status field

### ISSUE THREAD

**Issue by candonov** [aws-controllers-k8s/community#2124]
**Describe the bug**
When creating an s3 bucket with the ACK s3 controller, the controller should populate the bucket ARN under `status.ackResourceMetadata.arn`.

**Steps to reproduce**
Installed s3-controller v1.0.13 with AmazonS3FullAccess IRSA policy from [the addons repo](https://github.com/aws-ia/terraform-aws-eks-ack-addons/tree/main).

Created a test bucket:
```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: test-95608350843749
spec:
  name: test-95608350843749
```
Bucket gets created but `arn` is not populated in the status:
```
status:
  ackResourceMetadata:
    ownerAccountID: "111122223333"
    region: us-east-1
  conditions:
  - lastTransitionTime: "2024-08-08T01:08:53Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  location: /test-95608350843749
```
**Expected outcome**
A concise description of what you expected to happen.
The bucket ARN to be populated.
```
status:
  ackResourceMetadata:
    arn: <arn of the bucket>
    ownerAccountID: "111122223333"
    region: us-east-1
  conditions:
  - lastTransitionTime: "2024-08-08T01:08:53Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  location: /test-95608350843749
```
**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? yes, 1.30
* AWS service targeted (S3, RDS, etc.) S3
