### ISSUE TITLE
DynamoDB controller doesn't work with KMS aliases, requires ARN due to how AWS API returns ARN

### ISSUE THREAD

**Issue by jbilliau-rcd** [aws-controllers-k8s/community#2136]
**Describe the bug**
Creating a `Table` object like below:

```
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: dev-302040-test-whale-orange
  labels:
    helm-chart-release: aws-resources-0.0.1
    release: helmatest-ack
    app-id: "302040"
    app: dev-test-whale
    environment: dev
    deploy-date: "2024-08-15"
  annotations:
    services.k8s.aws/deletion-policy: delete
spec:
  tableName: dev-302040-test-whale-orange
  attributeDefinitions:
    - attributeName: Bill
      attributeType: S
  keySchema:
    - attributeName: Bill
      keyType: HASH
  sseSpecification:
    enabled: true
    sseType: KMS
    kmsMasterKeyID: alias/dev-302040-test-whale-orange
```

results in the following error endlessly, never resolving:

  conditions:
    - message: >-
        cannot update table LimitExceededException: Subscriber limit exceeded:
        Encryption mode changes are limited in the 24h window ending at
        2024-08-16T13:54:50.348Z. After the first 4 change, each subsequent
        change in the same window can be performed at most once every 21600
        seconds. Number of updates today: 4. Last change at
        2024-08-15T13:56:28.094Z. Next changes can be made at
        2024-08-15T19:56:28.094Z.
      status: 'True'
      type: ACK.Recoverable

This appears to be the same issue that plagued crossplane, due to how the AWS API always returns an ARN on create or update calls. https://github.com/crossplane-contrib/provider-aws/pull/1907

I suspect ACK needs the same fix.

**Steps to reproduce**

Create a `Table` object using a CMK KMS like below:

```
sseSpecification:
    enabled: true
    sseType: KMS
    kmsMasterKeyID: alias/dev-302040-test-whale-orange
```

But if you switch `kmsMasterKeyID` to the ARN of the key, it instantly resolves and fixes itself.

**Expected outcome**
`Table` should support KMS Aliases like a lot of the other ACK resources do. Otherwise, you can't create the KMS key and use it to encrypt objects in the same Helm chart/kubectl apply due to the ARN not being known yet.

**Environment**

Any.

* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? Yes, 1.28
* AWS service targeted (S3, RDS, etc.) Dynamodb

**Comment by michaelhtm** [comment]
Hey @jbilliau-rcd, I attempted this, and you are right, that issue persists. It seems like the DynamoDB api accepts KMS alias as input, but when you call describe it returns the ARN. I was not able to retrieve the KMS alias from the ARN...In ACK we need to do a Read operation to see if there are any diffs and check whether we need to call an update or not, which is what is happening in your case. 

[kro](https://kro.run/) is solving this problem tho, where you can use CEL to retrieve the kms ARN and use it on your table!
I hope that helps

**Comment by jbilliau-rcd** [comment]
hey @michaelhtm , thanks for responding. Is this something that will be fixed in the dynamodb controller itself? We already have ACK resources wrapped up in our own helm chart, didn't really want to use `vro` to get around an issue that would preferably be fixed in the controller itself.

**Comment by michaelhtm** [comment]
Hey @jbilliau-rcd, I have a PR that allows you to use references for the KMSKeyID, this is a Gitops friendly approach as you just need to specify the key resource name in your table CR manifest. Here's an example:

```yaml
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Key
metadata:
  name: myk
spec:
  description: "Key created by ACK tests"

---
# Table used to test multiple interfering updates at once
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: mytable
spec:
  tableName: mytable
  billingMode: PAY_PER_REQUEST
  tableClass: STANDARD
  attributeDefinitions:
    - attributeName: Bill
      attributeType: S
    - attributeName: Total
      attributeType: S
  keySchema:
    - attributeName: Bill
      keyType: HASH
    - attributeName: Total
      keyType: RANGE
  sseSpecification:
    enabled: true
    sseType: KMS
    kmsMasterKeyRef:
      from:
        name: myk
```
