### ISSUE TITLE
Adopted Resource from SQS doesn't register queueURL correctly

### ISSUE THREAD

**Issue by omri-shilton** [aws-controllers-k8s/community#2138]
**Describe the bug**
Adopted Resource from SQS doesn't register queueURL correctly, it registers the queue name in the queueURL field.

**Steps to reproduce**
adopt an existing queue with adoptedresource 
look at the status of the newly created queue resource queueUrl field.
see that it is not in the url format

**Expected outcome**
queueUrl field to be in the url format : https://sqs.region.amazonaws.com/account-id/queue-name

* Kubernetes version - 1.28
* Using EKS (yes/no), if so version?  - yes 1.28
* AWS service targeted (S3, RDS, etc.) -  SQS

**Comment by a-hilaly** [comment]
Hi @omri-shilton - i am able to adopt an SQS using:
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-my-existing-queue
spec:  
  aws:
    nameOrID: https://sqs.us-west-2.amazonaws.com/095708837592/ack-queue
  kubernetes:
    group: sqs.services.k8s.aws
    kind: Queue
    metadata:
      name: ack-queue
      namespace: default
```
