### ISSUE TITLE
Recommended IAM Policy for EKS Controller is missing IAM permissions for nodegroup

### ISSUE THREAD

**Issue by xiangyanw** [aws-controllers-k8s/community#2164]
**Describe the bug**
I try to create an EKS nodegroup by the ACK EKS controller. But it failed with below error:

> Message_: \"User: arn:aws:sts::<account id>:assumed-role/ack-eks-controller/1725526945619799416 is not authorized to perform: iam:ListAttachedRolePolicies on resource: role xxxx-NodeInstanceRole-UxdKM7tTdtF4 because no identity-based policy allows the iam:ListAttachedRolePolicies action\"

> Message_: \"You are not authorized to perform ec2:DescribeSubnets. User: arn:aws:sts::<account id>:assumed-role/ack-eks-controller/1725526945619799416 is not authorized to perform: ec2:DescribeSubnets because no identity-based policy allows the ec2:DescribeSubnets action\"

**Steps to reproduce**
1. Install ACK EKS controller;
2. Configure IAM role for service account following this doc: https://aws-controllers-k8s.github.io/community/docs/user-docs/irsa/
3. Create an EKS cluster;
4. Create a nodegroup;
```
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: ack-eks-nodegroup
spec:
  name: ack-eks-nodegroup-1
  clusterName: ack-eks-cluster
  nodeRole: <IAM role ARN>
  scalingConfig:
    desiredSize: 1
    maxSize: 2
    minSize: 0
  subnets:
    - subnet-1
    - subnet-2
```

**Expected outcome**
The nodegroup is created without any issue

**Environment**

* Kubernetes version 1.30
* Using EKS (yes/no), if so version? EKS 1.30
* AWS service targeted (S3, RDS, etc.) EKS

**What needs fixing?**
Recommended Policy needs to add:
- iam:ListAttachedRolePolicies
- ec2:DescribeSubnets

**What is the URL of the document?**
https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/iam/recommended-inline-policy

**Comment by gecube** [comment]
Hi!

I used the next manifests

```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: eks-production-role
  namespace: infra-production
spec:
  name: eks-production-role
  assumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"eks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  policies:
    - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
  inlinePolicies:
    PolicyCloudWatchMetrics: >
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "cloudwatch:PutMetricData"
            ],
            "Resource": "*",
            "Effect": "Allow"
          }
        ]
      }
#    PolicyELBPermissions: >
#      {
#        "Version": "2012-10-17",
#        "Statement": [
#          {
#            "Action": [
#              "ec2:DescribeAccountAttributes",
#              "ec2:DescribeAddresses",
#              "ec2:DescribeInternetGateways"
#            ],
#            "Resource": "*",
#            "Effect": "Allow"
#          }
#        ]
#      }
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: eks-production-nodegroup-role
  namespace: infra-production
spec:
  name: eks-production-nodegroup-role
  assumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  policies:
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  inlinePolicies: {}
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: production
  namespace: infra-production
spec:
  name: production
  roleARN: arn:aws:iam::*****:role/eks-production-role
  logging:
    clusterLogging:
      - enabled: true
        types:
          - api
          - audit
          - authenticator
          - controllerManager
          - scheduler
  resourcesVPCConfig:
    endpointPrivateAccess: true
    endpointPublicAccess: false
    subnetRefs:
      - from:
          name: production-private-eu-west-2a
      - from:
          name: production-private-eu-west-2b
  tags:
    Name: production
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng-20230810
  namespace: infra-production
spec:
  name: production-main-ng-20230810
  clusterName: production
  diskSize: 100
  subnetRefs:
  - from:
      name: production-private-eu-west-2a
  - from:
      name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 0
    maxSize: 10
    desiredSize: 0
  instanceTypes:
    - m5.4xlarge
  releaseVersion: 1.27.3-20230728
  taints:
    - effect: NO_SCHEDULE
      key: com.zodiamarkets.role
      value: old-nodegroup
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: OpenIDConnectProvider
metadata:
  name: production
  namespace: infra-production
spec:
  url: https://oidc.eks.eu-west-2.amazonaws.com/id/*****
  clientIDs:
    - sts.amazonaws.com
  thumbprints:
  - *****
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng-20240323-b
  namespace: infra-production
spec:
  name: production-main-ng-20240323-b
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 10
    maxSize: 10
    desiredSize: 10
  instanceTypes:
    - m5.4xlarge
#  releaseVersion: 1.27.3-20230728
  amiType: BOTTLEROCKET_x86_64
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng-20240506-a
  namespace: infra-production
spec:
  name: production-main-ng-20240506-a
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2a
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 10
    desiredSize: 1
  instanceTypes:
    - m5.4xlarge
  #  releaseVersion: 1.27.3-20230728
  amiType: BOTTLEROCKET_x86_64
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-main-ng-20240506-c
  namespace: infra-production
spec:
  name: production-main-ng-20240506-c
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2c
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 10
    desiredSize: 1
  instanceTypes:
    - m5.4xlarge
  amiType: BOTTLEROCKET_x86_64
```

```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: eks-production-ebs-csi-driver-role
  namespace: infra-production
spec:
  name: eks-production-ebs-csi-driver-role
  assumeRolePolicyDocument: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::****:oidc-provider/oidc.eks.eu-west-2.amazonaws.com/id/****"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              "oidc.eks.eu-west-2.amazonaws.com/id/****:aud": "sts.amazonaws.com",
              "oidc.eks.eu-west-2.amazonaws.com/id/****:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
            }
          }
        }
      ]
    }
  policies:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  inlinePolicies: {}
```

```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: eks-production-loadbalancercontroller-role
  namespace: infra-production
spec:
  name: eks-production-loadbalancercontroller-role
  assumeRolePolicyDocument: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::*****:oidc-provider/oidc.eks.eu-west-2.amazonaws.com/id/*****"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              "oidc.eks.eu-west-2.amazonaws.com/id/*****:aud": "sts.amazonaws.com",
              "oidc.eks.eu-west-2.amazonaws.com/id/*****:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller"
            }
          }
        }
      ]
    }
  policies: []
  inlinePolicies:
    AWSLoadBalancerControllerIAMPolicy: >
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "iam:CreateServiceLinkedRole"
            ],
            "Resource": "*",
            "Condition": {
              "StringEquals": {
                "iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:DescribeAccountAttributes",
              "ec2:DescribeAddresses",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeInternetGateways",
              "ec2:DescribeVpcs",
              "ec2:DescribeVpcPeeringConnections",
              "ec2:DescribeSubnets",
              "ec2:DescribeSecurityGroups",
              "ec2:DescribeInstances",
              "ec2:DescribeNetworkInterfaces",
              "ec2:DescribeTags",
              "ec2:GetCoipPoolUsage",
              "ec2:DescribeCoipPools",
              "elasticloadbalancing:DescribeLoadBalancers",
              "elasticloadbalancing:DescribeLoadBalancerAttributes",
              "elasticloadbalancing:DescribeListeners",
              "elasticloadbalancing:DescribeListenerCertificates",
              "elasticloadbalancing:DescribeSSLPolicies",
              "elasticloadbalancing:DescribeRules",
              "elasticloadbalancing:DescribeTargetGroups",
              "elasticloadbalancing:DescribeTargetGroupAttributes",
              "elasticloadbalancing:DescribeTargetHealth",
              "elasticloadbalancing:DescribeTags"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "cognito-idp:DescribeUserPoolClient",
              "acm:ListCertificates",
              "acm:DescribeCertificate",
              "iam:ListServerCertificates",
              "iam:GetServerCertificate",
              "waf-regional:GetWebACL",
              "waf-regional:GetWebACLForResource",
              "waf-regional:AssociateWebACL",
              "waf-regional:DisassociateWebACL",
              "wafv2:GetWebACL",
              "wafv2:GetWebACLForResource",
              "wafv2:AssociateWebACL",
              "wafv2:DisassociateWebACL",
              "shield:GetSubscriptionState",
              "shield:DescribeProtection",
              "shield:CreateProtection",
              "shield:DeleteProtection"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:AuthorizeSecurityGroupIngress",
              "ec2:RevokeSecurityGroupIngress"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:CreateSecurityGroup"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:CreateTags"
            ],
            "Resource": "arn:aws:ec2:*:*:security-group/*",
            "Condition": {
              "StringEquals": {
                "ec2:CreateAction": "CreateSecurityGroup"
              },
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:CreateTags",
              "ec2:DeleteTags"
            ],
            "Resource": "arn:aws:ec2:*:*:security-group/*",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:AuthorizeSecurityGroupIngress",
              "ec2:RevokeSecurityGroupIngress",
              "ec2:DeleteSecurityGroup"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:CreateLoadBalancer",
              "elasticloadbalancing:CreateTargetGroup"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:CreateListener",
              "elasticloadbalancing:DeleteListener",
              "elasticloadbalancing:CreateRule",
              "elasticloadbalancing:DeleteRule"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:AddTags",
              "elasticloadbalancing:RemoveTags"
            ],
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:AddTags",
              "elasticloadbalancing:RemoveTags"
            ],
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:AddTags"
            ],
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ],
            "Condition": {
              "StringEquals": {
                "elasticloadbalancing:CreateAction": [
                  "CreateTargetGroup",
                  "CreateLoadBalancer"
                ]
              },
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:ModifyLoadBalancerAttributes",
              "elasticloadbalancing:SetIpAddressType",
              "elasticloadbalancing:SetSecurityGroups",
              "elasticloadbalancing:SetSubnets",
              "elasticloadbalancing:DeleteLoadBalancer",
              "elasticloadbalancing:ModifyTargetGroup",
              "elasticloadbalancing:ModifyTargetGroupAttributes",
              "elasticloadbalancing:DeleteTargetGroup"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:RegisterTargets",
              "elasticloadbalancing:DeregisterTargets"
            ],
            "Resource": "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:SetWebAcl",
              "elasticloadbalancing:ModifyListener",
              "elasticloadbalancing:AddListenerCertificates",
              "elasticloadbalancing:RemoveListenerCertificates",
              "elasticloadbalancing:ModifyRule"
            ],
            "Resource": "*"
          }
        ]
      }
```
