### ISSUE TITLE
Cloudfront - delete a distribution which is not disabled 

### ISSUE THREAD

**Issue by MalibuKoKo** [aws-controllers-k8s/community#2168]
**Describe the bug**
message: "DistributionNotDisabled: The distribution you are trying to delete has not been disabled.\n\tstatus code: 409,

**Steps to reproduce**
Try to delete distribution resource which is enabled
```yaml
apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: Distribution
metadata:
  name: foo
spec:
  distributionConfig:
    enabled: true
    ...
```

**Expected outcome**
Controller have to disable it and delete it

**Environment**

* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? yes, v1.28.5-eks-5e0fdde
* AWS service targeted (S3, RDS, etc.) : cloudfront
