### ISSUE TITLE
route53-controller unable to find recordset upon adoption

### ISSUE THREAD

**Issue by mqhenning** [aws-controllers-k8s/community#2187]
**Describe the bug**
When using an AdoptedResource to adopt a route53 RecordSet, e.g. a `CNAME`, route53-controller is unable to adopt the record, throwing a `resource not found` error. Using version `0.0.17`.

Stack trace:
```
{"level":"error","ts":"2024-10-08T16:23:39.266Z","msg":"Reconciler error","controller":"adoptedresource","controllerGroup":"services.k8s.aws","controllerKind":"AdoptedResource","AdoptedResource":{"name":"adopt-test-cname","namespace":"ack-system"},"namespace":"ack-system","name":"adopt-test-cname","reconcileID":"0245fc92-4704-4d0c-9e2b-de1721e9ce90","error":"resource not found","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324
 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261
 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```

**Steps to reproduce**
Create a route53 record, say via the AWS console. Create an adopted resource (using it's name, zoneID, recordType to specify it):
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: test-adopted-recordset
spec:
  aws:
    nameOrID: <record name, e.g. test-record.organization.tld.>
    additionalKeys:
      hostedZoneID: <Zone ID, e.g Z00000000000>
      recordType: <type, e.g. CNAME>
  kubernetes:
    group: route53.services.k8s.aws
    kind: RecordSet
    metadata:
      name: <name, e.g. test-record.organization.tld.>
```

**Expected outcome**
The resource is adopted, and an ack-controlled resource is created.

**Environment**

* Kubernetes version 1.30
* Using EKS (yes/no), if so version? yes, 1.30
* AWS service targeted (S3, RDS, etc.) Route53

**Comment by michalschott** [comment]
Having the same issue

**Comment by michaelhtm** [comment]
Hello @michalschott @mqhenning 
Is this do you still have this issue? We also have a new way of adopting resources if you'd like to try that one
https://aws-controllers-k8s.github.io/community/docs/user-docs/features/#resourceadoption

**Comment by mqhenning** [comment]
> Hello [@michalschott](https://github.com/michalschott) [@mqhenning](https://github.com/mqhenning) Is this do you still have this issue? We also have a new way of adopting resources if you'd like to try that one https://aws-controllers-k8s.github.io/community/docs/user-docs/features/#resourceadoption

Thanks for following up! I'm curious, how would I use this to adopt a resource? The docs currently say it's only available for the s3 controller. Is that no longer the case?

**Comment by michaelhtm** [comment]
@mqhenning 
The docs are outdated, there's a PR that will update it soon! The feature is supported across all controllers

**Comment by mqhenning** [comment]
That's good to know. So to adopt (say) a CNAME in zone `Z00111222333` for a zone named `example.cloud` and a record for `foo.example.cloud` would I do something like:

```
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: my-recordset
  annotations:
    services.k8s.aws/adoption-policy: "adopt"
    services.k8s.aws/adoption-fields:  |
        {
           "name": "foo",
           "recordType": "CNAME",
           "hostedZoneID": "Z00111222333"
        }
```

**Comment by michaelhtm** [comment]
It looks correct, except you'd need the recordSet ID instead of name.
```yaml
apiVersion: route53.services.k8s.aws/v1alpha1
kind: RecordSet
metadata:
  name: my-recordset
  annotations:
    services.k8s.aws/adoption-policy: "adopt"
    services.k8s.aws/adoption-fields:  |
        {
           "id": "foo",
           "recordType": "CNAME",
           "hostedZoneID": "Z00111222333"
        }
```
