### ISSUE TITLE
Error when trying to create sns subscription with lambda protocol

### ISSUE THREAD

**Issue by HuyDangSotatek** [aws-controllers-k8s/community#2192]
**Describe the bug**
Error when trying to create sns subscription with lambda protocol through argocd although there is no RawMessageDelivery in my manifest
```
InvalidParameter: Invalid parameter: Delivery protocol [lambda] does not support raw message delivery.\n\tstatus code: 400
```

**Steps to reproduce**
Use argocd to apply this
```
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    services.k8s.aws/deletion-policy: retain
  labels:
    argocd.argoproj.io/instance: Label
  name: SubscriptionName
  namespace: NameSpace
spec:
  endpoint: >-
    arn:aws:lambda:region:xxx:function:FunctionName
  filterPolicy: |-
    {
      "tags": [
        "TAG"
      ]
    }
  filterPolicyScope: MessageAttributes
  protocol: lambda
  topicRef:
    from:
      name: TopicName
```

**Expected outcome**
Expected no errors

* Kubernetes version
* Using EKS (yes/no), if so version? 1.30
* AWS service targeted (S3, RDS, etc.) : SNS
