### ISSUE TITLE
SNS subscription resource is created but then fails when the rawMessageDelivery variable is not set

### ISSUE THREAD

**Issue by daniduhnev1** [aws-controllers-k8s/community#2195]
## **Describe the bug**
SNS subscriptions are created successfully via the ACK SNS controller and initially the status shows healthy. However, if the `rawMessageDelivery` variable is not explicitly in the yaml config of the subscription after a period of a few minutes the Kubernetes resources becomes in errored state and can no longer be managed by ACK. The error states looks like this:
```
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:sns:us-west-2:<account-id>:my-ack-topic:769088a7-70f2-4b78-b1d0-fde29416adde
    Owner Account ID:  <account-id>
    Region:            us-west-2
  Conditions:
    Message:                       InvalidParameter: Invalid parameter: RawMessageDelivery: Invalid value [null]. Must be true or false.
                                   status code: 400, request id: 615535da-d870-5432-a050-6a537ada93f9
    Status:                        True
    Type:                          ACK.Terminal
    Last Transition Time:          2024-10-16T11:15:54Z
    Message:                       Resource not synced
    Reason:                        resource is in terminal condition
    Status:                        False
    Type:                          ACK.ResourceSynced
  Confirmation Was Authenticated:  true
  Pending Confirmation:            false
```

This error is fixed if and when the `rawMessageDelivery` variable is explicitly set as `true` or `false`. However, it is my understanding that this variable should default to `false` and does not have to be explicitly set. For example, see test resource here: https://github.com/aws-controllers-k8s/sns-controller/blob/main/test/e2e/resources/subscription_with_refs.yaml

## **Steps to reproduce**
Create an example topic, queue and subscription:
```
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Topic
metadata:
  name: my-ack-topic
spec:
  displayName: "Test topic"
  name: my-ack-topic
---
apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: my-ack-queue
spec:
  queueName: my-ack-queue
  delaySeconds: "0"
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: my-ack-sub
spec:
  topicARN: "arn:aws:sns:us-west-2:<account-id>:my-ack-topic"
  endpoint: "arn:aws:sqs:us-west-2:<account-id>:my-ack-queue"
  protocol: sqs
```
Observe that the subscription is created successfully and that we are able to use the topic to send messages to the queue. Observe also that in a few minutes, while the subscription on AWS remains functioning, the Kubernetes resources fails with error `InvalidParameter: Invalid parameter: RawMessageDelivery: Invalid value [null]. Must be true or false. Status code: 400, request id: <request-id>`

## **Expected outcome**
We expect to have a default `false` value of `rawMessageDelivery`, and to not have to be set explicitly in the yaml manifest. Please confirm if it is the case that this variable should have a default value set. 

## **Environment**

* Kubernetes version - 1.30
* Using EKS (yes/no), if so version?  - yes, eks.8
* AWS service targeted (S3, RDS, etc.) - SNS Subscription
