### ISSUE TITLE
ACK ElastiSearch: add valkey test suite

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2199]
Good day!

I want ask to add to the test suite instances with `valkey` engine. Otherwise it is relatively difficult to find out the proper settings. I am talking about the next repo: https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/test/e2e/resources/usergroup.yaml

I was able to prepare valkey instance with the next manifests:

```yaml
---
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheSubnetGroup
metadata:
  name: valkey-subnet
spec:
  cacheSubnetGroupName: valkey-subnet
  cacheSubnetGroupDescription: valkey-subnet
  subnetIDs:
  - subnet-*****
  - subnet-*****
  - subnet-*****
---
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: valkeyapp
spec:
  cacheSubnetGroupName: valkey-subnet
  transitEncryptionEnabled: false
  engine: valkey
  description: valkeyapp
  replicationGroupID: valkeyapp
  cacheNodeType: cache.m6g.2xlarge
  securityGroupRefs:
    - from:
        name: limit-valkey-to-subnet
  preferredCacheClusterAZs:
    - 'eu-west-2c'
```
