### ISSUE TITLE
Document ACK Controllers feature flags

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#2203]
The ACK project currently has the following feature flags defined in the helm charts:

```yaml
# Configuration for feature gates.  These are optional controller features that
# can be individually enabled ("true") or disabled ("false") by adding key/value
# pairs below.
featureGates:
  # Enables the Service level granularity for CARM. See https://github.com/aws-controllers-k8s/community/issues/2031
  ServiceLevelCARM: false
  # Enables the Team level granularity for CARM. See https://github.com/aws-controllers-k8s/community/issues/2031
  TeamLevelCARM: false
  # Enable ReadOnlyResources feature/annotation. 
  ReadOnlyResources: false
```

we need to expose information about these feature flag on the ACK documentation website, including:
- A brief description of each feature flag
- The current stage of the feature (`alpha`, `beta`, `GA`, etc.)
- Relevant issue or PR links for more context
- Plans for the feature's future (timeline for promotion, deprecation, etc...)
