### ISSUE TITLE
[EKS controller]: can't change a size of instance in the node group

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2210]
Good day!

I had an node group:

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-fix-ng-20241010-b
  namespace: infra-production
spec:
  name: production-fix-ng-20241010-b
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 1
    desiredSize: 1
  instanceTypes:
    - m5.large
  taints:
    - key: "node-role.kubernetes.io/fix"
      value: ""
      effect: "NO_SCHEDULE"
  labels: {}
  amiType: BOTTLEROCKET_x86_64
```

Then I am changing the instance type:

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-fix-ng-20241010-b
  namespace: infra-production
spec:
  name: production-fix-ng-20241010-b
  clusterName: production
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2b
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 1
    desiredSize: 1
  instanceTypes:
    - m5.large
  taints:
    - key: "node-role.kubernetes.io/fix"
      value: ""
      effect: "NO_SCHEDULE"
  labels: {}
  amiType: BOTTLEROCKET_x86_64
```

The node group is stuck:

```
status:
  ackResourceMetadata:
    arn: 'arn:aws:eks:eu-west-2:*****:nodegroup/production/production-fix-ng-20241010-b/48c98b02-726a-81e5-2958-d89886c0a63b'
    ownerAccountID: '*****'
    region: eu-west-2
  conditions:
    - lastTransitionTime: '2024-11-10T13:10:06Z'
      status: 'True'
      type: ACK.ReferencesResolved
    - lastTransitionTime: '2024-11-10T13:10:06Z'
      message: Nodegroup is currently being updated
      status: 'False'
      type: ACK.ResourceSynced
    - message: 'nodegroup has started asynchronously updating, cannot be modified until ''ACTIVE'''
      status: 'True'
      type: ACK.Recoverable
  createdAt: '2024-11-10T12:20:41Z'
  health: {}
  modifiedAt: '2024-11-10T13:09:56Z'
  resources:
    autoScalingGroups:
      - name: eks-production-fix-ng-20241010-b-48c98b02-726a-81e5-2958-d89886c0a63b
  status: ACTIVE
```
