### ISSUE TITLE
Lambda Function zipFile Error

### ISSUE THREAD

**Issue by urton** [aws-controllers-k8s/community#2223]
When trying to use Python code inline via `zipFile`, I get the following error:
```
The Function "myfunction" is invalid: spec.code.zipFile: Invalid value: "def lambda_handler(event, context):\n    print('hello world')\n": spec.code.zipFile in body must be of type byte: "def lambda_handler(event, context):\n    print('hello world')\n"
```
My Function YAML:
```
---
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: myfunction
  namespace: devops-automation
spec:
  code: 
    zipFile: |
      def lambda_handler(event, context):
          print('hello world')
  environment: 
    variables: {}
  fileSystemConfigs:
  - arn: "arn:aws:elasticfilesystem:us-west-1:*****:access-point/fsap-*****"
    localMountPath: "/mnt/efs"
  handler: "index.lambda_handler"
  memorySize: 256
  name: myfunction
  publish: false
  reservedConcurrentExecutions: 100
  role: "arn:aws:iam::*****:role/*****"
  runtime: python3.12
  tags: {}
  timeout: 30
  vpcConfig: 
    securityGroupIDs:
    - sg-*****
    subnetIDs:
    - subnet-*****
    - subnet-*****
```

**Comment by knottnt** [comment]
@urton The `zipFile` field expects a base64 encoding of the zip file containing your code package. Here's an example of deploying a Lambda function with `zipFile`:

1. Write the python code to a file
```bash
cat <<EOF > app.py
def lambda_handler(event, context):
    return 'hello world'
EOF
```

2. Zip the python file
```bash
zip -r function.zip app.py
```

3. Base64 encode the zip file
```bash
cat function.zip | base64
```

We can then the use the resulting base64 encoding in our Lambda function manifest

```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: sample-lambda
  annotations:
    services.k8s.aws/region: us-west-2
spec:
 name: sample-lambda
 packageType: Zip
 runtime: python3.13
 handler: app.lambda_handler
 code:
    zipFile: UEsDBAoAAAAAAHl/21qeD5FAPQAAAD0AAAAGABwAYXBwLnB5VVQJAANlIl9oZiJfaHV4CwABBPcBAAAEFAAAAGRlZiBsYW1iZGFfaGFuZGxlcihldmVudCwgY29udGV4dCk6CiAgICByZXR1cm4gJ2hlbGxvIHdvcmxkJwpQSwECHgMKAAAAAAB5f9tang+RQD0AAAA9AAAABgAYAAAAAAABAAAApIEAAAAAYXBwLnB5VVQFAANlIl9odXgLAAEE9wEAAAQUAAAAUEsFBgAAAAABAAEATAAAAH0AAAAAAA==
 role: "arn:aws:iam::*****:role/*****"
```
