### ISSUE TITLE
AWS ACK Route53 resolver controller - Cannot adopt a ResolverEndpoint

### ISSUE THREAD

**Issue by stefanescualexandrumihai** [aws-controllers-k8s/community#2240]
Route53resolver-controller version: `1.0.2`
The route53 controller has `featureGates.ResourceAdoption` value set to `true`.
Kubernetes version `v1.29.6`.

When trying to apply the following spec:

```
apiVersion: route53resolver.services.k8s.aws/v1alpha1
kind: ResolverEndpoint
metadata:
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-fields: |
      {
        "id": "rslvr-out-xxxxx"
      }
    services.k8s.aws/adoption-policy: adopt
  name: resolverendpoint-xxxx
  namespace: namespace-xxxx
```

I'm receiving the message: "Reference resolution failed", with the reason: "Resource reference wrapper or ID required: SecurityGroupIDs, SecurityGroupRefs"

```
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:route53resolver:us-east-1:account-id-xxxx:resolver-endpoint/rslvr-out-xxxx
    Owner Account ID:  account-id-xxxx
    Region:            us-east-1
  Conditions:
    Last Transition Time:  2025-01-17T08:23:40Z
    Message:               Reference resolution failed
    Reason:                resource reference wrapper or ID required: SecurityGroupIDs,SecurityGroupRefs
    Status:                Unknown
    Type:                  ACK.ReferencesResolved
  Creation Time:           2024-12-10T08:44:51.711386879Z
  Creator Request ID:      ab72b914-1501-457a-8f94-43e997b52976
  Host VPCID:              vpc-xxxx
  Id:                      rslvr-out-xxxx
  Ip Address Count:        3
  Modification Time:       2024-12-10T08:47:04.307Z
  Status:                  OPERATIONAL
  Status Message:          This Resolver Endpoint is operational.
```

Then, if I add some information to the spec of the object (e.g., the correct security group), the object is marked as ACK.ResourceSynced. The AWS resource is managed by the ACK controller without creating a new one.
