### ISSUE TITLE
AWS Events Rule not a Supported EventSourceMapping

### ISSUE THREAD

**Issue by urton** [aws-controllers-k8s/community#2250]
When trying to add an EventBridge Rule as a Lambda EventSourceMapping, I get the following error:
```
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "1f6b5069-a034-4c80-abcb-931fce63775c"
  },
  Message_: "Unrecognized event source. Unsupported source arn : arn:aws:events:us-west-1:*****:rule/my-rule",
  Type: "User"
}
```
And here's my ESM YAML:
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: EventSourceMapping
metadata:
  name: my-event-source-mapping
  namespace: my-namespace
spec:
  enabled: true
  eventSourceARN: arn:aws:events:us-west-1:*****:rule/my-rule
  functionName: my-function
```
What is the recommended way to add the required Lambda permission to an Event Rule? Hopefully I am missing something obvious...
