### ISSUE TITLE
Issues adopting MSK configuration & cluster

### ISSUE THREAD

**Issue by kkopuru** [aws-controllers-k8s/community#2254]
We have existing MSK clusters provisioned using service broker that we are trying to adopt. Adoption of MSK configuration & cluster is failing with following error
```
status:
  conditions:
  - message: 'Configuration.kafka.services.k8s.aws "platformqa-ndp-msk-conf" is invalid:
      spec.serverProperties: Required value'
    status: "False"
    type: ACK.Adopted
```
```
status:
  conditions:
  - message: 'Cluster.kafka.services.k8s.aws "platformqa-ndp-msk" is invalid: [spec.kafkaVersion:
      Required value, spec.name: Required value]'
    status: "False"
    type: ACK.Adopted
```

**Environment**
- AWS EKS: 1.29
- kafka-controller: 1.0.1
