### ISSUE TITLE
Maintenance window updates

### ISSUE THREAD

**Issue by nmvk** [aws-controllers-k8s/community#229]
**Describe the bug**
Elasticache allows customers to perform some modifications in maintenance window. This can be done by not specifying `--apply-immediately`.

Generated code for the update does not seem to have a way to accept this parameter. So when I requested to update a replication group from ACK the request was accepted and ACK describe showed modification as applied but modification was not applied in Elasticache as it was going to be updated during maintenance window.

**Steps to reproduce**
Create a replication group with t3.micro.

```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test-rg
spec:
    engine: redis 
    replicationGroupID: test-k8
    replicationGroupDescription: test
    automaticFailover: true
    cacheNodeType: cache.t3.micro
    numNodeGroups: 3
    replicasPerNodeGroup: 2
```
Update the instance type to t3.medium.
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test-rg
spec:
    engine: redis 
    replicationGroupID: test-k8
    replicationGroupDescription: test
    automaticFailover: true
    cacheNodeType: cache.t3.medium
    numNodeGroups: 3
    replicasPerNodeGroup: 2
```
**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version : 1.17
* Using EKS (yes/no), if so version? Yes
* AWS service targeted : Elasticache

**Comment by jaypipes** [comment]
I had a chat with @nmvk about this on Friday. I think to make things simpler, ACK would probably not want to support the maintenance window feature and instead always use the `--apply-immediately` flag. It's going to be "interesting" to figure out how we handle status polling for both RDS and Elasticache resources already, and having to handle another unique maintenance window technique would be difficult.

**Comment by nmvk** [comment]
We would require a way to overwrite the value of input parameter in this case. My proposal is to allow specifying the default values for an operations parameter in `generator.yaml`

```
resources:
  CacheSubnetGroup:
    exceptions:
      codes:
        404: CacheSubnetGroupNotFoundFault
operations:
  ModifyReplicationGroup:
    default_values:
      ApplyImmediately: true
```
