### ISSUE TITLE
ACK EC2 Controller VPCEndpoint doesn't modify the aws object based on spec definition

### ISSUE THREAD

**Issue by stefanescualexandrumihai** [aws-controllers-k8s/community#2296]
AWS ACK EC2 Controller version : 1.3.1
The ec2 controller has featureGates.ResourceAdoption value set to true.
Kubernetes version v1.29.6

After the object adoption using the following manifest:

```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCEndpoint
metadata:
  name: astef8-sbx-va6-test
  namespace: sbx-clusters
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-fields: |
      {
        "vpcEndpointID": "vpce-xxxx"
      }
    services.k8s.aws/adoption-policy: adopt
```

The spec was populated with this:

```
spec:
  dnsOptions:
    dnsRecordIPType: ipv4
  ipAddressType: ipv4
  policyDocument: "{\n  \"Statement\": [\n    {\n      \"Action\": \"*\", \n      \"Effect\":
    \"Allow\", \n      \"Principal\": \"*\", \n      \"Resource\": \"*\"\n    }\n
    \ ]\n}"
  privateDNSEnabled: true
  serviceName: com.amazonaws.us-east-1.secretsmanager
  subnetIDs:
  - subnet-xxxx1
  - subnet-xxxx2
  - subnet-xxxx3
  tags:
  - key: services.k8s.aws/controller-version
    value: ec2-1.3.1
  - key: Name
    value: astef8-sbx-va6-test
  - key: services.k8s.aws/namespace
    value: sbx-clusters
  vpcEndpointType: Interface
  vpcID: vpc-xxxx
```

I did the same thing for a vpcendpoint of gateway type.

```
spec:
  policyDocument: '{"Version":"2008-10-17","Statement":[{"Effect":"Allow","Principal":"*","Action":"*","Resource":"*"}]}'
  privateDNSEnabled: false
  routeTableIDs:
  - rtb-xxxx1
  - rtb-xxxx2
  - rtb-xxxx3
  - rtb-xxxx4
  serviceName: com.amazonaws.us-east-1.s3
  tags:
  - key: Name
    value: astef8-sbx-va6-s3
  - key: services.k8s.aws/controller-version
    value: ec2-1.3.1
  - key: services.k8s.aws/namespace
    value: sbx-clusters
  vpcEndpointType: Gateway
  vpcID: vpc-xxxx
```

I removed the annotations: `services.k8s.aws/adoption-fields` and `services.k8s.aws/adoption-policy`.  
Afterwards, I tried to modify the subnetIDs by deleting one of them. The controller logged the following messages: `desired resource state has changed` and `updated resource` . However, in the aws console, the modification was not reflected. The same behaviour for a vpcendpoint of gateway type ( trying to delete one of the routetableIDs entries). 

Logs for the gateway type:
**`kubectl logs  -n ack-ec2-controller ack-ec2-controller-5bc4889db9-m64m6 | grep astef8-sbx-va6-s3`**

```
{"level":"info","ts":"2025-02-12T13:54:22.931Z","logger":"ackrt","msg":"desired resource state has changed","kind":"VPCEndpoint","namespace":"sbx-clusters","name":"astef8-sbx-va6-s3","account":"xxxx","role":"arn:aws:iam::xxxx:role/ack-ec2-assumedrole","region":"us-east-1","is_adopted":true,"generation":3,"diff":[{"Path":{"Parts":["Spec","RouteTableIDs"]},"A":["rtb-xxxx2","rtb-xxxx3","rtb-xxx4"],"B":["rtb-xxxx1","rtb-xxxx2","rtb-xxxx3","rtb-xxxx4"]}]}
{"level":"info","ts":"2025-02-12T13:54:22.931Z","logger":"ackrt","msg":"updated resource","kind":"VPCEndpoint","namespace":"sbx-clusters","name":"astef8-sbx-va6-s3","account":"xxxx","role":"arn:aws:iam::xxxx:role/ack-ec2-assumedrole","region":"us-east-1","is_adopted":true,"generation":3}
```

I also tried to delete a routetableid/subnetid from aws console that was present in the object's spec, but the controller didn't add it back ( checked the aws console after a while )

**Comment by rushmash91** [comment]
Hi @stefanescualexandrumihai,

Thank you for reporting this issue! To help investigate further, could you please provide a few details:

- How long did you wait after making changes in the AWS console before checking if the controller had reconciled the state? It would be helpful to know the specific timeframe.

- Could you share your `periodicResync` configuration for the EC2 controller?

**Comment by stefanescualexandrumihai** [comment]
Reconcile default resync seconds: 600
I waited for more than 10 minutes. After modifying the resources yesterday, I checked them again today and noticed a discrepancy in the AWS console: there are fewer route table IDs (2) compared to what is specified in the AWS ack VPCEndpoint spec (3). The AWS ACK EC2 controller logs messages every 10 minutes:
```
{"level":"info","ts":"2025-02-13T09:37:29.541Z","logger":"ackrt","msg":"desired resource state has changed","kind":"VPCEndpoint","namespace":"sbx-clusters","name":"astef8-sbx-va6-s3","account":"xxxx","role":"arn:aws:iam::xxxx:role/ack-ec2-assumedrole","region":"us-east-1","is_adopted":true,"generation":3,"diff":[{"Path":{"Parts":["Spec","RouteTableIDs"]},"A":["rtb-0140dfb8fc56f832f","rtb-0665e002ef4ac4e70","rtb-0b6d62b5667f017c5"],"B":["rtb-09ff09131b4a5fe21","rtb-0140dfb8fc56f832f"]}]}
{"level":"info","ts":"2025-02-13T09:37:29.542Z","logger":"ackrt","msg":"updated resource","kind":"VPCEndpoint","namespace":"sbx-clusters","name":"astef8-sbx-va6-s3","account":"xxxx","role":"arn:aws:iam::xxxx:role/ack-ec2-assumedrole","region":"us-east-1","is_adopted":true,"generation":3}
```

**Comment by stefanescualexandrumihai** [comment]
```
status:
  ackResourceMetadata:
    ownerAccountID: "xxxx"
    region: us-east-1
  conditions:
  - lastTransitionTime: "2025-02-13T10:46:09Z"
    message: Late initialization successful
    reason: Late initialization successful
    status: "True"
    type: ACK.LateInitialized
  - lastTransitionTime: "2025-02-13T10:46:09Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  creationTimestamp: "2025-02-13T10:05:10Z"
  ownerID: "xxxx"
  requesterManaged: false
  state: available
  vpcEndpointID: vpce-xxxx
```
