### ISSUE TITLE
In-place upgrade from ElastiCache Redis to Valkey cluster not working

### ISSUE THREAD

**Issue by dheitepriem** [aws-controllers-k8s/community#2299]
**Describe the bug**
The change of an existing ElastiCache ReplicationGroup from Redis to Valkey by an in-place upgrade using the [elasticache-controller](https://github.com/aws-controllers-k8s/elasticache-controller) is not working

**Steps to reproduce**
- Create an ElastiCache for Redis cluster using this manifest:
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: general-cluster
spec:
  atRestEncryptionEnabled: true
  automaticFailoverEnabled: true
  cacheNodeType: cache.t4g.small
  cacheParameterGroupName: default.redis7.cluster.on
  cacheSubnetGroupName: Subnet_Group_Name
  description: Redis cluster for general applications
  engine: redis
  multiAZEnabled: true
  numNodeGroups: 1
  preferredMaintenanceWindow: fri:00:00-fri:07:00
  replicasPerNodeGroup: 1
  replicationGroupID: general-cluster
  securityGroupIDs:
  - Security_Group_ID
  snapshotRetentionLimit: 0
  snapshotWindow: 23:00-00:00
  tags:
  - key: env
    value: dev
  - key: service
    value: core
  transitEncryptionEnabled: true
  userGroupIDs:
  - User_Group_ID
```
- Change the values of `cacheParameterGroupName` and `engine`
```
cacheParameterGroupName: default.redis7.cluster.on --> default.valkey8.cluster.on
engine: redis --> valkey
```

**Expected outcome**
The ElastiCache cluster is changed from Redis version 7 to Valkey version 8

**Actual outcome**
The ACK controller throws the error
```
  Conditions:
    Status:   True
    Type:     ACK.ResourceSynced
    Message:  InvalidParameterCombination: valkey parameter group is not applicable to engine redis
              status code: 400, request id: 2293b2a9-7938-473b-a530-ceed7a7d4074
    Status:   True
    Type:     ACK.Terminal
```

**Environment**

* ACK version `ack-elasticache-controller.0.1.0`
* Kubernetes version `1.32.0`
* Using EKS (yes/no), if so version? `Yes, eks.2`
* AWS service targeted (S3, RDS, etc.) `AWS ElastiCache`
