### ISSUE TITLE
listener.elbv2 incorrect documentation

### ISSUE THREAD

**Issue by michaelvl** [aws-controllers-k8s/community#2350]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/reference/elbv2/v1alpha1/listener/)

**Which section(s) is the issue in?**

The description of this input:

```
| | defaultActions.[].redirectConfig.statusCode
Optional | string
```

**What needs fixing?**

This input does not seem to be optional, I get the following error when not setting it:

```
  - message: |
      operation error Elastic Load Balancing v2: CreateListener, 1 validation error(s) found.
      - missing required field, CreateListenerInput.DefaultActions[0].RedirectConfig.StatusCode.
    status: "True"
    type: ACK.Recoverable
```

**Additional context**

Setting this input to `statusCode: HTTP_301` resolved to problem.

**Comment by rushmash91** [comment]
Hi @michaelvl, Thank you for reporting this documentation issue regarding the ELBv2 listener. 

To help us properly update the documentation, could you please share your YAML configuration (both the one that produced the error and the working version with statusCode: HTTP_301)?

**Comment by michaelvl** [comment]
The following `Listener` definition applied with line 10 commented out produces the error, removing the `#` from line 10 causes the resource to sync without errors:

```
apiVersion: elbv2.services.k8s.aws/v1alpha1
kind: Listener
metadata:
  name: ack-test-redir
spec:
  defaultActions:
  - type: redirect
    redirectConfig:
      port: "443"
      #statusCode: HTTP_301
  loadBalancerRef:
    from:
      name: ack-elbv2-test
  port: 80
  protocol: HTTP
```
