### ISSUE TITLE
The Route53 controller doesn't apply the adoption tags to the object and doesn't modify the tags based on the spec

### ISSUE THREAD

**Issue by stefanescualexandrumihai** [aws-controllers-k8s/community#2351]
**Describe the bug**
AWS ACK EC2 Controller version : 1.0.5
The ec2 controller has featureGates.ResourceAdoption value set to true.

The object spec tags did not reflect in the AWS object.

**Steps to reproduce**

After the object adoption using the following manifest:

```
kind: ResolverEndpoint
metadata:
  name: astef-test-adoption
  namespace: sbx-clusters
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-fields: |
      {
        "id": "rslvr-out-xxxx"
      }
    services.k8s.aws/adoption-policy: adopt
```

The spec was populated with this:

```
spec:
  direction: OUTBOUND
  ipAddresses:
  - ip: 10.10.1.8
    subnetID: subnet-1
  - ip: 10.10.12.60
    subnetID: subnet-2
  name: test-to-adopt-endpoint
  resolverEndpointType: IPV4
  securityGroupIDs:
  - sg-xxxx1
  - sg-xxxx2
  - sg-xxxx3
```

One thing that I noticed is the lack of ack controller specific tags: `services.k8s.aws/controller-version` and `services.k8s.aws/namespace`
I tried adding a tag in the object spec ( `RECONCILE_DEFAULT_RESYNC_SECONDS`: 600 ), however the tag didn't appear in the AWS console.

```
spec:
  direction: OUTBOUND
  ipAddresses:
  - ip: 10.10.1.8
    subnetID: subnet-1
  - ip: 10.10.12.60
    subnetID: subnet-2
  name: test-to-adopt-endpoint
  resolverEndpointType: IPV4
  securityGroupIDs:
  - sg-xxxx1
  - sg-xxxx2
  - sg-xxxx3
  tags:
  - key: test
     value: test
```

There were no logs related to any modifications, even though `lastTransitionTime` changed during the period I was monitoring.
 

**Expected outcome**

ACK Route53Resolver Controller tags the ack object with specific adoption tags and modifies the tags from aws, based on its spec.

**Environment**

* Kubernetes version : v1.29.6
* Using EKS (yes/no), if so version? 1.29
* AWS service targeted (S3, RDS, etc.) Route53-controller
