### ISSUE TITLE
targetgroup.elbv2 port not reconciled - immutable field?

### ISSUE THREAD

**Issue by michaelvl** [aws-controllers-k8s/community#2354]
**Describe the bug**

I created a `TargetGroup` resource, e.g.:

```
apiVersion: elbv2.services.k8s.aws/v1alpha1
kind: TargetGroup
metadata:
  name: ack-elbv2-test
spec:
  name: ack-elbv2-test
  ipAddressType: ipv4
  port: 80
  protocol: HTTP
  targetType: ip
  ...
 ```
This created the `TargetGroup` in AWS as expected. I then changed the `port` to a different value and reapplied. The updated resource definition was accepted by the API server, however, the targetgroup in AWS was not updated. The Kubernetes resource was also reverted back to the original `port` value, i.e. a subsequent `kubectl get` showed the old value.

I suspect this is a more general issue about values that cannot be changed after a given AWS resource have been created - i.e. the kind of resources where Terraform would recreate the resource instead of doing in-place updates. However, I don't see the issue about 'in-place' vs. 'recreate' addressed in the documentation.

**Environment**

* Kubernetes version: 1.31
* Using EKS (yes/no), if so version? yes, 1.31
* AWS service targeted (S3, RDS, etc.) ec2, version 1.3.4
