### ISSUE TITLE
[apigatewayv1] Inability to Use parentRef.from.name for Root Path Resource Creation in RestAPI

### ISSUE THREAD

**Issue by avishaig1986** [aws-controllers-k8s/community#2359]
**Describe the bug**
api gateway v1 -  https://github.com/aws-controllers-k8s/apigateway-controller

When using API Gateway V1 controller, there is a limitation when attempting to create a `Resource` whose parent is the root path (`/`). This issue arises because the `parentRef.from.name` parameter, which is intended to reference the parent resource by name, is restricted to only recognize `Resource` names. However, the root path (`/`) is associated with the `RestAPI` rather than a `Resource`, making it impossible to use `parentRef.from.name` to reference it directly.

As a result, when creating a `Resource` with the root path as its parent, users must manually retrieve the `.status.rootResourceID` of the `RestAPI` after its creation. This additional step is necessary to obtain the root resource ID, which is then used in the `ParentID` field for creating the `Resource`.

**Steps to reproduce**
Attempt to apply the following yaml to the cluster:

```yaml
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: RestAPI
metadata:
  name: api-gateway-name
spec:
  name: api-gateway-name
  description: "api-gateway-description"
  endpointConfiguration: 
    types:
      - PRIVATE
---
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: Resource
metadata:
  name: my-resource
spec:
  restAPIID: dev-hcp.export-root-resource-id
  restAPIRef:
    from:
      name: api-gateway-name
  parentRef:
    from:
      name: api-gateway-name #cannot use the name of a RestAPI , only name of another Resource
```

**Expected outcome**
It should be allowed to use the name of the `RestAPI` in the `Resource` `parentRef.from.name` , or have another parameter in `Resource` such as `restApiParentRef.from.name` for example

**Actual outcome**
The following error message appears:
`resources.apigateway.services.k8s.aws "example-restapi-name" not found`

```yaml
conditions:
  - lastTransitionTime: 2025-02-26T10:24:40Z
    message: Reference resolution failed
    reason: resources.apigateway.services.k8s.aws "example-restapi-name" not found
    status: Unknown
    type: ACK.ReferencesResolved
```

**Environment**
* EKS Kubernetes version - 1.31 
* AWS service targeted - Lambda Functions

**Comment by denzhel** [comment]
Same here, it only works if I provide the parentID:
```
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: Resource
metadata:
  name: bp-aws-ack-poc-parent-resource
spec:
  #parentRef:
  #  from:
  #    name: bp-aws-ack-poc
  parentID: 123123abc
  restAPIRef:
    from:
      name: bp-aws-ack-poc
  pathPart: bp-aws-ack-poc
```
If I uncomment the `parentRef` and comment ID it errors:
```
resources.apigateway.services.k8s.aws "bp-aws-ack-poc" not found
```

**Comment by limiteddenial** [comment]
I am having the same issue.

It would be nice to be able to omit the parentID or parenetRef if you are creating the resource under the root path.
Since you are already have to ref the api, it may be able to also extract the root-resource-id and use that and set the ParenetID variable.

```
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: RestAPI
metadata:
  name: api-gateway-name
spec:
  name: api-gateway-name
  description: "api-gateway-description"
---
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: Resource
metadata:
  name: my-resource
spec:
  pathPart: my-resource
  restAPIRef:
    from:
      name: api-gateway-name
```

or another option would be to change how RestAPI works and it creates a resource called root
then you can reference that.

```
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: RestAPI
metadata:
  name: api-gateway-name
spec:
  name: api-gateway-name
  description: "api-gateway-description"
---
apiVersion: apigateway.services.k8s.aws/v1alpha1
kind: Resource
metadata:
  name: my-resource
spec:
   parentRef:
      from:
         name: root
 pathPart: my-resource
  restAPIRef:
    from:
      name: api-gateway-name
```

**Comment by denzhel** [comment]
> I am having the same issue.
> 
> It would be nice to be able to omit the parentID or parenetRef if you are creating the resource under the root path. Since you are already have to ref the api, it may be able to also extract the root-resource-id and use that and set the ParenetID variable.


Hi @limiteddenial ,

I ended up solving this issue with `kro` since according to what I understand this is not something they are going to resolve, rather suggest using `kro` as coupling.
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: apigateway
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApiGateway
    spec:
      apiGateway:
        enabled: boolean | default=false
        name: string
  resources:
    - id: restApi
      includeWhen:
        - ${schema.spec.apiGateway.enabled}
      template:
        apiVersion: apiGateway.services.k8s.aws/v1alpha1
        kind: RestAPI
        metadata:
          name: ${schema.spec.apiGateway.name}
        spec:
          name: ${schema.spec.apiGateway.name}
          endpointConfiguration:
            types:
            - "REGIONAL"
    - id: parentResource
      includeWhen:
        - ${schema.spec.apiGateway.enabled}
      template:
        apiVersion: apiGateway.services.k8s.aws/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.apiGateway.name}-parent-resource
        spec:
          parentRef:
            from:
              name: ${restApi.status.rootResourceID}
          restAPIRef:
            from:
              name: ${restApi.status.id}
          pathPart: ${schema.spec.apiGateway.name}
```
