### ISSUE TITLE
ECS taskDefinitionRef does not trigger reconciliation when new task definitions are created

### ISSUE THREAD

**Issue by jaguer0** [aws-controllers-k8s/community#2365]
**Describe the bug**
ECS `taskDefinitionRef` does not trigger reconciliation when a new task definition is created. I'm using Flux CD and have already tried `kustomize.toolkit.fluxcd.io/force: enabled`, but it didn’t work. It seems reconciliation only occurs during the scheduled period or when service fields are manually updated.

I’ve previously seen deployments working with `taskDefinitionRef` for other ECS tasks and services, but this [issue](https://github.com/aws-controllers-k8s/community/issues/2361) raises doubts, which suggests that injected service fields might be the reason for triggering a deployment.

In this case, the service hasn't changed, but the taskDefinitionRef should have been updated with the newly created task definition

**Steps to reproduce**
```
---
apiVersion: ecs.services.k8s.aws/v1alpha1
kind: Service
metadata:
  name: adot
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  name: adot
  capacityProviderStrategy:
  - base: 0
    capacityProvider: FARGATE
    weight: 1
  cluster: staging
  deploymentConfiguration:
    alarms:
      alarmNames:
      - none
      enable: false
      rollback: false
    deploymentCircuitBreaker:
      enable: true
      rollback: true
    maximumPercent: 200
    minimumHealthyPercent: 100
  deploymentController:
    type: ECS
  desiredCount: 1
  enableECSManagedTags: true
  enableExecuteCommand: false
  healthCheckGracePeriodSeconds: 30
  networkConfiguration:
    awsVPCConfiguration:
      assignPublicIP: DISABLED
      securityGroups:
      - sg-xxx
      subnets:
      - subnet-xxx
      - subnet-xxx
  platformVersion: 1.4.0
  propagateTags: NONE
  schedulingStrategy: REPLICA
  serviceConnectConfiguration:
    enabled: true
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /ecs/adot/staging
        awslogs-region: us-west-2
        awslogs-stream-prefix: ecs
        max-buffer-size: 25m
        mode: non-blocking
    namespace: arn:xxx
    services:
    - clientAliases:
      - dnsName: adot-4317-tcp.staging
        port: 4317
      discoveryName: adot-4317-tcp
      portName: adot-4317-tcp
  serviceRegistries:
  - containerName: adot
    registryARN: arn:xxx
  taskDefinitionRef:
    from:
      name: adot-staging
```
Using Gitops , Create a ecs service and task definition, update the task definition like a new image tag which will  generate a new task definition revision. 

You'll see the task definition is created with the revision, but the service is untouched. 

**Expected outcome**
When  `taskDefinitionRef` is set & a new taskdefinition is generated, it should see the change and trigger a deployment. Otherwise won't be Gitops friendly as we'd have to somehow retrieve the arn of the task definition and hard code it? .

* Kubernetes version
* Using EKS Yes v1.29.13-eks-8cce635
* AWS service targeted: ECS
