### ISSUE TITLE
Support generating `tags` via codegen

### ISSUE THREAD

**Issue by rushmash91** [aws-controllers-k8s/community#2368]
Currently, the code generator does not support generating tags for AWS resources. Adding this functionality would greatly improve the usability of ACK controllers, as tagging is a crucial feature for many AWS services.

### Proposed Solution

1. Extend the `generator.yaml` configuration to include a `tags` section where users can specify default tags or tag policies.

2. Modify the code generation logic to:
   - Add tag-related fields to the resource Spec structs
   - Include tag operations in the resource manager's Create, Update, and Delete methods
   - Generate appropriate CRD schema for tag fields

3. Update the reconciliation logic to handle tag differences between the desired and actual state of resources.

### Example `generator.yaml` Configuration

```yaml
resources:
  Repository:
    fields:
      Tags:
        type: map[string]string
    operations:
      Create:
        - TagResource
      Update:
        - TagResource
        - UntagResource
      Delete:
        - UntagResource
```

### Benefits

- Improved resource management capabilities for ACK controllers
