### ISSUE TITLE
NACL: Rules are not created properly

### ISSUE THREAD

**Issue by itaiatu** [aws-controllers-k8s/community#2374]
**Describe the bug**
NACL rules are not created properly in the AWS console.
This is a follow-up issue of https://github.com/aws-controllers-k8s/community/issues/2241.

**Steps to reproduce**
I have created the following NACL in the k8s cluster
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: NetworkACL
metadata:
  name: demo-itaiatu-test2
  namespace: sbx-clusters
  annotations:
    services.k8s.aws/region: us-east-1
spec:
  associations:
    - subnetID: subnet-04ceee7dff3fe90f4
  entries:
    - cidrBlock: 0.0.0.0/0
      egress: false
      protocol: "6"
      portRange:
        from: 80
        to: 80
      ruleAction: allow
      ruleNumber: 100
  vpcID: vpc-0361ffbb3d7a097e4
  tags:
    - key: Name
      value: demo-itaiatu-test2
```

Object's status
```yaml
...
  tags:
  - key: Name
    value: demo-itaiatu-test2
  vpcID: vpc-0361ffbb3d7a097e4
status:
  ackResourceMetadata:
    ownerAccountID: "258057316678"
    region: us-east-1
  conditions:
  - lastTransitionTime: "2025-03-12T13:31:52Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  id: acl-0a15a4c496cd94e55
  isDefault: false
  ownerID: "258057316678"
```

![Image](https://github.com/user-attachments/assets/9388debb-7edf-45b1-a997-49406b8f758b)

When looking in the AWS Console, in the first ~10 minutes, `demo-itaiatu-test2` NACL didn't have the `100` rule, but only the default ones (even if the status - posted above - said that the resource is synced)

After ~10 minutes (maybe on the next reconciliation - object updates), the rule with number `100` appeared in the console.
![Image](https://github.com/user-attachments/assets/34fc9fa5-e4f7-4aeb-bdf0-a7f889473bf2)

Another weird part is that on the **default NACL**, the rule with number `100` is added, but with wrong `protocol` and `portRange`, both on Ingress and Egress.
- Ingress
![Image](https://github.com/user-attachments/assets/af93207e-416c-4492-aec0-407e68ca6b2a)
- Egress
![Image](https://github.com/user-attachments/assets/35c909a8-b014-41af-b448-0175776e69ea)

**Expected outcome**
Same as https://github.com/aws-controllers-k8s/community/issues/2241.

**Environment**

* Kubernetes version 1.29
* Using EKS (yes/no), if so version? 1.29
* AWS service targeted (S3, RDS, etc.) EC2 v1.3.7
