### ISSUE TITLE
cloudwatch MetricAlarm - no way to reference Healthcheck created in the same deployment via route53-controller

### ISSUE THREAD

**Issue by akeyd** [aws-controllers-k8s/community#2379]
**Is your feature request related to a problem?**
When attempting to Create a cloudwatch MetricAlarm that references route53-controller's Healthcheck deployed simultaneously thee's no way to reference HealthCheckI in the dimension.
I tried this:

```
---
apiVersion: route53.services.k8s.aws/v1alpha1
kind: HealthCheck
metadata:
  name: www-backend-test-healthcheck
  namespace: default
spec:
  healthCheckConfig:
    type: HTTPS
    fullyQualifiedDomainName: "www.example.com"
    port: 443
    failureThreshold: 3
    requestInterval: 30
    resourcePath: "/healthz"
    enableSNI: true
    measureLatency: true
    alarmIdentifier:
      name: "www-backend-test-healthcheck-alarm"
      region: "us-west-2"
  tags:
    - key: Name
      value: www-backend-test-healthcheck

---
apiVersion: cloudwatch.services.k8s.aws/v1alpha1
kind: MetricAlarm
metadata:
  name: www-backend-test-healthcheck-alarm
  namespace: default
spec:
  name: "www-backend-test-healthcheck-alarm"
  comparisonOperator: LessThanThreshold
  evaluationPeriods: 2
  metricName: HealthCheckStatus
  namespace: AWS/Route53
  period: 60
  statistic: Minimum
  threshold: 1
  alarmDescription: "Alarm when HTTPS health check fails"
  dimensions:
    - name: HealthCheckId
      valueFrom:
        reference:
          apiVersion: route53.services.k8s.aws/v1alpha1
          kind: HealthCheck
          name: www-backend-test-healthcheck
          fieldPath: status.healthCheckId
  actionsEnabled: true
```
But it throws:
Error from server (BadRequest): error when creating metricalarm.yaml": MetricAlarm in version "v1alpha1" cannot be handled as a MetricAlarm: strict decoding error: unknown field "spec.dimensions[0].valueFrom"

This is somewhat similar to this: https://github.com/aws-controllers-k8s/community/issues/2209 as in both cases there doesn't seem to be a way to reference the HealthCheckId by some kind of name/path etc.

**Describe the solution you'd like**
Be able to reference route53 healthcheck id by kubernetes references or similar.

**Describe alternatives you've considered**
The only alternative I can reasonably consider is to do it all in terraform and drop both the controllers.
