### ISSUE TITLE
RDS ACK Controller Does Not Resync engineVersion After Auto Minor Version Upgrade

### ISSUE THREAD

**Issue by doryer** [aws-controllers-k8s/community#2380]
**Describe the bug**
We are using the ACK RDS Controller to deploy and manage RDS instances via CRDs, with ArgoCD handling the synchronization.

We configure our RDS instances with autoMinorVersionUpgrade: true to allow automatic minor version upgrades. To support this, our desired state in ArgoCD sets:

engineVersion: `null`

Setting engineVersion: null ensures that:

* The operator does not override the existing version.
* The operator fetches the latest engine version from AWS and patches the CRD accordingly.
However, we expected that during the automatic re-sync process, the RDS controller would detect an engine version change in AWS and update the CRD to reflect the new version without requiring a manual sync.

The status of the object and the error log is:
`InvalidParameterCombination: Cannot upgrade postgres from 14.13 to 14.12 status code: 400, request id: e119c847-e32a-4b7e-b095-7bdd8sdsdsdb09`

This suggests that the operator is not detecting minor version upgrades during the re-sync cycle, leading to unintended downgrade attempts.

**Steps to reproduce**

1. Configure CRD with autoMinorVersionUpgrade set to true
```yaml 
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: rds-test
spec:
  allocatedStorage: 20
  autoMinorVersionUpgrade: true
  dbInstanceClass: db.t4g.small
  dbInstanceIdentifier: symbol-gateway-postgresql-staging-v2
  engineVersion: null
```

2. Let the operator patch the engineVersion field with the current version from AWS.

3. Trigger a minor version upgrade for the RDS instance.

4. After the upgrade completes, check if the CRD reflects the new engine version.

5. Attempt to sync the CRD in ArgoCD and observe whether the operator tries to downgrade the database.

Let the operator patch the version on the cloud to the CRD, then upgrade the minor version. after the minor version upgraded, try to sync the CRD.

**Expected outcome**
* The RDS operator should detect minor version upgrades as part of its re-sync process and automatically update the engineVersion field in the CRD.
* The CRD should match the live AWS state, preventing ArgoCD from attempting a downgrade.

**Environment**

* Kubernetes version: v1.28
* Using EKS (yes/no), if so version? Yes, 1.28
* AWS service targeted (S3, RDS, etc.): RDS
