### ISSUE TITLE
CRD documentation isn't correctly represeting array of struct types

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#2393]
Right now, our docs are showing complex configs like they're single items, when they're actually meant to be arrays of structs. e.g in **S3** `bucket.spec.notifications` - it looks like we're not showing users can set up multiple notifications. 

How it's shown today:
```yaml
  topicConfigurations:
    events:
    - string
    filter: 
      key: 
        filterRules:
        - name: string
          value: string
    id: string
    topicARN: string
```

How it should look like:
```yaml
topicConfigurations:
  - events:
    - string
    filter: 
      key: 
        filterRules:
        - name: string
          value: string
    id: string
    topicARN: string
```

https://aws-controllers-k8s.github.io/community/reference/s3/v1alpha1/bucket/
