### ISSUE TITLE
Memorydb controller can not create custom values in parameter group

### ISSUE THREAD

**Issue by acharviakou** [aws-controllers-k8s/community#2405]
**Describe the bug**
A concise description of what the bug is.
Memory db parameter group created using default parameters on first apply even if something not default specified.

**Steps to reproduce**
Apply the following manifest
```
apiVersion: memorydb.services.k8s.aws/v1alpha1
kind: ParameterGroup
metadata:
  name: pg-d-test
  namespace: tipico
spec:
  family: memorydb_redis7
  name: pg-d-test
  parameterNameValues:
  - parameterName: search-enabled
    parameterValue: "yes"
  - parameterName: search-query-timeout-ms
    parameterValue: "10002"
```
This manifest contains not default parameter values.
If you check parameters in AWS console or using kubectl (kubectl get parametergroup.memorydb pg-d-test -oyaml) then you will see default parameters
If you apply this manifest once again (kubectl apply -f ...) then custom values will be added
It is a bit confusing. Moreover some parameters can not be changed for existing cluster like "search-enabled" to enable vector search.

**Expected outcome**
A concise description of what you expected to happen.
I would expect to have correct parameter group values on first time apply

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)
