### ISSUE TITLE
Inconsistent Tagging Schema in ACK S3 Controller

### ISSUE THREAD

**Issue by af-ilya** [aws-controllers-k8s/community#2418]
Description:
The current schema for the ACK S3 controller allows setting tags under spec.tagging.tagSet, where each tag is defined as a key-value pair. However, according to the ACK documentation at https://aws-controllers-k8s.github.io/community/docs/user-docs/ack-tags/, tags should be specified under spec.tags.

The schema should be updated to reflect this structure to align with the documentation.
This inconsistency may confuse users attempting to apply tags based on the provided documentation, especially when building automation around this field. 

Expected Schema:
```
spec:
  tags:
    - key: string
      value: string
```

Current Schema:
```
spec:
  tagging:
    tagSet:
    - key: string
      value: string
```
