### ISSUE TITLE
activemq engineVersion types 

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2426]
Good day!

If I am applying such a manifest:

```
apiVersion: mq.services.k8s.aws/v1alpha1
kind: Broker
metadata:
  name: activemq-new
  namespace: infra-production
spec:
  logs:
    audit: true
    general: true
  name: activemq-new
  autoMinorVersionUpgrade: false
  deploymentMode: ACTIVE_STANDBY_MULTI_AZ
  engineType: ActiveMQ
  engineVersion: 5.18
  hostInstanceType: mq.m5.xlarge
  publiclyAccessible: false
  subnetRefs:
    - from:
        name: production-private-eu-west-2b
    - from:
        name: production-private-eu-west-2a
  users:
    - password:
        namespace: infra-production
        name: amq-password
        key: password
      groups: []
      consoleAccess: true
      username: admin
  securityGroupRefs:
  - from:
      name: limit-amq-to-subnet
```

I am getting the next error:

```
Broker/infra-production/activemq-new dry-run failed: failed to create typed patch object (infra-production/activemq-new; mq.services.k8s.aws/v1alpha1, Kind=Broker): .spec.engineVersion: expected string, got &value.valueUnstructured{Value:5.18}
```

I think it should be better documented or some conversion should be made for automatic conversion.

Totally sure that change in the source manifest to 

```yaml
...
  engineVersion: '5.18'
```

would help. But it is always pain to remember it.
