### ISSUE TITLE
Sync Kubernetes object labels to spec.tags for AWS resource tagging

### ISSUE THREAD

**Issue by af-ilya** [aws-controllers-k8s/community#2429]
Many AWS resources managed by ACK controllers support tagging through the spec.tags field, but each resource has its own CRD schema. In contrast, Kubernetes labels use consistent metadata.labels field across all objects, which is also commonly used by tooling for policy enforcement, auditing, and organization.

This feature request proposes an option to automatically copy labels from metadata.labels into the spec.tags field when a resource is created or updated. This would simplify tag management and ensure consistency between Kubernetes and AWS tagging systems.

**Proposal**
- Add support for optional syncing of metadata.labels into spec.tags
- Controlled via annotation or controller-wide config
- Optional key prefixing/filtering

**Benefits**
- Unified tagging across Kubernetes and AWS
- Simplifies automation and policy enforcement
- Enables better cost allocation and resource tracking using Kubernetes-native metadata

Example:

```
metadata:
  labels:
    env: prod
    team: platform
  annotations:
    services.k8s.aws/label-sync: enabled
spec:
  tags:
    - key: env
      value: prod
    - key: team
      value: platform
```
