### ISSUE TITLE
Installing ACK charts in namespaced mode via prevents multiple installs

### ISSUE THREAD

**Issue by ericlarssen** [aws-controllers-k8s/community#2430]
**Describe the bug**
When you install a helm chart in namespaced mode a cluster role is created with a name not unique to the helm install.

```
Error: Unable to continue with install: ClusterRole "ack-namespaces-cache-acm-controller" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "test-b": current value is "test-a"
```

https://github.com/aws-controllers-k8s/acm-controller/blob/v1.0.7/helm/templates/caches-role.yaml#L4

I noticed this file exists in a number of charts but did not identify them all. This would not be a problem however when helm installs the files, it adds annotations unique to the the helm install, preventing multiple helm releases from owning the same resource.

meta.helm.sh/release-name: ack-chart
meta.helm.sh/release-namespace: my-namespace

**Steps to reproduce**
1. Helm install acm chart into a namespace (test-a), with the installScope set to namespace
2. Attempt to Helm install acm chart into another namespace (test-b), with the installScope set to namespce

**Expected outcome**
Both installs should work but will fail with a like error. 

```
Error: Unable to continue with install: ClusterRole "ack-namespaces-cache-acm-controller" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "test-b": current value is "test-a"
```

**Environment**

* All k8s versions
* Not EKS related
* Afaict all helm chart

**Comment by a-hilaly** [comment]
Good catch @ericlarssen ! indeed we need to make the cluster-scoped resources names unique across the cluster!

**Comment by ericlarssen** [comment]
I believe the cluster role binding will also need updated

**Comment by itaiatu** [comment]
We have the same problem, but in a different scenario.

When leveraging the sharding mechanism in cluster mode, in a GitOps context, ArgoCD complains about `SharedResourceWarning`

Example for two `ack-s3` controllers deployed on the same cluster on two different namespaces.
```
ClusterRole/ack-namespaces-cache-s3-controller is part of X and Y
ClusterRole/ack-s3-controller is part of X and Y
ClusterRoleBinding/ack-namespaces-cache-s3-controller is part of X and Y
ClusterRoleBinding/ack-s3-controller is part of X and Y
```

---

Instead of creating multiple `ClusterRoles` and `ClusterRoleBindings` with the same spec, a possible solution would be to have a feature flag for these 4 `ClusterRoles` and `ClusterRoleBindings`.

In this way, in a cluster-scoped mode, we will deploy the `ClusterRole` and `ClusterRoleBinding` only on a single shard (one ArgoCD App) and for the rest, we will disable that flag.

**Comment by alexzandershevchenko** [comment]
> We have the same problem, but in a different scenario.
> 
> When leveraging the sharding mechanism in cluster mode, in a GitOps context, ArgoCD complains about `SharedResourceWarning`
> 
> Example for two `ack-s3` controllers deployed on the same cluster on two different namespaces.
> 
> ```
> ClusterRole/ack-namespaces-cache-s3-controller is part of X and Y
> ClusterRole/ack-s3-controller is part of X and Y
> ClusterRoleBinding/ack-namespaces-cache-s3-controller is part of X and Y
> ClusterRoleBinding/ack-s3-controller is part of X and Y
> ```
> 
> Instead of creating multiple `ClusterRoles` and `ClusterRoleBindings` with the same spec, a possible solution would be to have a feature flag for these 4 `ClusterRoles` and `ClusterRoleBindings`.
> 
> In this way, in a cluster-scoped mode, we will deploy the `ClusterRole` and `ClusterRoleBinding` only on a single shard (one ArgoCD App) and for the rest, we will disable that flag.

That sounds like overcomplicating simple things...  

I'm also using ArgoCD and using simple workaround with `ignoreDifferences` in Application's/ApplicationSet Template spec:
```
  ignoreDifferences:
    - group: '*'
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/argocd.argoproj.io~1instance
    - group: '*'
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/argocd.argoproj.io~1instance
```
This solves warnings and continuous sync. But would be great to have correct helmcharts for all resources. I'm not sure why name generation implemented for some resources and not implemented for ClusterRole and ClusterRoleBindings... :)

**Comment by itaiatu** [comment]
> That sounds like overcomplicating simple things...

We can make the `ClusterRole` and `ClusterRoleBinding` names dynamically.

**Comment by alexzandershevchenko** [comment]
> We can make the `ClusterRole` and `ClusterRoleBinding` names dynamically then.

Yep. Like 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-cache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-cache
```
and so on...
