### ISSUE TITLE
The ACK Lambda Controller modifies the object spec

### ISSUE THREAD

**Issue by stefanescualexandrumihai** [aws-controllers-k8s/community#2431]
**Describe the bug**
I encountered an issue while creating a Function using `vpcConfig.securityGroupRefs`:

```yaml
status:
  ackResourceMetadata:
    arn: arn:aws:lambda:us-east-1:1234:function:pr13344879357-ci-va6-cw2splunk
    ownerAccountID: "1234"
    region: us-east-1
  conditions:
  - lastTransitionTime: "2025-04-17T11:22:25Z"
    message: Reference resolution failed
    reason: 'both resource reference wrapper and ID cannot be used together: VPCConfig.SecurityGroupIDs,VPCConfig.SecurityGroupRefs'
    status: Unknown
    type: ACK.ReferencesResolved
  lastModified: 2025-04-17T09:41:44.372+0000
  lastUpdateStatus: Successful
  revisionID: 93e97a3b-c3b0-451c-af76-b2928cb415bd
  state: Active
```

My spec contains these lines:
```yaml
    securityGroupRefs:
      - from:
          name: {{ include "cluster-build.clusterFullName" $ }}-cw2splunklambda
```

**Steps to reproduce**

I've also created a simple manifest with this in its spec:

```yaml
  vpcConfig:
    securityGroupRefs:
      - from:
          name: pr13344879357-ci-va6-cw2splunklambda
```

And the controller took this snippet of code and transformed it into:

```yaml
  vpcConfig:
    securityGroupIDs:
    - sg-042a062cc8a002db3
```

```sh
kubectl get securitygroup -n ci-clusters  pr13344879357-ci-va6-cw2splunklambda 
NAME                                   ID
pr13344879357-ci-va6-cw2splunklambda   sg-042a062cc8a002db3
```

**Expected outcome**

The ACK Lambda Controller accepts both securityGroupRefs and securityGroupIDs / just one of them, but it does not transform securityGroupRefs into securityGroupIDs.

I assume that AWS Lambda template doesn't support reference by name 
**Environment**

* Kubernetes version 1.30
* Using EKS (yes/no), if so version?  1.30
* AWS service targeted (S3, RDS, etc.) lambda-controller:1.6.1
