### ISSUE TITLE
Failed to update lambda after successful creation

### ISSUE THREAD

**Issue by haim-bp** [aws-controllers-k8s/community#2432]
**Describe the Bug**  
After successfully creating a Lambda function using the ACK controller, subsequent updates to the function (e.g., updating `spec.environment.variables`) fail with a validation error, despite the resource being initially synced.

---

**Steps to Reproduce**  
1. Create a Lambda function using the ACK controller. The initial sync succeeds, as shown below:
    ```yaml
    ackResourceMetadata:
      arn: arn:aws:lambda:eu-central-1:12312321:function:function-dev
      ownerAccountID: "12312321"
      region: eu-central-1
    codeSHA256: dfsdfsdf=
    codeSize: 2363902
    conditions:
      - lastTransitionTime: "2025-04-20T10:32:20Z"
        message: Resource synced successfully
        reason: ""
        status: "True"
        type: ACK.ResourceSynced
    lastModified: 2025-04-20T10:29:48.641+0000
    lastUpdateStatus: Successful
    revisionID: 4c5bfb15-ffds-48cd-a46f-b3c7efeb680e
    state: Active
    version: $LATEST
    ```

2. Attempt to update the Lambda function by modifying `spec.environment.variables`.

3. The update fails, and the following conditions are reported:
    ```yaml
    conditions:
      - message: |
          operation error Lambda: UpdateFunctionConfiguration, 1 validation error(s) found.
          - missing required field, UpdateFunctionConfigurationInput.EphemeralStorage.Size.
        status: "True"
        type: ACK.Recoverable
      - lastTransitionTime: "2025-04-20T12:37:57Z"
        message: Unable to determine if desired resource state matches latest observed
          state
        reason: |
          operation error Lambda: UpdateFunctionConfiguration, 1 validation error(s) found.
          - missing required field, UpdateFunctionConfigurationInput.EphemeralStorage.Size.
        status: Unknown
        type: ACK.ResourceSynced
    ```

---

**Expected Outcome**  
The Lambda function configuration should update successfully without requiring manual specification of `EphemeralStorage.Size` unless it is explicitly set in the spec.

---

**Environment**
- **Kubernetes Version:** [Please specify]
- **EKS:** Yes, version 1.31
- **Targeted AWS Service:** Lambda
