### ISSUE TITLE
Lambda function gets stuck in the Pending state upon creation

### ISSUE THREAD

**Issue by haim-bp** [aws-controllers-k8s/community#2433]
**Describe the Bug**  
Lambda function gets stuck in the `Pending` state upon creation. Once in this state, the function cannot be updated or deleted via the ACK controller.  
The only workaround is to manually remove the `finalizers.lambda.services.k8s.aws/Function` entry and then delete the resource manually.

---

**Steps to Reproduce**  
1. Create a Lambda `Function` resource using the ACK controller.
2. The resource enters the following status:
    ```yaml
    conditions:
      - message: function in 'Pending' state, cannot be modified or deleted
        status: "True"
        type: ACK.Recoverable
      - lastTransitionTime: "2025-04-20T12:53:34Z"
        message: Unable to determine if desired resource state matches latest observed
          state
        reason: function in 'Pending' state, cannot be modified or deleted
        status: Unknown
        type: ACK.ResourceSynced
    ```

3. Attempts to update or delete the function using the ACK controller result in no action due to the function being stuck in a `Pending` state.
4. To resolve, you must:
    - Remove the `finalizers.lambda.services.k8s.aws/Function` finalizer from the resource.
    - Manually delete the Kubernetes resource.

---

**Expected Outcome**  
The Lambda function should either:
- Successfully transition from `Pending` to `Active`, or  
- Fail with a clear error and allow cleanup or retry via normal ACK resource management (without requiring manual intervention).

---

**Environment**
- **Kubernetes Version:** [Please specify]
- **EKS:** Yes, version 1.31
- **Targeted AWS Service:** Lambda
