### ISSUE TITLE
[EKS Controller] constantly spamming in logs

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2442]
with

```json
{"level":"info","ts":"2025-04-29T08:28:29.342Z","logger":"ackrt","msg":"desired resource state has changed","kind":"Nodegroup","namespace":"infra-production","name":"production-fix-ng-20250413-c","account":"*****","role":"arn:aws:iam::*****:role/ack-ec2-controller-tooling","region":"eu-west-2","is_adopted":false,"generation":2,"diff":[{"Path":{"Parts":["Spec","Taints"]},"A":[{"effect":"NO_SCHEDULE","key":"node-role.kubernetes.io/fix","value":""}],"B":[{"effect":"NO_SCHEDULE","key":"node-role.kubernetes.io/fix"}]}]}
```

the source manifest:

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-fix-ng-20250413-c
  namespace: infra-production
spec:
  name: production-fix-ng-20250413-c
  clusterName: production-new
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2c
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 1
    desiredSize: 1
  instanceTypes:
    - m5.4xlarge
  taints:
    - key: "node-role.kubernetes.io/fix"
      value: ""
      effect: "NO_SCHEDULE"
  labels: {}
  amiType: BOTTLEROCKET_x86_64
```

**Comment by gecube** [comment]
looks like fixed with changing the manifest to:

```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: production-fix-ng-20250413-c
  namespace: infra-production
spec:
  name: production-fix-ng-20250413-c
  clusterName: production-new
  diskSize: 100
  subnetRefs:
    - from:
        name: production-private-eu-west-2c
  nodeRole: arn:aws:iam::*****:role/eks-production-nodegroup-role
  scalingConfig:
    minSize: 1
    maxSize: 1
    desiredSize: 1
  instanceTypes:
    - m5.4xlarge
  taints:
    - key: "node-role.kubernetes.io/fix"
#######      value: "" ##### removed
      effect: "NO_SCHEDULE"
  labels: {}
  amiType: BOTTLEROCKET_x86_64
```
