### ISSUE TITLE
[EKS Controller] IMDSv2 for node groups

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2444]
Good day!

It is mandatory for many regulated business to select by default IMDSv2 on EC2 instances.
Even Amazon itself recommends to enable this setting:

<img width="430" alt="Image" src="https://github.com/user-attachments/assets/fd1d544b-e51e-44cd-b4db-1786f865d8e8" />

Unfortunately, `NodeGroup` API does not support it at all.

https://aws-controllers-k8s.github.io/community/reference/eks/v1alpha1/nodegroup/

Despite the terraform provider https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group#input_metadata_options

**Comment by gecube** [comment]
related issues:

https://github.com/aws/aws-cdk/issues/31124
https://github.com/hashicorp/terraform-provider-aws/issues/38516

**Comment by michaelhtm** [comment]
Hi @gecube 
It seems like there is no clear way to resolve this right now.
As you mentioned, this is not supported by the API, and the controller is limited to it.
cc: @rushmash91 @a-hilaly

**Comment by gecube** [comment]
@michaelhtm sorry to hear it, so it means that it should be clearly described how to get the working EKS cluster from the scratch with creating the proper EC2 launch template and then utilise it in EKS api.

**Comment by rushmash91** [comment]
Hi @gecube,

Yes, that is a great idea! 

We can document how to create a nodegroup with a `launchtemplate` that have the parameters set up with the appropiate hop count in the launch template: 

something like this

```
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 2

```
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html

https://github.com/aws-controllers-k8s/ec2-controller/blob/main/config/crd/bases/ec2.services.k8s.aws_launchtemplates.yaml#L453-L468


and then reference that launch template to create a nodegroup (we can add a reference like we have for EC2 instances)

```
  launchTemplate:
    name: ...
```

https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/crd/bases/eks.services.k8s.aws_nodegroups.yaml#L163-L183

**Comment by rushmash91** [comment]
Here is an example:

- Create a LaunchTemplate

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: LaunchTemplate
metadata:
  name: eks-imdsv2-launch-template
spec:
  name: eks-imdsv2-launch-template
  data:
    metadataOptions:
      httpTokens: required
      httpEndpoint: enabled
      httpPutResponseHopLimit: 1
```

- Create a  Nodegroup
```yaml
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: eks-managed-nodegroup
spec:
  name: eks-managed-nodegroup
  clusterName: my-cluster
  nodeRole: arn:aws:iam::111122223333:role/eks-node-group-role
  subnets:
    - subnet-xxxxxxxxxxxx1
    - subnet-xxxxxxxxxxxx2
  launchTemplate:
    name: eks-imdsv2-launch-template
    version: "1"
  scalingConfig:
    minSize: 1
    maxSize: 5
    desiredSize: 3
```

Remember to replace the following placeholder values with your actual values:

• my-cluster with your EKS cluster name
• arn: aws: iam::111122223333:role/eks-node-group-role with your actual node IAM role ARN
• subnet-xxxxxxxxxxxx1 and subnet-xxxxxxxxxxxx2 with your actual subnet IDs
