### ISSUE TITLE
MSK: operation error Kafka: CreateCluster, https response error StatusCode: 403

### ISSUE THREAD

**Issue by kappa8219** [aws-controllers-k8s/community#2464]
**Describe the bug**

arn:aws:iam::aws:policy/AmazonMSKFullAccess attached with Pod Identity results in:

```
{
  "level": "error",
  "ts": "2025-05-09T05:31:01.021Z",
  "msg": "Reconciler error",
  "controller": "cluster",
  "controllerGroup": "kafka.services.k8s.aws",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "cluster-name",
    "namespace": "ack-system"
  },
  "namespace": "ack-system",
  "name": "x",
  "reconcileID": "7680a7be-2523-4689-9268-0c04a18db412",
  "error": "operation error Kafka: CreateCluster, https response error StatusCode: 403, RequestID: 3bba50f8-f56f-4d73-a50f-23eef5249e01, api error AccessDeniedException: User: xxx is not authorized to perform: kafka:CreateCluster on resource: *",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"
}

```

**Steps to reproduce**

**Expected outcome**
Create cluster

**Environment**

* Kubernetes version 1.31
* Using EKS - yes 
* AWS service - MSK

**Comment by gecube** [comment]
@kappa8219 did you restart controller after changing the perms? Very strange as it worked for me two weeks ago.

**Comment by gecube** [comment]
ah... I used IRSA... I still did not switch to pod identity.

**Comment by vinicius91** [comment]
Any updates on this investigation? I'm facing similar issues on my stack too

**Comment by gecube** [comment]
@vinicius91 I think that strimzi gives better experience.. at leas from the maintenance and cost perspective. But it could sound like anti-advertisement or advertisement against managed amazon services and msk in particular - no way :-)

**Comment by kappa8219** [comment]
> Hello @kappa8219 @vinicius91 
> I was unable to replicate this issue. I'm also using PodIdentity with `AmazonMSKFullAccess` permission, and was able to create the msk Cluster successfully..
> I'm using v1.2.1.
> 
> Not sure what could be the issue here..
> 

Hm, will also retry with the modern version, also 4.1 is out, it is interesting to see queues in Kafka.

**Comment by kappa8219** [comment]
Still no success :(

```json
{
  "level": "error",
  "ts": "2025-10-24T05:19:33.504Z",
  "msg": "Reconciler error",
  "controller": "cluster",
  "controllerGroup": "kafka.services.k8s.aws",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "xxx-dev-eks-app",
    "namespace": "ack-system"
  },
  "namespace": "ack-system",
  "name": "xxx-dev-eks-app",
  "reconcileID": "8d29b64d-3355-4cb5-9fe0-ad72ec16cfd3",
  "error": "operation error Kafka: CreateCluster, https response error StatusCode: 403, RequestID: ID, api error AccessDeniedException: User: arn:aws:sts::xxx:assumed-role/ack-controllers-kafka/eks-terra-clus-ack-contro-xxx is not authorized to perform: kafka:CreateCluster on resource: *",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"
}

```

Pod Identity association seems to be fine(at least for many other controllers such config works). Role is also looks attached with both AdministratorAccess and AmazonMSKFullAccess.

Here is my cluster config:

```yaml
apiVersion: kafka.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: dev-eks-app
  namespace: ack-system
spec:
  name: dev-eks-app
  kafkaVersion: "4.1.x.kraft"
  numberOfBrokerNodes: 2
  brokerNodeGroupInfo:
    instanceType: "kafka.m7g.large"
    clientSubnets:
      - subnet-xxx
      - subnet-yyy
    securityGroups:
      - sg-zzz
    storageInfo:
      ebsStorageInfo:
        volumeSize: 200
        provisionedThroughput:
          enabled: false
  encryptionInfo:
    encryptionInTransit:
      clientBroker: "TLS_PLAINTEXT"
      inCluster: true
  enhancedMonitoring: "DEFAULT"
  loggingInfo:
    brokerLogs:
      cloudWatchLogs:
        enabled: true
        logGroup: dev-mks-logs-app
  configurationInfo:
    arn: "aws_msk_configuration.dev-cluster-configuration-eks-2node-kraft.arn"
    revision: 1
  openMonitoring:
    prometheus:
      jmxExporter:
        enabledInBroker: true
      nodeExporter:
        enabledInBroker: true
---
apiVersion: kafka.services.k8s.aws/v1alpha1
kind: Configuration
metadata:
  name: dev-cluster-configuration-eks-2node-kraft2
  namespace: ack-system
spec:
  name: "dev-cluster-configuration-eks-2node-kraft2"
  kafkaVersions:
    - "4.1.x.kraft"
  serverProperties: MY_HASH_CONFIG
---
```

Controller: public.ecr.aws/aws-controllers-k8s/kafka-controller:1.2.1
