### ISSUE TITLE
ACK EC2 Controller doesn't adopt VPC Peering Connection

### ISSUE THREAD

**Issue by stefanescualexandrumihai** [aws-controllers-k8s/community#2480]
**Describe the bug**
Same as here : https://github.com/aws-controllers-k8s/community/issues/2419
**Steps to reproduce**

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCPeeringConnection
metadata:
  annotations:
    services.k8s.aws/adopted: "true"
    services.k8s.aws/adoption-fields: |
      {
        "vpcPeeringConnectionID": "pcx-03240039307ec4900"
      }
    services.k8s.aws/adoption-policy: adopt
  name: test-vpc-peer-to-test
  namespace: ci-clusters
status:
  conditions:
  - lastTransitionTime: "2025-05-14T08:27:04Z"
    message: Reference resolution failed
    reason: 'resource reference wrapper or ID required: VPCID,VPCRef'
    status: Unknown
    type: ACK.ReferencesResolved
```

![Image](https://github.com/user-attachments/assets/5697697b-119e-43ac-97df-f77ea7a53f82)

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version 1.30
* Using EKS (yes/no), if so version? 1.30
* AWS service targeted (S3, RDS, etc.) ACK EC2 1.4.4

**Comment by michaelhtm** [comment]
Hi @stefanescualexandrumihai 
Seems like the configuration is not correct. The `services.k8s.aws/adopted: true` is added by the controller when it successfully adopts the resource.
I just tested it successfully wit the following configuration:
```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCPeeringConnection
metadata:
  name: my-pcs
  annotations:
    services.k8s.aws/adoption-policy: adopt
    services.k8s.aws/adoption-fields: |
      {
        "vpcPeeringConnectionID": "pcx-01b143ceb64da5dd5"
      }
```
