### ISSUE TITLE
Stand alone Subscription Filter CRD for ACK Cloudwatch logs controller

### ISSUE THREAD

**Issue by vladkiner** [aws-controllers-k8s/community#2483]
**Is your feature request related to a problem?**
We are having similar issue with Log Groups created by RDS for audit, error and slowquery logs as described [issues/2174](https://github.com/aws-controllers-k8s/community/issues/2174). Log group doesn't get imported and we suspecting due to ownership issue. We suspecting RDS/RDS Controller might own it and prevent Cloudwatchlogs Controller to adopt the resource. It would be beneficial to have Stand alone Subscription Filter CRD for ACK Cloudwatch logs controller

**Describe the solution you'd like**
A standalone crd for subscription filter in ACK cloudwatch logs controller

**Describe alternatives you've considered**
So far we have zero alternatives

**Comment by knottnt** [comment]
@vladkiner could you share the manifests and steps to reproduce the issue?

**Comment by knottnt** [comment]
@vladkiner The error you're seeing may be due to the `LogGroup` resource you're creating seeing that the AWS resource isn't yet managed by ACK. `AdoptedResource` attempts to create a new ACK resource so the fact that both `AdoptedResource` and `LogGroup` are being created could cause a conflict.

If you'd like to use the `LogGroup` manifest as the source of truth when adopting the AWS resource you can use the newer [adoption-policy annotations](https://aws-controllers-k8s.github.io/community/docs/user-docs/features/#resourceadoption) with `adopt-or-create` policy.

```yaml
apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
kind: LogGroup
metadata:
  name: aws-rds-cluster-hello-world-error
  namespace: {{namespace}}
  annotations:
    service.k8s.aws/adoption-policy: adopt-or-create
spec:
  name: "/aws/rds/cluster/hello-world/error"
  retentionDays: 7
  subscriptionFilters:
    - destinationARN: "arn:aws:firehose:us-east-1:{{aws_account}}:deliverystream/{{delivery_stream_name}}"
      distribution: "ByLogStream"
      filterName: "filter_name"
      filterPattern: ""
      roleARN: "arn:aws:iam::{{aws_account}}:role/{{role_name}}"
```
