### ISSUE TITLE
[rds-controller] can't modify DBParameterGroup after failure

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#2487]
1. create a DBParameterGroup with incorrect parameters.

Then got:

```yaml
status:
  ackResourceMetadata:
    arn: 'arn:aws:rds:eu-west-2:474417630776:pg:****-1'
    ownerAccountID: '474417630776'
    region: eu-west-2
  conditions:
    - message: 'unknown parameter: character_set_system'
      status: 'True'
      type: ACK.Terminal
    - lastTransitionTime: '2025-05-16T14:00:44Z'
      message: Resource not synced
      reason: resource is in terminal condition
      status: 'False'
      type: ACK.ResourceSynced
```

2. Change the DBParameterGroup. Find that there are no changes.

**Comment by gecube** [comment]
Anyway, I checked that if I delete it from the cluster - it immediately is deleted from the cloud (so the controller is working).

**Comment by gecube** [comment]
after removal and recreation of the resource - everything is fine:


```yaml
status:
  ackResourceMetadata:
    arn: 'arn:aws:rds:eu-west-2:474417630776:pg:****'
    ownerAccountID: '474417630776'
    region: eu-west-2
  conditions:
    - lastTransitionTime: '2025-05-16T14:11:40Z'
      message: Resource synced successfully
      reason: ''
      status: 'True'
      type: ACK.ResourceSynced
  parameterOverrideStatuses:
    - applyMethod: immediate
      applyType: dynamic
      parameterName: character_set_client
      parameterValue: utf8
    - applyMethod: immediate
      applyType: dynamic
      parameterName: character_set_connection
      parameterValue: utf8
    - applyMethod: immediate
      applyType: dynamic
      parameterName: character_set_database
      parameterValue: utf8
    - applyMethod: immediate
      applyType: dynamic
      parameterName: character_set_results
      parameterValue: utf8
    - applyMethod: immediate
      applyType: dynamic
      parameterName: character_set_server
      parameterValue: utf8
    - applyMethod: immediate
      applyType: dynamic
      parameterName: collation_connection
      parameterValue: utf8_general_ci
    - applyMethod: immediate
      applyType: dynamic
      parameterName: collation_server
      parameterValue: utf8_general_ci
    - applyMethod: immediate
      applyType: dynamic
      parameterName: log_bin_trust_function_creators
      parameterValue: '1'
```
