### ISSUE TITLE
Support for cross-region VPC Endpoints

### ISSUE THREAD

**Issue by cecilkootz** [aws-controllers-k8s/community#2513]
**Documentation**

- [Announcement Post](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-privatelink-across-region-connectivity/)
- [aws-sdk-go-v2 spec](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#CreateVpcEndpointServiceConfigurationInput)
- [ec2-controller VPCEndpointSpec](https://pkg.go.dev/github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1#VPCEndpointSpec)

**Which section(s) is the issue in?**

VPCEndpoint for the ec2 controller

**Describe the solution you'd like**
Additional field in the VPC Endpoint spec to allow for the `ServiceRegion` to be supplied. Currently defaults to region targeted for the VPC attachment. This supports scenarios where the service is hosted in say `us-east-1` but the attachment is in `us-west-2`.

**Comment by knottnt** [comment]
@farhaan-shamsee Does the VPC Endpoint Service you're trying to connect to have `Supported Regions` set to include ap-southeast-1? If the VPC Endpoint Services are also managed by ACK it looks like we'll also need to remote SupportedRegions from the [ignored field paths](https://github.com/aws-controllers-k8s/ec2-controller/blob/b3570a72f8a4fe236c4e7d2d7614928526982812/generator.yaml#L76) as well.

**Comment by knottnt** [comment]
Hmm testing adding the `serviceRegion` field on my end and I'm able to create a new VpcEndpoint connecting from `ap-southeast-1` to a VPC Endpoint Service in `eu-central-1` with the below manifest.

```yaml
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCEndpoint
metadata:
  name: cross-region-endpoint
spec:
  serviceName: com.amazonaws.vpce.eu-central-1.not-a-real-servicename
  serviceRegion: eu-central-1
  ipAddressType: ipv4
  vpcEndpointType: Interface
  vpcID: <vpc-id>
  tags:
    - key: Name
      value: cross-region-endpoint
```

Are you modifying an existing VPC Endpoint? Looking at the [ModifyVpcEndpoint](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcEndpoint.html) operation it doesn't provide a way to change the ServiceRegion. So, for an existing resource the ACK controller won't be able to modify the `serviceRegion` field after initial creation. Instead you'd need to create a new VPC Endpoint.
