### ISSUE TITLE
MSK Cluster SASL/SCRAM: AWS Console Does Not Recognize Kubernetes Secret via associatedSCRAMSecretRefs

### ISSUE THREAD

**Issue by Chalapathidevops** [aws-controllers-k8s/community#2518]
**Describe the bug**

When creating an Amazon MSK cluster using the ACK controller and specifying associatedSCRAMSecretRefs (to reference a Kubernetes Secret
for SASL/SCRAM authentication), the cluster is created successfully. However, the AWS Management Console displays the following
error message:

"You must associate AWS Secrets Manager secrets with the cluster to configure SASL/SCRAM authentication."

If we instead specify associatedSCRAMSecrets directly with the ARN of the AWS Secrets Manager secret, the error does not appear,
and the configuration works as expected. However, this approach requires us to hardcode the ARN of the Secrets Manager secret,
which is not ideal for dynamic or automated deployments.

**Expected outcome**

1. We want the associatedSCRAMSecretRefs feature to work seamlessly, allowing the ACK controller to properly associate the Kubernetes
   Secret with the MSK cluster and ensure that the AWS Console does not display the error.
2. Additionally, we would like the ARN of the AWS Secrets Manager secret to be fetched dynamically, without requiring hardcoding or
   manual intervention.
3. Lastly, the configurationInfo (if applicable) should also support dynamic generation and integration to simplify the workflow further.

**Comment by Chalapathidevops** [comment]
Hello @michaelhtm, Thank you for the clarification.

I followed the example configuration and created both the Secret resource in Secrets Manager and the Kubernetes secret as shown. However, when I verify the MSK cluster setup, I still see the following error:

"You must associate AWS Secrets Manager secrets with the cluster to configure SASL/SCRAM authentication."

Sample code:

k8s Secret
```
apiVersion: v1
kind: Secret
metadata:
  name: awsmsk
  namespace: test
data:
  password: myawsmsk-password
```
SecretsManager Secret
```
  apiVersion: secretsmanager.services.k8s.aws/v1alpha1
  kind: Secret
  metadata:
    name: awsmsk
    namespace: test
  spec:
    name: AmazonMSK_mskscrm-test
    secretString:
      key: "password"
      name: "awsmsk"
      namespace: test
  ```  

MSK Cluster:
```
    spec:
      associatedSCRAMSecretRefs:
      - from:
          name: AmazonMSK_mskscrm-test
          namespace: test
```

<img width="1477" alt="Image" src="https://github.com/user-attachments/assets/a9b9e0b1-4f91-4a58-9d7a-8457d5bcbf9e" />

**Comment by michaelhtm** [comment]
The first two are correct. When referencing it in MSK cluster though you'd need to use metadata.name of the SecretsManager Secret.
```yaml 
    spec:
      associatedSCRAMSecretRefs:
      - from:
          name: awsmsk
          namespace: test
```

**Comment by Chalapathidevops** [comment]
@michaelhtm - I have used metadata.name of the SecretsManager Secret, but still facing the same error.

<img width="1204" alt="Image" src="https://github.com/user-attachments/assets/b58591ff-0b81-4ddb-b3b3-b3c25a5dec10" />

```
apiVersion: v1
data:
  password: test-password
kind: Secret
metadata:
  name: awsmsk
  namespace: default
 ``` 
```
apiVersion: v1
items:
- apiVersion: secretsmanager.services.k8s.aws/v1alpha1
  kind: Secret
  metadata:
    name: awsmsk-secret
    namespace: default
  spec:
    name: AmazonMSK_test
    secretString:
      key: password
      name: awsmsk
      namespace: default
 ```
```
spec:
  associatedSCRAMSecretRefs:
  - from:
      name: awsmsk-secret
```
