### ISSUE TITLE
Support logical rule statements in wafv2-controller

### ISSUE THREAD

**Issue by takeshi-hatamoto** [aws-controllers-k8s/community#2534]
**Is your feature request related to a problem?**

The following code deploys a rule in labelMatchStatement.

```
  rules:
   - name: Allowbot
      priority: 12
      action:
        allow: {}
      visibilityConfig:
        metricName: Allowbot
        sampledRequestsEnabled: true
        cloudWatchMetricsEnabled: true
      statement:
        labelMatchStatement: 
          scope: LABEL
          key: "awswaf:managed:aws:bot-control:bot:name:googlebot"
```

However, when I use “orStatement” to apply the or condition of labelMatchStatement, I get the following error, which I would like to improve.

`strict decoding error: unknown field “spec.rules[12].statement.orStatement.statements”`

```
    - name: Allowbot
      priority: 13
      action:
        allow: {}
      visibilityConfig:
        metricName: Allowbot
        sampledRequestsEnabled: true
        cloudWatchMetricsEnabled: true
      statement:
        orStatement: 
          statements:
            - labelMatchStatement:
                scope: LABEL
                key: "awswaf:managed:aws:bot-control:bot:user_triggered:verified"
            - labelMatchStatement:
              scope: LABEL
              key: "awswaf:managed:aws:bot-control:bot:name:googlebot"
```

**Describe the solution you'd like**

Please let me know if you have already implemented this and if there is a way to solve this problem with orStatement.
I would like to eventually be able to use not only orStatement but also andStatement and NotStatement.
[Using logical rule statements in AWS WAF](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statements-logical.html)

**Comment by rushmash91** [comment]
Hi @takeshi-hatamoto,
Thanks for reporting this issue! The Statement fiels are implemented.

The logical statements `(orStatement, andStatement, notStatement)` are string fields that contain YAML content, rather than structured objects like your snippet. You need to use the YAML pipe `|` operator to provide the logical statement as a multi-line string. 

Here's the corrected version of your configuration:

```yaml
- name: Allowbot
  priority: 13
  action:
    allow: {}
  visibilityConfig:
    metricName: Allowbot
    sampledRequestsEnabled: true
    cloudWatchMetricsEnabled: true
  statement:
    orStatement: |
      statements:
        - labelMatchStatement:
            scope: LABEL
            key: "awswaf:managed:aws:bot-control:bot:user_triggered:verified"
        - labelMatchStatement:
            scope: LABEL
            key: "awswaf:managed:aws:bot-control:bot:name:googlebot"
```

another example: https://github.com/aws-controllers-k8s/wafv2-controller/blob/main/test/e2e/resources/rule_group_nested_statements.yaml

This should resolve your issue. Let me know if you need any clarification or continue to face the issue!
