### ISSUE TITLE
ACK S3 Controller: Ignore empty fields in adopted bucket

### ISSUE THREAD

**Issue by kalyaninikam1** [aws-controllers-k8s/community#2542]
**Describe the bug**
When upgrading the s3-ack controller version from 1.0.20 to 1.0.30, we encounter an error for adopted buckets. It's incorrectly handling the empty fields such as the website field. This issue persists when upgrading to version 1.0.33 as well.

**Steps to reproduce**
Adopt an s3 bucket using s3-ack version 1.0.20. After upgrading s3-ack version to 1.0.30, check the bucket status, it will show an error.

**Expected outcome**
There should not be any errors for adopted s3 bucket when upgrading the s3 ack version to 1.0.30 and 1.0.33.

**Environment**

* Kubernetes version: 1.32
* AWS service targeted: S3
* ACK S3 controller version: 1.0.30, 1.0.33

**Logs**
`$ kubectl describe bucket <adopted_s3_bucket_name> -n <kube_namespace>
```yaml
Name:         <adopted_s3_bucket_name>
Namespace:    <kube_namespace>
Labels:       <none>
Annotations:  services.k8s.aws/adopted: true
API Version:  s3.services.k8s.aws/v1alpha1
Kind:         Bucket
Metadata:
  Creation Timestamp:  xxxxx
  Finalizers:
    finalizers.s3.services.k8s.aws/Bucket
  Generation:        2
  Resource Version:  xxxxxxxxx
  UID:               xxxx
Spec:
  Accelerate:
  Acl:  xxxxx
  Cors:
    Cors Rules:
      Allowed Headers:
        *
      Allowed Methods:
        xxxxx
      Allowed Origins:
        xxxxx
      Expose Headers:
        xxxxx
      Allowed Headers:
        *
      Allowed Methods:
        xxxxx
      Allowed Origins:
        xxxxx
      Expose Headers:
        xxxxx
  Encryption:
    Rules:
      Apply Server Side Encryption By Default:
        Sse Algorithm:     xxxxx
      Bucket Key Enabled:  xxxxx
  Grant Full Control: xxxxx
  Grant Read:              
  Grant Read ACP:          
  Grant Write:             
  Grant Write ACP:         
  Lifecycle:
    Rules:
      Expiration:
        Days:  xxxxx
      Filter:
        Prefix:  
      Noncurrent Version Expiration:
        Noncurrent Days:  xxxxx
      Status:             xxxxx
      Transitions:
        Days:           xxxxx
        Storage Class:  xxxxx
  Logging:
    Logging Enabled:
      Target Bucket:  xxxxx
      Target Prefix:  
  Metrics:
    Id:  EntireBucket
  Name:  xxxxx
  Notification:
  Ownership Controls:
    Rules:
      Object Ownership:  xxxxx
  Policy: xxxxx               

  Public Access Block:
    Block Public AC Ls:       xxxxx
    Block Public Policy:      xxxxx
    Ignore Public AC Ls:      xxxxx
    Restrict Public Buckets:  xxxxx
  Request Payment:
    Payer:  xxxxx
  Tagging:
    Tag Set:
      Key:    xxxxx
      Value:  xxxxx
  Versioning:
    Status:  xxxxx
  Website:
Status:
  Ack Resource Metadata:
    Arn:               xxxxx
    Owner Account ID:  xxxxx
    Region:            xxxxx
  Conditions:
    Message:               api error InvalidArgument: A value for IndexDocument Suffix must be provided if RedirectAllRequestsTo is empty
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  xxxxx
    Message:               Unable to determine if desired resource state matches latest observed state
    Reason:                Error syncing property 'Website': operation error S3: PutBucketWebsite, https response error StatusCode: 400, RequestID: xxxxx, HostID: xxxxx, api error InvalidArgument: A value for IndexDocument Suffix must be provided if RedirectAllRequestsTo is empty
    Status:                Unknown
    Type:                  ACK.ResourceSynced
Events:                    <none>
```
