### ISSUE TITLE
when will ACK SQS be beta and available for user testing? 

### ISSUE THREAD

**Issue by teochenglim** [aws-controllers-k8s/community#678]
**Is your feature request related to a problem?**
I'm frustrated when SNS is working, but SQS is not and most developer need both.
Also that's no example how to create the SNS/SQS CRD

**Describe the solution you'd like**
Would like to have simple helm chart for standardise installation and example that show how to create the CRD.

**Describe alternatives you've considered**
I might write my own if it take too long. Our use case doesn't need the full feature, just basic queue and basic topic with some permission settings and tag.

@mhausenblas maybe you can help?

**Comment by jaypipes** [comment]
Hi @teochenglim, unfortunately the SQS service controller is not yet released. I don't have an exact timeline for it, but hoping to get it out into preview within the next month or so.

**Comment by rkevin-arch** [comment]
Would also like to see this as well. I've tried compiling the SQS controller from source, but am having issues (it's probably expected since it's not ready yet). Let me know if I should be making a separate issue for this.

The deployment we have is basically [vanilla](https://github.com/aws-controllers-k8s/sqs-controller/blob/main/config/controller/deployment.yaml), except it uses an image built from source, has a serviceaccount with permission to create SQS queues (in ECK), and the following extra environment variables:
```yaml
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_ACCOUNT_ID
          value: "Redacted 12 digit account ID"
        - name: ACK_ENABLE_DEVELOPMENT_LOGGING
          value: "true"
        - name: ACK_LOG_LEVEL
          value: debug
```
When creating the following custom resource:
```yaml
apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: sqs-test
  namespace: krong
spec:
  queueName: krong-test
```
The controller logs show the following error:
```
2021-07-09T07:01:41.930Z	DEBUG	ackrt	starting reconciliation	{"kind": "Queue", "namespace": "krong", "name": "sqs-test", "generation": 1, "account": "REDACTED", "role": "", "region": "us-west-2"}
2021-07-09T07:01:41.938Z	DEBUG	ackrt	marked resource as managed	{"kind": "Queue", "namespace": "krong", "name": "sqs-test", "generation": 1}
2021-07-09T07:01:42.139Z	DEBUG	ackrt	patched resource	{"kind": "Queue", "namespace": "krong", "name": "sqs-test", "generation": 1}
2021-07-09T07:01:42.139Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "queue", "request": "krong/sqs-test", "error": "MalformedInput: End of list found where not expected\n\tstatus code: 400, request id: 4f87e19c-cbf8-5e2e-bf19-b8fd3d6e2683"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```
The error is printed every 1~2s and doesn't go away until I delete the custom resource. Any help would be appreciated, thanks!
