### ISSUE TITLE
glue securityconfiguration code-generation issue with s3Encryption

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#715]
**Describe the bug**
we generated for crossplane via code-generation for aws service glue -> securityconfiguration - is the issue a problem with the code-generation ?

this works:
```
[...]
      s3Encryption:
        - s3EncryptionMode: "DISABLED"
[...]
```

with the following configuration we have an AWS Issue:

```
[...]
      s3Encryption:
        - s3EncryptionMode: "SSE-KMS"
        - kmsKeyARN: "arn:aws:kms:eu-central-1:<aws-id>:key/<kms-key-id>"
[...]
```
**Error: managed/securityconfiguration.glue.aws.crossplane.io  cannot create SecurityConfiguration in AWS: InvalidInputException: S3 EncryptionConfiguration list cannot be greater than one**

**Steps to reproduce**

```
apiVersion: glue.aws.crossplane.io/v1alpha1
kind: SecurityConfiguration
metadata:
  name: glue-securityconfiguration-4
spec:
  forProvider:
    name: glue-securityconfiguration-4
    region: eu-central-1
    encryptionConfiguration:
      cloudWatchEncryption:
        cloudWatchEncryptionMode: "SSE-KMS"
        kmsKeyARN: "arn:aws:kms:eu-central-1:<aws-id>:key/<kms-key-id>"
      jobBookmarksEncryption:
        jobBookmarksEncryptionMode: "DISABLED"
      s3Encryption:
        - s3EncryptionMode: "SSE-KMS"
        - kmsKeyARN: "arn:aws:kms:eu-central-1:<aws-id>:key/<kms-key-id>"
  providerConfigRef:
    name: default

```

**Environment**
* Using local kind-cluster with crossplane 1.1.0
* AWS service targeted glue securityconfiguration

**Comment by jaypipes** [comment]
This looks to be an issue with the upstream AWS Glue API model not matching AWS Glue API server-side validation behaviour. You should be able to do this instead and it should work:

```yaml
      s3Encryption:
        - s3EncryptionMode: "SSE-KMS"
          kmsKeyARN: "arn:aws:kms:eu-central-1:<aws-id>:key/<kms-key-id>"
```
