### ISSUE TITLE
Documentation on Errors

### ISSUE THREAD

**Issue by nmvk** [aws-controllers-k8s/community#741]
**Is your feature request related to a problem?**
Many errors in ACK are communicated through conditions. We need to document this for ACK users. For example.

I have an ElastiCache manifest file like

```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: rg
spec:
    engine: redis 
    replicationGroupID: rg
    replicationGroupDescription: test replication group
    cacheNodeType: cache.t3.micro
    numNodeGroups: 1
    atRestEncryptionEnabled: true
    transitEncryptionEnabled: true
    replicasPerNodeGroup: 6
```
As of now allowed values for `replicasPerNodeGroup`  are 0 to 5. However when someone runs `kubectl`, request would be accepted.

```
kubectl apply -f ~/Documents/rg.yaml 
replicationgroup.elasticache.services.k8s.aws/rg created
```
Currently to see errors one need to run
```
kubectl describe replicationgroup/rg
```
Response will have error conditions
```
  Conditions:
    Message:  The number of replicas per node group must be within 0 and 5.
    Status:   True
    Type:     ACK.Terminal
```

**Describe the solution you'd like**
Document to rely on terminal conditions rather than kubectl/client response.

**Describe alternatives you've considered**
N/A
