### ISSUE TITLE
Add OLM-specific generator configs for each service and the service template

### ISSUE THREAD

**Issue by komish** [aws-controllers-k8s/community#744]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
To simplify the automated creation of Operator Lifecycle Manager ("OLM") bundles for a given controller release, the controller repos need a base configuration added.

As an initial goal, I figure it makes sense to contribute one for each repo for which an e2e test exists (referring to: https://github.com/aws-controllers-k8s/community/tree/main/test/e2e). That said, I see S3 is missing here and I've done most testing against S3 so I'll throw that in as well:

* dynamodb https://github.com/aws-controllers-k8s/dynamodb-controller
* ecr https://github.com/aws-controllers-k8s/ecr-controller
* kms https://github.com/aws-controllers-k8s/kms-controller
* mq https://github.com/aws-controllers-k8s/mq-controller
* sfn https://github.com/aws-controllers-k8s/sfn-controller
* sns https://github.com/aws-controllers-k8s/sns-controller
* sqs https://github.com/aws-controllers-k8s/sqs-controller
* sqs https://github.com/aws-controllers-k8s/s3-controller

We can also add a generic config for the template

* template https://github.com/aws-controllers-k8s/template-controller

I expect these configs to live at this path: `{SERVICE}-controller/olm/olmconfig.yaml` to align with the default location being used by build scripts.

Alternatively, what services would you prefer to see? I can add those as well. 

**Describe alternatives you've considered**
The alternative is to have these configs hosted elsewhere as a relatively-static asset that can be pulled down at build-time. This alternate would require an additional step either in build automation or in the scripts that call `ack-generate olm`.

**Comment by RedbackThomson** [comment]
Actually each of the repositories you've listed in this are using the old-style bash e2e resources. All of the other repositories have transferred to the new Python e2e resources, and I'd say those are more suitable for this enhancement. A full list of those repositories is in this issue: https://github.com/aws-controllers-k8s/community/issues/735

**Comment by komish** [comment]
Ah, thanks @RedbackThomson! I'll check out the list and target that instead.

**Comment by komish** [comment]
With that in mind, here are the new targets:

- [ ] apigatewayv2 - [aws-controllers-k8s/apigatewayv2-controller](https://github.com/aws-controllers-k8s/apigatewayv2-controller)
- [ ] applicationautoscaling - [aws-controllers-k8s/applicationautoscaling-controller](https://github.com/aws-controllers-k8s/applicationautoscaling-controller)
- [ ] elasticache - [aws-controllers-k8s/elasticache-controller](https://github.com/aws-controllers-k8s/elasticache-controller)
- [ ] mq - [aws-controllers-k8s/mq-controller](https://github.com/aws-controllers-k8s/mq-controller)
- [ ] rds - [aws-controllers-k8s/rds-controller](https://github.com/aws-controllers-k8s/rds-controller)
- [ ] sagemaker - [aws-controllers-k8s/sagemaker-controller](https://github.com/aws-controllers-k8s/sagemaker-controller)
- [ ] s3 - [aws-controllers-k8s/s3-controller#11](https://github.com/aws-controllers-k8s/s3-controller)

I'll update with PR links as they come through.

**Comment by komish** [comment]
@RedbackThomson I've historically been using a configuration that looked like this.

```yaml
---
annotations:
  capabilityLevel: basic install
  shortDescription: AWS S3 Controller is a Service Controller for Managing AWS S3 Buckets
    in Kubernetes
displayName: AWS Simple Storage Service (S3) for Kubernetes
description: Manage AWS S3 Buckets from within your OpenShift cluster.
  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: Bucket
  spec: |
    name: "example-bucket-created-by-ack"
- kind: MultipartUpload
  spec: |
    bucket: "example-bucket-created-by-ack"
      key: "some-key"
maintainers:
- name: "The ACK Team"
  email: "ack@example.com"
```

## A few questions:

**Display Names:** 
I used this format for testing but it's up for adjustment.

```yaml:
displayName: AWS Simple Storage Service (S3) for Kubernetes
```

* Would you prefer this instead use the format as written in the service controller READMEs? E.g.:

```yaml:
displayName: "ACK service controller for Amazon Simple Storage Service (S3)"
```

---
**Maintainers**

What contact information should I put in the maintainer slot? I'm thinking this might vary per service?

```yaml
maintainers:
- name: "The ACK Team"
  email: "ack@example.com"
```
