### ISSUE TITLE
The AdoptedResource CRD does not work for ApplicationAutoscaling Service Controller

### ISSUE THREAD

**Issue by mbaijal** [aws-controllers-k8s/community#766]
**Describe the bug**
The AdoptedResource CRD does not work for ApplicationAutoscaling Service Controller since the `ScalingPolicy` and `ScalableTarget` Describe APIs require more than one field to work. 

**Steps to reproduce**
1. Create an endpoint in SageMaker and enable applicationAutoscaling using the AWS Console. 
2. Check using awscli to ensure that the ScalingPolicy resource exists `aws application-autoscaling describe-scaling-policies --service-namespace SageMaker --region us-west-2`.
3. [Update ApplicationAutoscaling to v0.1.1 runtime and latest code-gen](https://github.com/mbaijal/applicationautoscaling-controller/tree/0.1.1-on-sagemaker-tests-for-hap-2). Verify that you have the AdoptedResource CRD. 
4. Now try to adopt the resource into Kubernetes using a spec file as follows - 
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adoptedscalingpolicy
spec:
  aws:
    nameOrID: "endpoint/ep-name/variant/AllTraffic"
  kubernetes:
    group: applicationautoscaling.services.k8s.aws
    kind: ScalingPolicy
    metadata:
      name: adopted_scaling_policy
```
5. check that the resource was adopted using `kubectl get scalingpolicies.applicationautoscaling.services.k8s.aws`

**Expected outcome**
Resource should have been adopted into k8s

**Actual Outcome**
The following error in the pod logs - 
```
2021-05-11T10:24:55.574Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "adoptedresource", "request": "default/adoptedscalingpolicy", "error": "InvalidParameter: 1 validation error(s) found.\n- missing required field, DescribeScalingPoliciesInput.ServiceNamespace.\n"}
```

**Environment**
Tested using a Kind Cluster

* Kubernetes version: 16.*
* Using EKS (yes/no), if so version?:  no
* AWS service targeted (S3, RDS, etc.): ApplicationAutoscaling

**Comment by RedbackThomson** [comment]
As per the suggestion above, I have included the `additionalKeys` map as part of `AWSIdentifiers`. 

Runtime PR: https://github.com/aws-controllers-k8s/runtime/pull/13
Code-Generator PR: https://github.com/aws-controllers-k8s/code-generator/pull/62

An example of it working for this use case:

I put a new scaling policy using the AWS CLI:
```bash
aws application-autoscaling put-scaling-policy --policy-name test-policy --service-namespace sagemaker --resource-id endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1 --scalable-dimension sagemaker:variant:DesiredInstanceCount --policy-type TargetTrackingScaling --target-tracking-scaling-policy-configuration file://example-scaling-policy.json
```

Then attempted to adopt the resulting scaling policy given the return ARN and `serviceNamespace` additional key:
```yaml
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-xgboost-scaling-policy
spec:
  aws:
    arn: arn:aws:autoscaling:us-west-2:<redacted>:scalingPolicy:d908645f-4669-4db7-8c7e716484b67601:resource/sagemaker/endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1:policyName/test-policy
    additionalKeys:
      serviceNamespace: sagemaker
  kubernetes:
    group: applicationautoscaling.services.k8s.aws
    kind: ScalingPolicy
```

It successfully reproduced the spec:
```
Name:         adopt-xgboost-scaling-policy
Namespace:    default
Labels:       <none>
Annotations:  services.k8s.aws/adopted: true
API Version:  applicationautoscaling.services.k8s.aws/v1alpha1
Kind:         ScalingPolicy
Metadata:
  Creation Timestamp:  2021-05-12T23:06:14Z
  Finalizers:
    finalizers.applicationautoscaling.services.k8s.aws/ScalingPolicy
  Generation:        1
  Resource Version:  1138911
  Self Link:         /apis/applicationautoscaling.services.k8s.aws/v1alpha1/namespaces/default/scalingpolicies/adopt-xgboost-scaling-policy
  UID:               007b3a31-040d-4e5f-b7fd-449d85ad150e
Spec:
  Policy Name:         test-policy
  Policy Type:         TargetTrackingScaling
  Resource ID:         endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1
  Scalable Dimension:  sagemaker:variant:DesiredInstanceCount
  Service Namespace:   sagemaker
  Target Tracking Scaling Policy Configuration:
    Predefined Metric Specification:
      Predefined Metric Type:  SageMakerVariantInvocationsPerInstance
    Target Value:              70
Status:
  Ack Resource Metadata:
    Owner Account ID:  <redacted>
  Alarms:
    Alarm ARN:   arn:aws:cloudwatch:us-west-2:<redacted>:alarm:TargetTracking-endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1-AlarmHigh-ab739cb9-0ef3-4bd5-8d8e-c2f13dfe8dd5
    Alarm Name:  TargetTracking-endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1-AlarmHigh-ab739cb9-0ef3-4bd5-8d8e-c2f13dfe8dd5
    Alarm ARN:   arn:aws:cloudwatch:us-west-2:<redacted>:alarm:TargetTracking-endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1-AlarmLow-e8f129ef-7b1e-44ed-8ef4-54fe12d3b481
    Alarm Name:  TargetTracking-endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1-AlarmLow-e8f129ef-7b1e-44ed-8ef4-54fe12d3b481
  Conditions:
  Policy ARN:  arn:aws:autoscaling:us-west-2:<redacted>:scalingPolicy:d908645f-4669-4db7-8c7e-716484b67601:resource/sagemaker/endpoint/xgboost-endpoint-znwbi73nyztvdah/variant/variant-1:policyName/test-policy
Events:        <none>
```
