### ISSUE TITLE
Missing merge logic in `resource.sdkFind`  when CRD field is renamed

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#773]
**Describe the bug**

`ack-generate` doesn't generate a complete "merge" logic in `sdkFind` when one the CRD fields is renamed, and the related API call returns a list of objects (e.g `ecr.DescribeRepositories)`

**Steps to reproduce**
Regenerate ECR controller with the following configuration
```yaml
resources:
  Repository:
    renames:
      operations:
        CreateRepository:
          input_fields:
            RepositoryName: Name
  
```

Note the following diff
```bash
$ git diff main

@@ -108,16 +109,6 @@ func (rm *resourceManager) sdkFind(
                        tmpARN := ackv1alpha1.AWSResourceName(*elem.RepositoryArn)
                        ko.Status.ACKResourceMetadata.ARN = &tmpARN
                }
-               if elem.RepositoryName != nil {
-                       if ko.Spec.RepositoryName != nil {
-                               if *elem.RepositoryName != *ko.Spec.RepositoryName {
-                                       continue
-                               }
-                       }
-                       ko.Spec.RepositoryName = elem.RepositoryName
-               } else {
-                       ko.Spec.RepositoryName = nil
-               }
                if elem.RepositoryUri != nil {
                        ko.Status.RepositoryURI = elem.RepositoryUri
                } else {
```

**Expected outcome**
The delete block of code should be changed to something like instead:

```go
if elem.RepositoryName != nil {
	if ko.Spec.Name != nil {
		if *elem.RepositoryName != *ko.Spec.Name {
			continue
		}
	}
	ko.Spec.Name = elem.RepositoryName
} else {
	ko.Spec.Name = nil
}
```

**Comment by A-Hilaly** [comment]
Actually I was able to fix to issue by providing a more complete `generator.yaml` :

```yaml
resources:
  Repository:
    renames:
      operations:
        CreateRepository:
          input_fields:
            RepositoryName: Name
        DeleteRepository:
          input_fields:
            RepositoryName: Name
        DescribeRepositories:
          input_fields:
            RepositoryName: Name
    list_operation:
      match_fields:
        - Name
```

I'm currently wondering if `ack-generate` should error or panic if `list_operation.match_fields` doesn't contain any known fields (for example renamed fields)
