### ISSUE TITLE
helm chart values OutofSync

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#787]
**Describe the bug**
Values.yaml does not include `AWS_ACCOUNT_ID`, `ACK_ENABLE_DEVELOPMENT_LOGGING`, `ACK_LOG_LEVEL`

**Steps to reproduce**
```
./scripts/build-controller-release.sh $SERVICE $RELEASE_VERSION
```

**Expected outcome**
```
aws:  
  region: ""
  accountID: ""

ack:
  enable_development_logging: false
  log_level: info
```

**Comment by jaypipes** [comment]
@surajkota I would prefer:

```yaml
aws:
  region: ""
  account_id: ""
log:
  enable_development_logging: true
  log_level: INFO
```
