### ISSUE TITLE
Allow NestedFields to support Lists

### ISSUE THREAD

**Issue by mbaijal** [aws-controllers-k8s/community#789]
**Is your feature request related to a problem?**
Some CRD fields contain a list of nested objects which should also be allowed to be referred/marked for various purposes. Refer to [Code-Generator PR#47](https://github.com/aws-controllers-k8s/code-generator/pull/47). 

An example of this use case would be the [DescribeScalableTargets](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html) API call. 
At the moment, this API does not return any status field in the response and hence I would like to be able to add the CreationTime as a metadata field using something like - 
```
resources:
  ScalableTarget:
    fields:
      ResourceID:
        is_read_only: true
        is_arn: true
        from:
          operation: DescribeScalableTargets
          path: ScalableTargets..ResourceId
```

This currently fails with the following error, but should successfully add the desired sub-field to the object status:
```
panic: unknown additional Status field with Op: DescribeScalableTargets and Path: ScalableTargets..CreationTime
```

**Describe the solution you'd like**
Support for parsing CRD subfields that are lists.
