### ISSUE TITLE
Status field for most/all spec fields

### ISSUE THREAD

**Issue by nmvk** [aws-controllers-k8s/community#814]
**Is your feature request related to a problem?**
Currently we do not have status fields for all the spec fields. This can be problematic as one might not be able to get the required server side information using k8 APIs.

For example `aws elasticache describe-replication-groups` provides many information which would be beneficial to be in status.

**Encryption**
```
"TransitEncryptionEnabled": true,
 "AtRestEncryptionEnabled": true,
```

**Log delivery configuration**

```
"LogDeliveryConfigurations": [
    {
        "LogType": "slow-log",
        "DestinationType": "cloudwatch-logs",
        "DestinationDetails": {
            "CloudWatchLogsDetails": {
                "LogGroup": "lognew"
            }
        },
        "LogFormat": "json",
        "Status": "active"
    }
] 
```

**Describe the solution you'd like**
Status fields for most/all spec fields

**Describe alternatives you've considered**
Only add very critical server side information in status

**Comment by surajkota** [comment]
+1
We also had to add a workaround for Endpoint resource in SageMaker  -
https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/pkg/resource/endpoint/custom_set_output.go#L64

EndpointConfigName is already part of Spec but the customer might want to look at service side value

**Comment by jaypipes** [comment]
@nmvk all you should need to do is add the following to the `generator.yaml` file for elasticache-controller:

```yaml
resources:
  ReplicationGroup:
    fields:
      TransitEncryptionEnabled:
        from:
          operation: DescribeReplicationGroups
          path: TransitEncryptionEnabled
        is_read_only: true
      AtRestEncryptionEnabled:
        from:
          operation: DescribeReplicationGroups
          path: AtRestEncryptionEnabled
        is_read_only: true
      LogDeliveryConfigurations:
        from:
          operation: DescribeReplicationGroups
          path: LogDeliveryConfigurations
        is_read_only: true
```
