### ISSUE TITLE
Conversion issue for sesv2/configurationseteventdestination

### ISSUE THREAD

**Issue by kelvinwijaya** [aws-controllers-k8s/community#898]
**Describe the bug**

I am leveraging on code-generator tools to generate the crossplane provider-aws resource template for the api and controllers

```
ERRO Running error: buildir: analysis skipped: errors in package: [/provider-aws/pkg/controller/sesv2/configurationseteventdestination/zz_conversions.go:48:9: elem declared but not used] 09:06:52 [FAIL]
```
GO show that the elem in the loop is not used and  it wont compile:

Generated:
```
for _, elem := range resp.EventDestinations {
		found = true
		break
	}
```

**Steps to reproduce**

In `crossplane/provider-aws`, run : `make services SERVICES=sesv2`

OR

In `aws-controllers-k8s/code-generator`, run: `go run -tags codegen cmd/ack-generate/main.go crossplane sesv2 --provider-dir ../provider-aws`

**Expected outcome**

The elem members should be populated in the For loop

```
for _, elem := range resp.EventDestinations {
		if elem.{Members} != nil {
			found = true
			break
		}
	}
```

Referencing ses api [spec](https://github.com/aws/aws-sdk-go/blob/v1.37.4/models/apis/sesv2/2019-09-27/api-2.json)
Based on the memberRefs, EventDesination has valid members (Name, Enabled, etc…)  , then by right it should be iterated in the for loop to populate all the members as seen from the code: [#L412](https://github.com/aws-controllers-k8s/code-generator/blob/564da95638a11004f7e214cd4d8b37ef3463c617/pkg/generate/code/set_resource.go#L412), [#L447](https://github.com/aws-controllers-k8s/code-generator/blob/564da95638a11004f7e214cd4d8b37ef3463c617/pkg/generate/code/set_resource.go#L447), [#L515](https://github.com/aws-controllers-k8s/code-generator/blob/564da95638a11004f7e214cd4d8b37ef3463c617/pkg/generate/code/set_resource.go#L515).

**Environment**

* Kubernetes version: kindest/node:v1.16.15
* Using EKS (yes/no), if so version? no
* AWS service targeted : SESv2

cc @muvaf

**Comment by RedbackThomson** [comment]
Hey Kelvin, thanks for reaching out. I've generated the SESv2 controller to replicate this issue and I see it happening as part of the sdkFind.

From what I understand, the reason the code generator does not attempt to match members is because the fields from `EventDestination` (`CloudWatchDestination`, `Enabled`, etc.) are in the root of the struct, whereas those same members, in the `CreateConfigurationSetEventDestination`, exist inside the `.EventDestination` struct (`EventDestination.Enabled`). The generator is not aware that it needs to match these values because they aren't reachable from the same member path.

However, for this method, we are simply trying to determine which of the returned `EventDestination` object matches the one in the spec. We can achieve this by matching the `EventDestinationName` field (set in the spec) with the `Name` field in `EventDestination` - all this requires is renaming `EventDestinationName` to `Name`. This is how we solve the same problem for S3 - renaming `Bucket` to `Name` in the `CreateBucket` and `DeleteBucket` calls. Here is the configuration change that should be added to the `generator.yaml`:
```yaml
operations:
  GetConfigurationSetEventDestinations:
    primary_identifier_field_name: Name
resources:
  ConfigurationSetEventDestination:
    renames:
      operations:
        CreateConfigurationSetEventDestination:
          input_fields:
            EventDestinationName: Name
        DeleteConfigurationSetEventDestination:
          input_fields:
            EventDestinationName: Name
```

However, this fix will only populate the `Spec.Name` field in the returned value. I believe in order to populate the other values (such as `Spec.EventDestination.CloudWatchDestination = elem.CloudWatchDestination`), you'll need a custom hook. Unfortunately you can't just do `Spec.EventDestination = elem` because they are different Go types (`EventDestinationDefinition` vs `EventDestination`).
