### ISSUE TITLE
RDS DBInstance Status never gets updated, stays in creating

### ISSUE THREAD

**Issue by JamesClonk** [aws-controllers-k8s/community#923]
**Describe the bug**
When using the rds-controller and creating a `DBInstance` resource, the status of that resource never gets updated beyond the initial creation. Even hours later after the RDS DB instance on AWS is long since `Available`, the status on the resource still shows `creating` and doesn't list any of the additionally expected properties like `Endpoint` for example. The rds-controller does not seem to update or reconcile DBInstance status after the initial createDBInstance call towards AWS RDS.

**Steps to reproduce**
- deploy rds-controller
- create a sample `DBInstance`:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: example-db-secret
  namespace: example
type: Opaque
stringData:
  password: super-safe-example-secret
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: example-db
  namespace: example
spec:
  allocatedStorage: 10
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: example-db
  engine: postgres
  engineVersion: "13.2"
  masterUsername: root
  masterUserPassword:
    namespace: example
    name: example-db-secret
    key: password
```
- observe that the status never leaves `creating`, and Db Instance Port never changes to != 0:
```yaml
$ kubectl -n example describe dbinstance example-db
...
Status:
  ...
  Db Instance Port:           0
  Db Instance Status:         creating
...
```

**Expected outcome**
After the RDS DB instance reaches status `Available`on AWS it should reflect that status on the K8s `DBInstance` resource. The `DBInstance` resource should now contain a field `Endpoint` with the respective value, also `DBInstancePort` should not be empty / `0` anymore.

**Environment**
* EKS, Kubernetes version 1.20
* rds-controller, v0.0.5 deployed via Helm chart
* AWS RDS - Postgres
