### ISSUE TITLE
Want to deploy ACK controllers from helm repository

### ISSUE THREAD

**Issue by paulcarlton-ww** [aws-controllers-k8s/community#958]
**Is your feature request related to a problem?**
Although #461 and #550 are closed I still can't work out how to access the helm repository that the ACK controller helm charts are deployed to.

**Describe the solution you'd like**
Be able to do helm repo add <url> to get access to helm charts. My actual preferred approach is to create a 'helmrepositories.source.toolkit.fluxcd.io' custom resource that can be used to install ACK controllers using the [Flux2 Helm-Controller](https://github.com/fluxcd/helm-controller/blob/main/docs/spec/README.md).

**Describe alternatives you've considered**
Alternative is to reference the helm charts directory in the github repo for each ACK controller

**Comment by vijtrip2** [comment]
Helm repo is setup and functional. Are you exporting following variable before pulling chart? `export HELM_EXPERIMENTAL_OCI=1`

Please see [this](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/) doc which installs ACK controllers using Helm.

And looks like the support for OCI charts is yet not present in fluxcd, but the issue is open.
https://github.com/fluxcd/source-controller/issues/124

**Comment by dervos** [comment]
I worked around this by using the GitRepository source kind instead of HelmRepository:
``` yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: s3-controller
spec:
  interval: 1h0m0s
  ref:
    tag: v0.0.3
  url: https://github.com/aws-controllers-k8s/s3-controller
```

And referencing the chart location in the helm release:
``` yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-s3-controller
spec:
  releaseName: ack-s3-controller
  chart:
    spec:
      chart: ./helm/
      sourceRef:
        kind: GitRepository
        name: s3-controller
```

Keep in mind that you're now relying on the referenced repositories versioning instead of referencing the helm version in your HelmRelease, which can have unexpected side-effects.
