### ISSUE TITLE
generated ClusterServiceVersion base `annotations.containerImage` needs to use the new image repository format

### ISSUE THREAD

**Issue by komish** [aws-controllers-k8s/community#967]
**Describe the bug**
When using code-generator to generator OLM assets, there is a templated value for `annotations.containerImage` in the ClusterServiceVersion that gets generated, and it uses the old format.

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    ...
    containerImage: public.ecr.aws/aws-controllers-k8s/controller:elasticache-v0.0.5
    ...
  name: ack-elasticache-controller.v0.0.0
```

containerImage should match the new format, seen here: https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/helm/values.yaml#L6

**Steps to reproduce**
```
ACK_GENERATE_OLM=true make build-controller SERVICE=elasticache
```

**Expected outcome**
This is a metadata value and doesn't affect runtime, but does get represented in OpenShift UIs so it should match what we actually want out of the box so users are not misled.

**Additional Info**
The template for this value is here:

https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/config/manifests/bases/clusterserviceversion.yaml.tpl#L10

The underlying struct backing this template is here:
https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/olm/types.go#L56-L64

The default values that get rendered are here:
https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/olm/olm.go#L102-L135

The controller image was static historically, so there may be some logistics here that need to change to properly compose the new value that you will need here.
